## --------------------------------------------------------------------------
## Spring Properties
## --------------------------------------------------------------------------

# MongoDB connection URI
spring.data.mongodb.uri=mongodb://${MONGODB_AUTHORITY}/config-service?authSource=admin&appname=config-service&ssl=false

## --------------------------------------------------------------------------
## Custom Application Properties
## --------------------------------------------------------------------------
de.heuboe.vmis2.config.service.vrzMode = true
de.heuboe.vmis2.config.service.stagingMode = true
de.heuboe.vmis2.config.service.systemName = C2VBA 

grpc.client.geoManager.address=

de.heuboe.vmis2.config.service.dataChangeKafkaTopic=VRZ-DataChange
de.heuboe.vmis2.config.service.itemsKafkaTopic=ConfigSrv-item
de.heuboe.vmis2.config.service.relsKafkaTopic=ConfigSrv-rel

de.heuboe.vmis2.config.service.chunkNodesAmount=0

de.heuboe.vmis2.config.service.activationKafkaTopic.autostart=false
de.heuboe.vmis2.config.service.snapshotKafkaTopic.autostart=false
de.heuboe.vmis2.config.service.dataChangeTriggerKafkaTopic.autostart=false

## --------------------------------------------------------------------------
## Kafka Properties
## --------------------------------------------------------------------------
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP}

spring.kafka.client-id=C2VBA-ConfigService
spring.kafka.consumer.group-id=C2VBA-ConfigService

spring.kafka.producer.properties.max.request.size=5242880
