server.port=4795

# WLS web service settings
#wls.protocol=http
wls.port=8087
geo.service.port=4926

wls.mongodb.uri=mongodb://he3-w7v/wlsC2VBATestps07?appName=wls

wls.system.version=4.9

map.pathname=C:/Users/peters/Desktop/C2VBA/C2VBA-here-map/_t_geom_by_SRC_HERE4DEBY_ZVM_S221R1_frc3__202207131321.csv
#map.pathname=map/Feinnetz_link.shp
map.srid=32632

vms.filename=map/KonfTab_Fischbach.txt;map/KonfTab_Freimann.txt

#www.filename=map/www_v0.9.txt
www.filename=map/www_v1.0.txt

sdb.filename=map/StrategieDefinition_v0.16.txt

sdb.route.fileDir=map/strategyRouteLocations

# OpenLR settings
openLR.encoder.config=openLR-encoder.xml
openLR.decoder.config=openLR-decoder.xml

tmc.filename=map/LCL-20.0.csv
tmc.version=D01:20.0

road.shapeFileDir=map/roadShapefile

aq.location.file=map/aq-location.csv

# MQ- and UFD supply
q.sued.filename=map/C2VBA-Q-Suedbayern-5-1.csv

#q.nord.filename=map/C2VBA-Q-Nordbayern.csv
q.nord.filename=map/C2VBA-Q-Nordbayern-2-add.csv


# WLS service settings
wls.srid=32632
wls.poolSize=10


cfg.check.kri2UzFile=map/kri2uz.csv
cfg.check.wancomKeyFileDir=D:/Develop/Git/C2VBA/wls-project-sdbby/src/test/resources/wancomStatistics


# gRPC config service connection
#grpc.client.ConfigService.address=dns:///hannahn-wx:9090
grpc.client.ConfigService.address=dns:///worker1.d.c2vba.heuboe.hbintern:31100
grpc.client.ConfigService.maxInboundMessageSize=30000000
grpc.client.ConfigService.negotiationType=PLAINTEXT

