{
 "title": "JMX exporter prometheus",
 "description": "Complete dashboard using metrics from prometheus JMX exporter, with drill down per release > pod",
 "tags": [ "JVM" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "type", "label": "Type", "query": "label_values(jvm_info, job)" },
   {
    "name": "app",
    "label": "Application",
    "query": "label_values(jvm_info{job=\"$type\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(jvm_memory_bytes_used{area=\"heap\",instance=~\"$app\"})*100) / sum(jvm_memory_bytes_max{area=\"heap\",instance=~\"$app\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(process_start_time_seconds{instance=~\"$app\"})*1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{instance=~\"$app\"})"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_info{instance=~\"$app\"}"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",instance=~\"$app\"}",
     "legendFormat": "Used {{instance}}"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",instance=~\"$app\"}",
     "legendFormat": "Max {{instance}}"
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",instance=~\"$app\"}",
     "legendFormat": "Used  {{instance}}"
    }
   ]
  },
  {
   "title": "Eden Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{instance=~\"$app\", pool=~\".* Eden Space\"}",
     "legendFormat": "Max  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$app\", pool=~\".* Eden Space\"}",
     "legendFormat": "Used  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{instance=~\"$app\", pool=~\".* Eden Space\"}",
     "legendFormat": "Committed  {{instance}}"
    }
   ]
  },
  {
   "title": "Old Gen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{instance=~\"$app\", pool=~\".* Old Gen\"}",
     "legendFormat": "Max  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$app\", pool=~\".* Old Gen\"}",
     "legendFormat": "Used  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{instance=~\"$app\", pool=~\".* Old Gen\"}",
     "legendFormat": "Committed  {{instance}}"
    }
   ]
  },
  {
   "title": "Survivor Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{instance=~\"$app\", pool=~\".* Survivor Space\"}",
     "legendFormat": "Max  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$app\", pool=~\".* Survivor Space\"}",
     "legendFormat": "Used  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{instance=~\"$app\", pool=~\".* Survivor Space\"}",
     "legendFormat": "Committed  {{instance}}"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{instance=~\"$app\", pool=\"Metaspace\"}",
     "legendFormat": "Max {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$app\", pool=\"Metaspace\"}",
     "legendFormat": "Used {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{instance=~\"$app\", pool=\"Metaspace\"}",
     "legendFormat": "Committed {{instance}}"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{instance=~\"$app\", pool=\"Compressed Class Space\"}",
     "legendFormat": "Max {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$app\", pool=\"Compressed Class Space\"}",
     "legendFormat": "Used {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{instance=~\"$app\", pool=\"Compressed Class Space\"}",
     "legendFormat": "Committed {{instance}}"
    }
   ]
  },
  {
   "title": "Code Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_max{instance=~\"$app\", pool=~\"Code.*\"}) by (instance)",
     "legendFormat": "Max {{instance}}"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used{instance=~\"$app\", pool=~\"Code.*\"}) by (instance)",
     "legendFormat": "Used {{instance}}"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_committed{instance=~\"$app\", pool=~\"Code.*\"}) by (instance)",
     "legendFormat": "Committed {{instance}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=~\"$app\"}",
     "legendFormat": "JVM current threads  {{instance}}"
    },
    {
     "expr": "jvm_threads_daemon{instance=~\"$app\"}",
     "legendFormat": "JVM daemon threads {{instance}}"
    },
    {
     "expr": "jvm_threads_deadlocked{instance=~\"$app\"}",
     "legendFormat": "JVM deadlocked threads  {{instance}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{instance=~\"$app\"}",
     "legendFormat": "{{gc}}  {{instance}}"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$app\"}[5m])",
     "legendFormat": "{{gc}} {{instance}}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{instance=~\"$app\"}",
     "legendFormat": "loaded  {{instance}}"
    }
   ]
  }
 ]
}