{
 "title": "Kafka Server",
 "description": "Overview over the Kafka Servers",
 "tags": [ "kafka" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "kafka_server",
    "label": "Kafka-Server",
    "query": "label_values(process_cpu_seconds_total{job=\"kafka_service_exporter\"} , host)"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Kafka-Service-Exporters",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=\"kafka_service_exporter\"})"
    }
   ]
  },
  {
   "title": "Running Kafka-JMX-Exporter",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=\"kafka_jmx_exporter\"})"
    }
   ]
  },
  {
   "title": "Running Zookeeper-JMX-Exporter",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=\"zookeeper_jmx_exporter\"})"
    }
   ]
  },
  {
   "title": "Cluster-Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "3" }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Idle cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{host=~\"$kafka_server\",mode=\"idle\"}[2m])) * 100",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1{host=~\"$kafka_server\"})",
     "legendFormat": "load 1m"
    },
    {
     "expr": "sum(node_load5{host=~\"$kafka_server\"})",
     "legendFormat": "load 5m"
    },
    {
     "expr": "sum(node_load15{host=~\"$kafka_server\"})",
     "legendFormat": "load 15m"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{host=~\"$kafka_server\"}) - sum(node_memory_MemFree_bytes{host=~\"$kafka_server\"}) - sum(node_memory_Buffers_bytes{host=~\"$kafka_server\"}) - sum(node_memory_Cached_bytes{host=~\"$kafka_server\"})",
     "legendFormat": "memory usage"
    },
    {
     "expr": "sum(node_memory_Buffers_bytes{host=~\"$kafka_server\"})",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "sum(node_memory_Cached_bytes{host=~\"$kafka_server\"})",
     "legendFormat": "memory cached"
    },
    {
     "expr": "sum(node_memory_MemFree_bytes{host=~\"$kafka_server\"})",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal_bytes{host=~\"$kafka_server\"}) - sum(node_memory_MemFree_bytes{host=~\"$kafka_server\"}) - sum(node_memory_Buffers_bytes{host=~\"$kafka_server\"}) - sum(node_memory_Cached_bytes{host=~\"$kafka_server\"})) / sum(node_memory_MemTotal_bytes{host=~\"$kafka_server\"})) * 100"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Disk Reads Completed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{host=~\"$kafka_server\",device=~\"sd.*\"}[5m])",
     "legendFormat": "{{device}} - {{host}}"
    }
   ]
  },
  {
   "title": "Disk Writes Completed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{host=~\"$kafka_server\",device=~\"sd.*\"}[5m])",
     "legendFormat": "{{device}} - {{host}}"
    }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{device=~\"sd.*\", host=~\"$kafka_server\"}[5m])",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Disk free",
   "type": "graph",
   "description": "Free disk space",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "min(node_filesystem_free_bytes{host=~\"$kafka_server\",mountpoint=\"/var/data/kafka\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Network received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo\"}[5m]))",
     "legendFormat": "data recieved"
    }
   ]
  },
  {
   "title": "Network transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo\"}[5m]))",
     "legendFormat": "data transmitted"
    }
   ]
  }
 ]
}