{
 "title": "Kafka Service",
 "description": "Kafka resource usage and throughput",
 "tags": [ "Kafka" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kafka_brokers, host)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_topic_partition_current_offset{host=\"$instance\",topic!=\"__consumer_offsets\",topic!=\"--kafka\"}, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "records in per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{host=\"$instance\", topic=~\"$topic\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{host=\"$instance\", topic=~\"$topic\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "records consume per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{host=~'$instance',topic=~\"$topic\"}[5m])/(5*60))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{host=~'$instance',topic=~\"$topic\"}[5m])/(5*60)) by (consumergroup)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "record lag by  consumer group",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{host=\"$instance\"}) by (consumergroup)  ",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "number of vmis2 connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(kafka_connection_count)", "legendFormat": "total" },
    {
     "expr": "sum(kafka_connection_count) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Partitions per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partitions{host=\"$instance\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}