{
 "title": "MongoDB",
 "description": "If you have the node_exporter running on the mongo instance, you will also get some useful alert panels related to disk io and cpu.",
 "tags": [
  "prometheus",
  "mongodb"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mongodb_connections, host)"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Query Metrics for $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{host=~\"$host\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_metrics_document_total{host=~\"$host\"}[$interval])) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{host=~\"$host\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Query Metrics for $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{host=~\"$host\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_metrics_document_total{host=~\"$host\"}[$interval])) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{host=~\"$host\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Query Metrics for $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{host=~\"$host\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_metrics_document_total{host=~\"$host\"}[$interval])) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{host=~\"$host\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Replica Set Metrics for $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "host" },
  {
   "title": "Member Health",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "min(mongodb_mongod_replset_number_of_members{host=~\"$host\"})",
     "legendFormat": "# members"
    },
    {
     "expr": "sum(mongodb_mongod_replset_member_health{host=~\"$host\"})",
     "legendFormat": "healthy members"
    }
   ]
  },
  {
   "title": "Member State",
   "type": "graph",
   "description": "See which node is currently acting as the primary, secondary, ...",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(mongodb_mongod_replset_member_state{host=~\"$host\"}) by (state)",
     "legendFormat": "{{state}} - {{name}}"
    }
   ]
  },
  {
   "title": "Replica Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_repl_total{host=~\"$host\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Replica Set Metrics for $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Member Health",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "min(mongodb_mongod_replset_number_of_members{host=~\"$host\"})",
     "legendFormat": "# members"
    },
    {
     "expr": "sum(mongodb_mongod_replset_member_health{host=~\"$host\"})",
     "legendFormat": "healthy members"
    }
   ]
  },
  {
   "title": "Member State",
   "type": "graph",
   "description": "See which node is currently acting as the primary, secondary, ...",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(mongodb_mongod_replset_member_state{host=~\"$host\"}) by (state)",
     "legendFormat": "{{state}} - {{name}}"
    }
   ]
  },
  {
   "title": "Replica Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 29 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_repl_total{host=~\"$host\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Replica Set Metrics for $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Member Health",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "min(mongodb_mongod_replset_number_of_members{host=~\"$host\"})",
     "legendFormat": "# members"
    },
    {
     "expr": "sum(mongodb_mongod_replset_member_health{host=~\"$host\"})",
     "legendFormat": "healthy members"
    }
   ]
  },
  {
   "title": "Member State",
   "type": "graph",
   "description": "See which node is currently acting as the primary, secondary, ...",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(mongodb_mongod_replset_member_state{host=~\"$host\"}) by (state)",
     "legendFormat": "{{state}} - {{name}}"
    }
   ]
  },
  {
   "title": "Replica Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 36 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_repl_total{host=~\"$host\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Health metrics for $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }, "repeat": "host" },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 43 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(mongodb_instance_uptime_seconds{host=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 43 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(mongodb_connections{host=~\"$host\",state=\"available\"})"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 43 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(mongodb_connections{host=~\"$host\",state=\"current\"})"
    }
   ]
  },
  { "title": "Health metrics for $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 48 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(mongodb_instance_uptime_seconds{host=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 48 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(mongodb_connections{host=~\"$host\",state=\"available\"})"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 48 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(mongodb_connections{host=~\"$host\",state=\"current\"})"
    }
   ]
  },
  { "title": "Health metrics for $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 53 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(mongodb_instance_uptime_seconds{host=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 53 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(mongodb_connections{host=~\"$host\",state=\"available\"})"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 53 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(mongodb_connections{host=~\"$host\",state=\"current\"})"
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Oplog Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(mongodb_mongod_replset_oplog_size_bytes{host=~\"$host\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "decmbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "mongodb_memory{host=~\"$host\",type=~\"resident|virtual\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_network_bytes_total{host=~\"$host\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Oplog Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_replset_oplog_head_timestamp{host=~\"$host\"}[5m])) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"mongo_node_exporter\", device=~\"sd.*\", host=~\"$host\"}[5m])",
     "legendFormat": "{{device}} - {{host}}"
    }
   ]
  },
  { "title": "CPU $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 }, "repeat": "host" },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{host=~\"$host\", mode=~\"user|system|iowait\"}[5m])) by (host, mode) / ignoring(mode) group_left count(node_cpu_seconds_total{host=~\"$host\",mode=\"idle\"}) by (host)",
     "legendFormat": "{{host}} - {{mode}}"
    }
   ]
  },
  { "title": "CPU $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{host=~\"$host\", mode=~\"user|system|iowait\"}[5m])) by (host, mode) / ignoring(mode) group_left count(node_cpu_seconds_total{host=~\"$host\",mode=\"idle\"}) by (host)",
     "legendFormat": "{{host}} - {{mode}}"
    }
   ]
  },
  { "title": "CPU $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{host=~\"$host\", mode=~\"user|system|iowait\"}[5m])) by (host, mode) / ignoring(mode) group_left count(node_cpu_seconds_total{host=~\"$host\",mode=\"idle\"}) by (host)",
     "legendFormat": "{{host}} - {{mode}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Disk Reads Completed (IOPS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{job=\"mongo_node_exporter\", device=\"sdb\", host=~\"$host\"}[5m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk Writes Completed (IOPS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{job=\"mongo_node_exporter\", device=~\"sdb\", host=~\"$host\"}[5m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk Read (Bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{host=~\"$host\", device=~\"sdb\"}[5m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk Writes (Bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{host=~\"$host\", device=\"sdb\"}[5m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk Usage [%]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - node_filesystem_free_bytes{job=\"mongo_node_exporter\", mountpoint=\"/var/lib/mongo\", host=~\"$host\"} * 100 / node_filesystem_size_bytes{job=\"mongo_node_exporter\", mountpoint=\"/var/lib/mongo\", host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{job=\"mongo_node_exporter\", mountpoint=\"/var/lib/mongo\", host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}