---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    label.servicename: "c2vba-parameter-tool-app_D"
    label.gitversion: "c2vba-parameter-tool-app_D_1.3.0.2"
    app: c2vba-parameter-tool-app
    log-type: spring-actuator
  name: c2vba-parameter-tool-app
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: c2vba-parameter-tool-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: c2vba-parameter-tool-app
    spec:
      initContainers:
      - name: initialize-parameter-data
        image: heuboe/c2vba/c2vba-parameter-tool-app-data:1.0.0
        command: ['/bin/sh','-c']
        args: ["rm -rf /parameter-data/converter-jars; rm -rf /parameter-data/parameter-definitions; mkdir /parameter-data/converter-jars; cp -R /app/resources/data/* /parameter-data;"]
        volumeMounts:
        - name: parameter-data
          mountPath: /parameter-data
      containers:
      - name: app
        image: heuboe/heuboecommons/heuboe-parameter-tool-app:1.3.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: actuator
          protocol: TCP
        envFrom:
        - secretRef:
            name: application-environment
        env:
        - name: "SPRING_PROFILES_ACTIVE"
          value: "default,${SYSTEM_NAME}"
        - name: application.name
          value: "c2vba-parameter-tool-app"
        - name: application.instance
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "info.kubernetes.node.name"
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: "info.kubernetes.pod.name"
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "info.kubernetes.pod.namespace"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "JAVA_TOOL_OPTIONS"
          value: "-XX:MaxRAMPercentage=75"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: parameter-data
          mountPath: /parameter-data
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /actuator/health
            port: actuator
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /actuator/health
            port: actuator
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          limits:
            cpu: "1000m"
            memory: 500Mi
          requests:
            cpu: "200m"
            memory: 200Mi
      volumes:
      - name: config
        configMap:
          name: c2vba-parameter-tool-app
      - name: parameter-data
        persistentVolumeClaim:
          claimName: parameter-data
