---
apiVersion: v1
kind: Service
metadata:
  name: c2vba-parameter-tool-app
spec:
  ports:
  - name: actuator
    nodePort: 31660
    port: 80
    protocol: TCP
    targetPort: actuator
  selector:
    app: c2vba-parameter-tool-app
  type: NodePort
