---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    label.servicename: "c2vba-datex2-join-www_D"
    label.gitversion: "c2vba-datex2-join-www_D_0.1.7.1"
    app: c2vba-datex2-join-www
    log-type: spring-actuator
  name: c2vba-datex2-join-www
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: c2vba-datex2-join-www
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: c2vba-datex2-join-www
        log-type: spring-actuator
    spec:
      containers:
      - name: app
        image: heuboe/c2vba/datex2/c2vba-datex2-join:0.1.8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: actuator
          protocol: TCP
        envFrom:
        - secretRef:
            name: application-environment
        - secretRef:
            name: mdm-certs-environment
        - secretRef:
            name: mdm-urls-environment
        - secretRef:
            name: publication-version-environment
        env:
        - name: application.name
          value: "c2vba-datex2-join-www"
        - name: application.instance
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "info.kubernetes.node.name"
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: "info.kubernetes.pod.name"
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "info.kubernetes.pod.namespace"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "SPRING_PROFILES_ACTIVE"
          value: "default,${SYSTEM_NAME}-${SYSTEM_STAGE},${SYSTEM_STAGE},VMS"
        - name: "JAVA_TOOL_OPTIONS"
          value: "-XX:MaxRAMPercentage=75"
          # value: "-Xmx300M"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: mdm-certs
          mountPath: /mdm-certs
        - name: files
          mountPath: /files
        resources:
          limits:
            cpu: "300m"
            memory: 400Mi
          requests:
            cpu: "200m"
            memory: 400Mi
      volumes:
      - name: config
        configMap:
          name: c2vba-datex2-join-www
      - name: mdm-certs
        configMap:
          name: mdm-certs
      - name: files
        persistentVolumeClaim:
          claimName: join-www-files
