server.port=8080


# System type: PROD, INTEGRATION, TEST 
wls.system.systemType=PROD

wls.system.instanceType=VRZ

wls.system.instanceId=VRZ

wls.system.version=2.8



# Port of SOAP-Geo-Service
geo.service.port=4916
de.heuboe.geo.manager.geoServerUrl=/c2vba

# Port of SOAP-WebLocationService
wls.port=8085

# Port of SOAP-Hierachy-Service
hierarchy.port=8096






# HERE mapfile
de.heuboe.geo.manager.shapeDir=/map/_t_geom_by_SRC_HERE4DEBY_ZVM_S221R1_frc3__202207131321.csv


# Abbiegeverbote
wls.turnRestrictionFile=/map/roadmap_turnRestriction.csv

#wls.turnRestrictionFile=D:/Temp/nrw/komod-with-a4/roadmap/roadmap_turnRestriction.csv


# Umschreibendes Polygon des Verkehrsgebiets: LCL-Versorgung wird dagegen geclippt 
wls.borderPolygonFile=/map/borderPolygon.txt

# For these route numbers no roads are created
#de.heuboe.geo.manager.routeNumsIgnore=L137,L380



# --------------------------------------------------------
# Road
# --------------------------------------------------------

de.heuboe.geo.manager.addRouteNums=ST2584,ST2580,ST2082,B505,B471,B304,B2,B17,B15n,B22,ST2088,ST2007,B310,B2r,B13

de.heuboe.geo.manager.routeNumPattern=[A] *[0-9]+[A-Za-z]?

de.heuboe.geo.manager.maxRoadClass=ROAD_CLASS_3


# MQ- and UFD supply
q.sued.filename=/map/C2VBA-Q-Suedbayern-5-1.csv

#q.nord.filename=/map/C2VBA-Q-Nordbayern.csv
q.nord.filename=/map/C2VBA-Q-Nordbayern-2-add.csv


aq.location.file=/map/aq-location.csv

# --------------------------------------------------------
# TMC
# --------------------------------------------------------

# LCL version of initial supply
wls.tmcVersion=20.0

# LCL
wls.tmcFile=/map/LCL-20.0.csv

# LCL points are restricted to this polygon
wls.tmcMapBorderFile=/map/borderPolygon.txt

wls.tmcCoordinateFile=/map/LCL-coordinates.csv
#de.heuboe.e21x.basis.geo.svc.tmcCoordinateFile=/map/samples/LCL-coordinates-empty.csv

wls.tmcRouteNumPattern=[AB].*



# --------------------------------------------------------
# KM
# --------------------------------------------------------


# Kilometrierungsversorgung
wls.kmPointCsvFile=/map/roadKmPoints.csv

# Pannenstreifenversorgung
#wls.hardShoulderCsvFile=/map/roadHardShoulderSections.txt


# Kilometrierungsversorgung als Shapefile 
#wls.kmPointSupplyShapefile=C:/Users/peters/Desktop/KomodNext-UZ/Kilometrierung/BKM/BKM_point.shp

# Ausgabedatei der Kilometrierungsversorgung: 
#wls.kmPointCsvOutSupplyFile=/map/roadKmPointsSupplyOut-new.csv


wls.subordinateRoadOriginFile=/map/subordinateRoadOrigin.txt
wls.subordinateRoadOriginResultFile=/map/subordinateRoadOriginResult.txt 
wls.roadTmcPointFile=/map/roadTmcPoints.txt 
wls.tmcPointShortNameFile=/map/tmcPointShortNames.txt


# --------------------------------------------------------
# OpenLR
# --------------------------------------------------------


# OpenLR-Encoder/Decoder-Konfiguration
de.heuboe.geo.manager.openLrPluginEncoderCfgFile=/openLRConfig/openLR-encoder.xml
de.heuboe.geo.manager.openLrPluginDecoderCfgFile=/openLRConfig/openLR-decoder.xml



wls.supplyMode=true

wls.poolSize=10


# MongoDB connection
wls.mongodb.uri=mongodb://${MONGODB_AUTHORITY}/geo-manager-01?appName=geo-manager-c2vba&authSource=admin

# Die Größe eines MongoDB-Datensatzes (Dokument) ist beschränkt (16 MB). 
# Beim Speichern einer neuen Kartenversorgung werden Collections gleichartiger Datensätze (etwa RoadElement) 
# in Teil-Collections von höchstens <maxCollectionSize> Datensätzen gespeichert. 
wls.supply.db.maxCollectionSize=50

# SRID der internen kartesischen geographischen Koordinaten
wls.srid=32632
wls.tmcSrid=4326

# Map background tile source of SOAP-Geo-Server  
#geo.service.tileServerUrl=http://62.132.115.147:20080/mptms/1.0.0/austria/EPSG3857/


# --------------------------------------------------------
# Initial map supply
# --------------------------------------------------------

# Directory of initial map supply files
wls.map.supply.dir=/map



# GeoManager writes road network as shapefile on activation of a new map (and on start)
wls.shapefile.dir=/map/shapefiles


# Checks locations of MQs and AQs, emits log warnings
wls.infra.check.locations=true

# Checks locations of MQs and AQs, tries to relocate them
#wls.infra.improve.locations=true

#wls.infra.check.roads=true


wls.strategicNetType=STRATEGIC_NET_ROAD_CLASS_0_1


#--------------------------------------------------------
# Strategien
#--------------------------------------------------------

de.heuboe.geo.manager.strategyFile=/map/StrategieDefinition_v0.16.txt

de.heuboe.geo.manager.strategyRouteLocationsDir=/map/strategyRouteLocations


#--------------------------------------------------------
# Miscellaneous
#--------------------------------------------------------

# Maximal number of XML elements in a SOAP message (default value is much smaller)
org.apache.cxf.stax.maxChildElements=100000



   
##
## Kafka
##

## Connection
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP}

# Consumer ID
spring.kafka.consumer.group-id=GeoManager

# Default serialization types
spring.kafka.consumer.properties.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.producer.properties.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer



   
## --------------------------------------------------------------------------
## Properties of gRPC service
## --------------------------------------------------------------------------

grpc.server.port=9090
grpc.client.SimpleServer.maxInboundMessageSize=25000000




## --------------------------------------------------------------------------
## ConfigService
## --------------------------------------------------------------------------

grpc.client.ConfigService.address=dns:///config-service:9090
grpc.client.ConfigService.maxInboundMessageSize=30000000
grpc.client.ConfigService.negotiationType=PLAINTEXT




## --------------------------------------------------------------------------
## Actuator
## --------------------------------------------------------------------------
management.endpoints.web.exposure.include=health
management.endpoints.web.exposure.exclude=shutdown
management.endpoint.metrics.enabled=true
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true