---
apiVersion: v1
kind: Service
metadata:
  name: c2vba-datex2-mst-localisation
spec:
  ports:
  - name: actuator
    nodePort: 32373
    port: 80
    protocol: TCP
    targetPort: actuator
  - name: svc
    nodePort: 32374
    port: 5711
    protocol: TCP
    targetPort: svc
  selector:
    app: c2vba-datex2-mst-localisation
  type: NodePort
