# Spring: HTTP access to actuator data
server.port=8080

# SOAP service port
de.heuboe.by.c2vba.datex2.mst.localisation.servicePort=5711

# Url of WLS (provides location data of MeasurementSites (MQs and UFDs)
de.heuboe.by.c2vba.datex2.mst.localisation.wlsUrl=http://wls-project-sdbby.c2vba.svc:82/WebLocationServerSrv?wsdl


de.heuboe.by.c2vba.datex2.mst.localisation.addOpenLRLocation=true


# gRPC config service connection
grpc.client.ConfigService.address=dns:///config-service:9090
grpc.client.ConfigService.maxInboundMessageSize=30000000
grpc.client.ConfigService.negotiationType=PLAINTEXT


##
## Kafka
##

## Connection
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP}
#spring.kafka.bootstrap-servers=kafka1.d.uz.komodnext.heuboe.hbintern:9092

# Consumer group ID
spring.kafka.consumer.group-id=c2vba-datex2-mst-localisation

# Topics with MQ and UFD detector configuration data
de.heuboe.by.c2vba.datex2.mst.localisation.lveBetriebsparameterTopic=C2VBA-tlsin-LVEBetriebsparameter
de.heuboe.by.c2vba.datex2.mst.localisation.ufdBetriebsparameterTopic=C2VBA-tlsin-UFDBetriebsparameter


## --------------------------------------------------------------------------
## Actuator
## --------------------------------------------------------------------------
management.endpoints.web.exposure.include=health
management.endpoints.web.exposure.exclude=shutdown
management.endpoint.metrics.enabled=true
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true


