---
apiVersion: v1
kind: Service
metadata:
  name: tls-receiver
spec:
  ports:
  - name: actuator
    nodePort: 32633
    port: 80
    protocol: TCP
    targetPort: actuator
  selector:
    app: tls-receiver
  type: NodePort
