{
  "id" : "DE-10209.M",
  "name" : "DE-10209.M",
  "elements" : [ {
    "id" : "DE1268349880_1",
    "length" : 100.0161958850563,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268349881_1",
    "length" : 50.53383903294737,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1232537336_1",
    "length" : 146.9123039224503,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225197481_1",
    "length" : 38.80970562939659,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225197482_1",
    "length" : 69.05688254702805,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244180678_1",
    "length" : 68.24508653582531,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244180679_1",
    "length" : 37.52858613168497,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1256987649_1",
    "length" : 16.414061893319975,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1256987650_1",
    "length" : 15.12878187639939,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586900042_1",
    "length" : 132.36771957356194,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783176706_1",
    "length" : 16.41402417943154,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783176707_1",
    "length" : 452.32262698047475,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225251807_1",
    "length" : 57.567875443536984,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225251808_1",
    "length" : 111.49844752373028,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1182942176_1",
    "length" : 37.51742958639719,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1182942177_1",
    "length" : 64.60166530338613,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783091733_1",
    "length" : 90.39450532932011,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE52913974_1",
    "length" : 202.9457912122616,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085146397_1",
    "length" : 17.265606855426128,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085146398_1",
    "length" : 141.74874593728578,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920987539_1",
    "length" : 326.40728187639314,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE722728701_1",
    "length" : 149.01427534785734,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE722728702_1",
    "length" : 25.79286408668386,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783091734_1",
    "length" : 107.86096726825808,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244200778_1",
    "length" : 127.9096983789559,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244200779_1",
    "length" : 57.5662199728533,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244200776_1",
    "length" : 38.573108233186296,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244200777_1",
    "length" : 799.9419987476324,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920987540_1",
    "length" : 334.62718403737415,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085146395_1",
    "length" : 60.09490243783546,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1282943672_1",
    "length" : 92.59967867657,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1282943673_1",
    "length" : 52.602354274855905,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE52819363_1",
    "length" : 193.4346889038892,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085151072_1",
    "length" : 22.839963389268135,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085151073_1",
    "length" : 85.29309695597121,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920987542_1",
    "length" : 47.848281604767486,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085151074_1",
    "length" : 26.257499474814143,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085151075_1",
    "length" : 151.7984933719477,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586900015_1",
    "length" : 208.48129759208754,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586900014_1",
    "length" : 341.7795589897555,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920963271_1",
    "length" : 194.05398793397995,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920963272_1",
    "length" : 150.37910946834504,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE52836344_1",
    "length" : 387.6099085754649,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289720612_1",
    "length" : 25.011924824505922,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289720613_1",
    "length" : 165.29882898720945,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920963274_1",
    "length" : 272.63719042362436,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562821923_1",
    "length" : 1498.862424020422,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586893466_1",
    "length" : 128.8807663279349,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225300766_1",
    "length" : 48.948076097553695,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225300767_1",
    "length" : 62.23306012801981,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783165139_1",
    "length" : 119.51260160426759,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  } ],
  "direction" : "POSITIVE",
  "firstOffset" : 85.0,
  "lastOffset" : 31.999999999999996,
  "length" : 7998.928571786936
}