{
  "id" : "DE-10046.M",
  "name" : "DE-10046.M",
  "elements" : [ {
    "id" : "DE1126526116_2",
    "length" : 84.87376118729904,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1126526115_2",
    "length" : 530.3440259706827,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285712765_2",
    "length" : 74.89092856038981,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285712767_2",
    "length" : 21.099964530949507,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285712766_2",
    "length" : 922.7618447234178,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE774028741_2",
    "length" : 269.26647569152897,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819426333_2",
    "length" : 114.66064328961497,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819426332_2",
    "length" : 203.25145525887774,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285712769_2",
    "length" : 23.11923272973995,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285712768_2",
    "length" : 65.46738194805909,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268205516_2",
    "length" : 42.35321048717581,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268189719_2",
    "length" : 121.50766578770752,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819426230_2",
    "length" : 40.50277902194319,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819426229_2",
    "length" : 297.9435334844157,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819426063_2",
    "length" : 104.68142419695832,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819426062_2",
    "length" : 122.80451242388101,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285716066_2",
    "length" : 42.355333122049316,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285716068_2",
    "length" : 24.96772683241212,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285716067_2",
    "length" : 24.239105866868744,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783168803_2",
    "length" : 58.62791392275609,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819424708_2",
    "length" : 193.6849680179613,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225197715_2",
    "length" : 62.06860285085844,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225197714_2",
    "length" : 24.513501328408548,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819425163_2",
    "length" : 165.34758059326788,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236110386_2",
    "length" : 261.31230139604395,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236110388_2",
    "length" : 170.15537927587138,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236110387_2",
    "length" : 101.59287562720527,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236207830_2",
    "length" : 243.22452470093293,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236207829_2",
    "length" : 32.77935032012847,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236207834_2",
    "length" : 32.87353239061803,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236207833_2",
    "length" : 83.51316181703064,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236222222_2",
    "length" : 133.34295293801247,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236222221_2",
    "length" : 29.072804955913174,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236222218_2",
    "length" : 35.83839823533879,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236222217_2",
    "length" : 422.93914133888234,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819422608_2",
    "length" : 1243.6701703644985,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE64429426_2",
    "length" : 108.1446900950333,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1239800815_2",
    "length" : 194.7175432442152,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1239800816_2",
    "length" : 41.758351996447345,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1239800818_2",
    "length" : 25.369935168331565,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1239800817_2",
    "length" : 36.57427565169338,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1239800820_2",
    "length" : 29.074001641435746,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1239800819_2",
    "length" : 349.8094987370139,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783166468_2",
    "length" : 142.99755840106877,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783166467_2",
    "length" : 80.34692882346945,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554348447_1",
    "length" : 459.9387652142506,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1296590142_1",
    "length" : 30.247753416298078,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1296590143_1",
    "length" : 34.107799144111645,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819421962_1",
    "length" : 104.26876817895334,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1226728096_1",
    "length" : 37.195006322005824,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1226728097_1",
    "length" : 49.82132952578101,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819419447_1",
    "length" : 33.46726679798211,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1273202658_1",
    "length" : 70.65277807475172,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1273202659_1",
    "length" : 58.03066755717697,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819417882_1",
    "length" : 28.333047853514188,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1087967383_1",
    "length" : 35.834601879225794,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1087967384_1",
    "length" : 105.41995181703042,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1104721720_1",
    "length" : 35.56665624903555,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1104721721_1",
    "length" : 142.81595214126114,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243535034_1",
    "length" : 92.89477062420227,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE769313388_1",
    "length" : 157.82412623698124,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE769313389_1",
    "length" : 187.76223233782974,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE769313390_1",
    "length" : 52.78463038500516,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562763528_1",
    "length" : 362.5987822096865,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554340528_1",
    "length" : 105.5141901975035,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819416800_1",
    "length" : 91.84115779660301,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819416801_1",
    "length" : 82.71865128887718,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819416611_1",
    "length" : 266.0989378756489,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819416612_1",
    "length" : 153.11047392210864,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921185697_2",
    "length" : 89.20167409178107,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1194518219_2",
    "length" : 38.6642594165843,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1194518218_2",
    "length" : 156.74329180153654,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783181644_2",
    "length" : 57.92219951276027,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783181643_2",
    "length" : 125.36847032664696,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562822201_2",
    "length" : 49.12301302610829,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285716063_2",
    "length" : 35.56754224537687,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285716062_2",
    "length" : 148.80633855905242,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225299843_2",
    "length" : 26.78002016111391,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE67622064_1",
    "length" : 82.51902207763115,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1232487682_1",
    "length" : 81.83688701353083,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1296674721_1",
    "length" : 128.2309181880848,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE854235839_1",
    "length" : 24.425072954589737,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562822185_1",
    "length" : 35.78921814269368,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783181654_1",
    "length" : 53.92925779142867,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1232487680_1",
    "length" : 114.65761266297342,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1232487681_1",
    "length" : 44.76421153218273,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921185701_1",
    "length" : 48.30906469329764,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243330417_1",
    "length" : 1031.9631975669913,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243330418_1",
    "length" : 584.9091311958648,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236103361_1",
    "length" : 75.41068837695397,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236103362_1",
    "length" : 33.375643052755805,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236103363_1",
    "length" : 188.05700093466953,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236104536_1",
    "length" : 528.8798217300874,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236104537_1",
    "length" : 44.141689082959175,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236104538_1",
    "length" : 342.2795484178483,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921185703_1",
    "length" : 37.35956126434159,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1232487684_1",
    "length" : 20.4497212506378,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1232487685_1",
    "length" : 33.481676241146275,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921185702_1",
    "length" : 108.88541755371307,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819410340_1",
    "length" : 214.7390069757463,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783184487_1",
    "length" : 112.27052834437475,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE52908818_1",
    "length" : 114.0369781052681,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243333077_1",
    "length" : 58.01514971928959,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243333076_2",
    "length" : 111.09782924078029,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1223766293_2",
    "length" : 38.483914105582805,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562818728_1",
    "length" : 398.4226792723834,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562818727_1",
    "length" : 454.50099968967226,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554332108_1",
    "length" : 42.42506526117696,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562819024_1",
    "length" : 97.92399300322373,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1254489891_1",
    "length" : 108.964146012696,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1254489892_1",
    "length" : 73.05270607516499,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783184495_1",
    "length" : 140.43268101149098,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244147353_1",
    "length" : 106.18371945967806,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244147354_1",
    "length" : 45.4607997532685,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172804231_1",
    "length" : 26.2029041663383,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172804233_1",
    "length" : 23.88640959803149,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244147358_1",
    "length" : 114.18376528301246,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244147359_1",
    "length" : 61.71124532613067,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172805821_1",
    "length" : 35.5176904089818,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172805819_1",
    "length" : 89.24108914381182,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921114732_1",
    "length" : 237.51355927592482,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268360875_1",
    "length" : 210.5275860736588,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1296919227_1",
    "length" : 631.5179491721967,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1272298966_1",
    "length" : 27.18945349967763,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244151144_1",
    "length" : 41.80908440683743,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244151146_1",
    "length" : 351.569223565745,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244151147_1",
    "length" : 106.79586587933792,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819398642_1",
    "length" : 52.272394227473754,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819398643_1",
    "length" : 149.0769514290646,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562821813_1",
    "length" : 207.56716069403782,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921114733_1",
    "length" : 134.8488302445506,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921114734_1",
    "length" : 98.37440354922725,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562818735_1",
    "length" : 840.6016129896096,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  } ],
  "direction" : "POSITIVE",
  "firstOffset" : 52.00000000000001,
  "lastOffset" : 740.0,
  "length" : 19988.936178831416
}