{
  "id" : "DE-10201.M",
  "name" : "DE-10201.M",
  "elements" : [ {
    "id" : "DE770438838_2",
    "length" : 123.71346998733611,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920963266_2",
    "length" : 52.597690236704764,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172530961_2",
    "length" : 134.12632314374065,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172530960_2",
    "length" : 37.53166682701108,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172530959_2",
    "length" : 21.616767881582454,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172530958_2",
    "length" : 394.69576701142887,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586918817_2",
    "length" : 217.68962585057875,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783165143_2",
    "length" : 53.90242978567913,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE792404811_2",
    "length" : 112.99148636274228,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE792404810_2",
    "length" : 72.90375521836158,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE52819377_2",
    "length" : 185.39483222300152,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562821927_2",
    "length" : 50.2592833895453,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783165137_2",
    "length" : 88.53192934592406,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920963264_2",
    "length" : 80.20076465267744,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920963263_2",
    "length" : 85.65235507349797,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586918736_2",
    "length" : 190.0755560704288,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562821915_2",
    "length" : 904.3386667791133,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920963268_2",
    "length" : 748.34504291647,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920963267_2",
    "length" : 186.88829283355602,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586918740_2",
    "length" : 262.24424329677265,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586918739_2",
    "length" : 148.04693266572255,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289720615_2",
    "length" : 26.099388005699293,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289720614_2",
    "length" : 128.7881399295029,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920963269_2",
    "length" : 167.63264233079357,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586899977_2",
    "length" : 262.0843082008861,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085151077_2",
    "length" : 89.02620915964343,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085151076_2",
    "length" : 201.05871854565433,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE52819367_2",
    "length" : 226.81943793006874,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085140672_2",
    "length" : 24.096348665246047,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085140671_2",
    "length" : 79.69477182367707,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920987545_2",
    "length" : 46.60407084774454,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085140674_2",
    "length" : 26.099601649502958,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085140673_2",
    "length" : 119.46553471512374,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554329925_2",
    "length" : 287.6337778518552,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE774036239_2",
    "length" : 600.0204840700684,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE774036238_2",
    "length" : 337.88818374233523,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920987547_2",
    "length" : 99.77190816168144,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085146391_2",
    "length" : 23.447942324389523,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1181838295_2",
    "length" : 22.395942572493208,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1181838294_2",
    "length" : 56.51474450288122,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1181400492_2",
    "length" : 130.01927130370694,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783091736_2",
    "length" : 109.97275005590372,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE52913978_2",
    "length" : 163.08215269257036,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920987549_2",
    "length" : 191.22029934596648,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920987548_2",
    "length" : 96.61840921742125,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586899978_2",
    "length" : 76.57239852763965,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586899979_2",
    "length" : 134.71111651259395,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE67617551_2",
    "length" : 199.31054711529453,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783091731_2",
    "length" : 85.70485343662067,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1282616693_2",
    "length" : 65.6554390299713,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1282616692_2",
    "length" : 172.70456141676718,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1282616695_2",
    "length" : 308.2326307817618,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1282616694_2",
    "length" : 106.80920350048876,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783176709_2",
    "length" : 74.80341086440247,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225251810_2",
    "length" : 76.32649548855653,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225251809_2",
    "length" : 79.27467132967121,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1256747694_2",
    "length" : 202.60870173660163,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1256747693_2",
    "length" : 228.06765791428793,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554330108_2",
    "length" : 100.62803339224942,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243926825_2",
    "length" : 189.60356126430162,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1235941458_2",
    "length" : 73.54715912983367,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1256978607_2",
    "length" : 445.76524343285774,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1256978606_2",
    "length" : 109.10375296174125,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1235641858_2",
    "length" : 24.997194291108872,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1256747636_2",
    "length" : 26.302848497070535,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1256747635_2",
    "length" : 55.22312565652031,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1235641812_2",
    "length" : 30.236534235686843,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1235642364_2",
    "length" : 65.44356943457177,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1235941286_2",
    "length" : 98.41390059003557,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1235941285_2",
    "length" : 58.44388298597529,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1235641626_2",
    "length" : 39.63682843937153,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1256978609_2",
    "length" : 86.91181808138946,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1256978608_2",
    "length" : 49.97121571390474,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243322550_2",
    "length" : 25.52676864469152,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243553147_2",
    "length" : 76.11886672500714,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE722733443_2",
    "length" : 147.84236381902448,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281265657_2",
    "length" : 60.66901523026246,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281265656_2",
    "length" : 74.01359092402419,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268334771_2",
    "length" : 37.55786942316207,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1267346523_2",
    "length" : 32.80496854057457,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297387040_2",
    "length" : 210.80301814185088,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297387042_2",
    "length" : 21.850307825929306,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297387041_2",
    "length" : 26.112762601671278,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1282998382_2",
    "length" : 29.656381155031927,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1282998381_2",
    "length" : 94.23014997744619,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1266938738_2",
    "length" : 111.29248495703827,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1266938737_2",
    "length" : 71.39178591178975,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1256995643_2",
    "length" : 69.04329054318502,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1256995642_2",
    "length" : 30.183341558312872,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  } ],
  "direction" : "POSITIVE",
  "firstOffset" : 55.0,
  "lastOffset" : 1.0,
  "length" : 11967.725899378656
}