syntax = "proto3";

package eu.vmis_ehe.vmis2.tls.send;

import "google/protobuf/timestamp.proto";
import "heuboe/protobuf/Documentation.proto";
import "heuboe/protobuf/InterfaceVersion.proto";

option java_multiple_files = true;
option (.heuboe.protobuf.interface_version) = "3.0.0";

message LVEAbrufPufferInhalt { // Fg 1 | Id 2 | deTyp 20
    option (.heuboe.protobuf.stereotype) = ENTITY;
    string id = 1;
    sint32 jobnummer = 2;
    google.protobuf.Timestamp tls_time = 3; // Zeit die via TLS-Zeitstempel (DE-Nummer 255) mitgesendet wurde
    google.protobuf.Timestamp process_time = 4; // Zeit, zu der die Daten im tls-receiver erstellt wurden.
    sint32 jahr = 11;
    sint32 monat = 12;
    sint32 tag = 13;
    sint32 stunde = 14;
    sint32 anzahl_stunden = 15;
}

message LVEAbrufPufferInhaltList { // Liste von LVEAbrufPufferInhalt
    option (.heuboe.protobuf.stereotype) = CONTAINER;
    string iid = 1;
    repeated LVEAbrufPufferInhalt elements = 2;
}

message AXLAbrufPufferInhalt { // Fg 2 | Id 2 | deTyp 20
    option (.heuboe.protobuf.stereotype) = ENTITY;
    string id = 1;
    sint32 jobnummer = 2;
    google.protobuf.Timestamp tls_time = 3; // Zeit die via TLS-Zeitstempel (DE-Nummer 255) mitgesendet wurde
    google.protobuf.Timestamp process_time = 4; // Zeit, zu der die Daten im tls-receiver erstellt wurden.
    google.protobuf.Timestamp zeitstempel = 11;
    sint32 anzahl_datensaetze = 12;
}

message AXLAbrufPufferInhaltList { // Liste von AXLAbrufPufferInhalt
    option (.heuboe.protobuf.stereotype) = CONTAINER;
    string iid = 1;
    repeated AXLAbrufPufferInhalt elements = 2;
}

message AXLAbrufPufferinhaltErgebnismeldung { // Fg 2 | Id 2 | deTyp 21
    option (.heuboe.protobuf.stereotype) = ENTITY;
    string id = 1;
    sint32 jobnummer = 2;
    google.protobuf.Timestamp tls_time = 3; // Zeit die via TLS-Zeitstempel (DE-Nummer 255) mitgesendet wurde
    google.protobuf.Timestamp process_time = 4; // Zeit, zu der die Daten im tls-receiver erstellt wurden.
    google.protobuf.Timestamp zeitstempel = 11;
    sint32 hundertstelsekunden = 12;
    sint32 anzahl_datensaetze = 13;
}

message AXLAbrufPufferinhaltErgebnismeldungList { // Liste von AXLAbrufPufferinhaltErgebnismeldung
    option (.heuboe.protobuf.stereotype) = CONTAINER;
    string iid = 1;
    repeated AXLAbrufPufferinhaltErgebnismeldung elements = 2;
}

message WZGAbrufPufferInhalt { // Fg 4 | Id 2 | deTyp 20
    option (.heuboe.protobuf.stereotype) = ENTITY;
    string id = 1;
    sint32 jobnummer = 2;
    google.protobuf.Timestamp tls_time = 3; // Zeit die via TLS-Zeitstempel (DE-Nummer 255) mitgesendet wurde
    google.protobuf.Timestamp process_time = 4; // Zeit, zu der die Daten im tls-receiver erstellt wurden.
    sint32 folgenummer = 11;
    sint32 anzahl_nachrichten = 12;
}

message WZGAbrufPufferInhaltList { // Liste von WZGAbrufPufferInhalt
    option (.heuboe.protobuf.stereotype) = CONTAINER;
    string iid = 1;
    repeated WZGAbrufPufferInhalt elements = 2;
}

message WZGAbrufCodedefinition { // Fg 4 | Id 3 | deTyp 21
    option (.heuboe.protobuf.stereotype) = ENTITY;
    string id = 1;
    sint32 jobnummer = 2;
    google.protobuf.Timestamp tls_time = 3; // Zeit die via TLS-Zeitstempel (DE-Nummer 255) mitgesendet wurde
    google.protobuf.Timestamp process_time = 4; // Zeit, zu der die Daten im tls-receiver erstellt wurden.
    sint32 stellcode = 11;
}

message WZGAbrufCodedefinitionList { // Liste von WZGAbrufCodedefinition
    option (.heuboe.protobuf.stereotype) = CONTAINER;
    string iid = 1;
    repeated WZGAbrufCodedefinition elements = 2;
}

message WZGAbrufBilddefinition { // Fg 4 | Id 3 | deTyp 22
    option (.heuboe.protobuf.stereotype) = ENTITY;
    string id = 1;
    sint32 jobnummer = 2;
    google.protobuf.Timestamp tls_time = 3; // Zeit die via TLS-Zeitstempel (DE-Nummer 255) mitgesendet wurde
    google.protobuf.Timestamp process_time = 4; // Zeit, zu der die Daten im tls-receiver erstellt wurden.
    sint32 stellcode = 11;
}

message WZGAbrufBilddefinitionList { // Liste von WZGAbrufBilddefinition
    option (.heuboe.protobuf.stereotype) = CONTAINER;
    string iid = 1;
    repeated WZGAbrufBilddefinition elements = 2;
}

message ZRAAbrufPufferInhalt { // Fg 9 | Id 2 | deTyp 20
    option (.heuboe.protobuf.stereotype) = ENTITY;
    string id = 1;
    sint32 jobnummer = 2;
    google.protobuf.Timestamp tls_time = 3; // Zeit die via TLS-Zeitstempel (DE-Nummer 255) mitgesendet wurde
    google.protobuf.Timestamp process_time = 4; // Zeit, zu der die Daten im tls-receiver erstellt wurden.
    sint32 folgenummer = 11;
    sint32 anzahl_nachrichten = 12;
}

message ZRAAbrufPufferInhaltList { // Liste von ZRAAbrufPufferInhalt
    option (.heuboe.protobuf.stereotype) = CONTAINER;
    string iid = 1;
    repeated ZRAAbrufPufferInhalt elements = 2;
}

message SYSReset { // Fg 254 | Id 2 | deTyp 38
    option (.heuboe.protobuf.stereotype) = ENTITY;
    string id = 1;
    sint32 jobnummer = 2;
    google.protobuf.Timestamp tls_time = 3; // Zeit die via TLS-Zeitstempel (DE-Nummer 255) mitgesendet wurde
    google.protobuf.Timestamp process_time = 4; // Zeit, zu der die Daten im tls-receiver erstellt wurden.
    sint32 grund = 11;
}

message SYSResetList { // Liste von SYSReset
    option (.heuboe.protobuf.stereotype) = CONTAINER;
    string iid = 1;
    repeated SYSReset elements = 2;
}

message SYSDateiAbruf { // Fg 254 | Id 3 | deTyp 40
    option (.heuboe.protobuf.stereotype) = ENTITY;
    string id = 1;
    sint32 jobnummer = 2;
    google.protobuf.Timestamp tls_time = 3; // Zeit die via TLS-Zeitstempel (DE-Nummer 255) mitgesendet wurde
    google.protobuf.Timestamp process_time = 4; // Zeit, zu der die Daten im tls-receiver erstellt wurden.
    string bezeichner = 11;
}

message SYSDateiAbrufList { // Liste von SYSDateiAbruf
    option (.heuboe.protobuf.stereotype) = CONTAINER;
    string iid = 1;
    repeated SYSDateiAbruf elements = 2;
}
