# Spring: HTTP access to actuator data
server.port=8080

# WLS web service settings
wls.protocol=http
wls.port:8085

# MongoDB database connection
wls.mongodb.uri=mongodb://${MONGODB_AUTHORITY}/wls-03?appName=wls-project-sdbby&authSource=admin

# WLS system version
wls.system.version=4.8

# Road net supply as Intrest shapefile
map.pathname=/map-wls/_t_geom_by_SRC_HERE4DEBY_ZVM_S221R1_frc3__202207131321.csv
map.srid=32632

# TLS configuration files: provide AQs with coordinates
vms.filename=/map-wls/KonfTab_Fischbach.txt;/map-wls/KonfTab_Freimann.txt

# Locations of SDBBY AQs
aq.location.file=/map-wls/aq-location.csv

# WWW chains
www.filename=/map-wls/www_v1.0.txt

# Strategy route definitions
sdb.filename=/map-wls/StrategieDefinition_v0.16.txt

# Strategy route locations
sdb.route.fileDir=/map-wls/strategyRouteLocations

# OpenLR settings
openLR.encoder.config=/map-wls/openLR-encoder.xml
openLR.decoder.config=/map-wls/openLR-decoder.xml

# LCL data
tmc.filename=map-wls/LCL-20.0.csv
tmc.version=D01:20.0

# MQ- and UFD coordinate supply (south)
q.sued.filename=/map-wls/C2VBA-Q-Suedbayern-5-1.csv

# MQ- and UFD coordinate supply (north)
q.nord.filename=/map-wls/C2VBA-Q-Nordbayern-2-add.csv

cfg.check.kri2UzFile=map-wls/wancomKeyFiles/kri2uz.csv
cfg.check.wancomKeyFileDir=map-wls/wancomKeyFiles

# WLS map SRID
wls.srid=32632

# Number of threads executing location conversions 
wls.poolSize=10


# gRPC config service connection
grpc.client.ConfigService.address=dns:///config-service:9090
grpc.client.ConfigService.maxInboundMessageSize=30000000
grpc.client.ConfigService.negotiationType=PLAINTEXT



## --------------------------------------------------------------------------
## Actuator
## --------------------------------------------------------------------------
management.endpoints.web.exposure.include=health
management.endpoints.web.exposure.exclude=shutdown
management.endpoint.metrics.enabled=true
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
