<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>receiver-app</artifactId>
	<version>0.0.2</version>

	<parent>
		<groupId>de.heuboe.tls</groupId>
		<artifactId>tls-parent-pom</artifactId>
		<version>0.1.1</version>
	</parent>

	<dependencies>
		<dependency>
			<groupId>de.heuboe.tls</groupId>
			<artifactId>receiver-rmq</artifactId>
			<version>0.0.1</version>
		</dependency>
	</dependencies>
</project>