---
apiVersion: v1
kind: Service
metadata:
  name: tls-tele-recorder
spec:
  ports:
  - name: actuator
    nodePort: 32630
    port: 80
    protocol: TCP
    targetPort: actuator
  selector:
    app: tls-tele-recorder
  type: NodePort
