de.heuboe.nrw.config.svc.model.type=CHB

#de.heuboe.nrw.sitecfg.svc.dstSystem=KOMOD
#de.heuboe.nrw.config.svc.soap.url=none
#de.heuboe.nrw.sitecfg.svc.scs.url=none

grpc.client.CfgServiceNrw.address=config-service:9090
#grpc.client.CfgServiceNrw.address=static://HANNAHN-WX.heuboe.hbintern:9090
#
grpc.client.GeoManagerNrw.address=geo-manager:9090
grpc.client.FeatureSvcNrw.address=geo-manager:9090
#grpc.client.GeoManagerNrw.address=static://peters-2k12v.heuboe.hbintern:9891
#grpc.client.FeatureSvcNrw.address=static://peters-2k12v.heuboe.hbintern:9891
#
de.heuboe.nrw.sitecfg.svc.rep.root=/site-data/unzipped
de.heuboe.nrw.sitecfg.svc.rep.sites=/site-data
de.heuboe.nrw.sitecfg.svc.rep.creation.mode=file


spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP}
spring.kafka.client-id=site-config-service
spring.kafka.consumer.group-id=site-config-service
spring.kafka.consumer.properties.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.producer.properties.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
spring.kafka.consumer.autoOffsetReset=earliest
spring.kafka.topics.DataChange=C2VBA-DataChange

