server.port=0

spring.data.mongodb.uri=mongodb://adminuser:password123@172.31.246.1:32000/datex2MST-ps?appName=datex2MSTLocServiceBuilder&authSource=admin

de.heuboe.datex2.mst.pubFilePath=D:/c2vba/MST
de.heuboe.datex2.mst.mstId=LVE
de.heuboe.datex2.mst.mstName=
de.heuboe.datex2.mst.mstVersion=111
de.heuboe.datex2.mst.defVersion=1
de.heuboe.datex2.mst.d2Version=2.3_MDM

de.heuboe.datex2.mst.natId=DE-MDM-Bayerische Straßenbauverwaltung - Zentralstelle für Verkehrsmanagement

de.heuboe.datex2.mst.schemaPath=D:/c2vba/d2Schema

de.heuboe.datex2.mst.loc.locServiceUrl=http://localhost:5711/BY/Datex2LocalisationService
  