---
apiVersion: v1
kind: Service
metadata:
  name: geo-manager-c2vba
spec:
  ports:
#  - name: jmx
#    nodePort: 31305
#    port: 31305
#    protocol: TCP
#    targetPort: jmx
  - name: actuator
    nodePort: 31300
    port: 80
    protocol: TCP
    targetPort: actuator
  - name: grpclb
    nodePort: 31301
    port: 9090
    protocol: TCP
    targetPort: grpc
  - name: grpc-ssl
    nodePort: 31314
    port: 9443
    protocol: TCP
    targetPort: grpc-ssl
  - name: wls
    nodePort: 31302
    port: 82
    protocol: TCP
    targetPort: wls
  - name: hierarchy
    nodePort: 31303
    port: 83
    protocol: TCP
    targetPort: hierarchy
  - name: geo
    nodePort: 31304
    port: 84
    protocol: TCP
    targetPort: geo
  selector:
    app: geo-manager-c2vba
  type: NodePort
