# Spring: HTTP access to actuator data
server.port=8080

# MongoDB database connection
spring.data.mongodb.uri=mongodb://${MONGODB_AUTHORITY}/strategy?appName=strategie-matching&authSource=admin



##
## Kafka
##

## Connection
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP}

# Consumer group ID
spring.kafka.consumer.group-id=strategie-matching

# Default serialization types
spring.kafka.consumer.properties.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.producer.properties.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer


de.heuboe.sdbby.service.wzgBetriebsartTopic = C2VBA-tlsin-WZGBetriebsart
de.heuboe.sdbby.service.wzgStellzustandTopic = C2VBA-tlsin-WZGStellzustand
de.heuboe.sdbby.service.wzgKanalSteuerungTopic = C2VBA-tlsin-WZGKanalsteuerung
de.heuboe.sdbby.service.wzgDeFehlerTopic = C2VBA-tlsin-WZGDeFehler

de.heuboe.sdbby.service.strategyStateTopic = C2VBA-StrategyStates


# WLS address
#de.heuboe.sdbby.service.wlsHost=wls-project-sdbby.c2vba.svc
#de.heuboe.sdbby.service.wlsPort=82

# Strategy rule file
de.heuboe.sdbby.service.rulesFile=/files/rules/StrategieRegeln_v0.20.txt


# Number of preceding font characters of a WWW text
de.heuboe.sdbby.service.precedingFontChars=1

# gRPC config service connection
grpc.client.ConfigService.address=dns:///config-service:9090
grpc.client.ConfigService.maxInboundMessageSize=30000000
grpc.client.ConfigService.negotiationType=PLAINTEXT

# gRPC GeoManager connection
grpc.client.GeoManager.address=dns:///geo-manager-c2vba:9090
grpc.client.GeoManager.maxInboundMessageSize=30000000
grpc.client.GeoManager.negotiationType=PLAINTEXT


## --------------------------------------------------------------------------
## Actuator
## --------------------------------------------------------------------------
management.endpoints.web.exposure.include=health
management.endpoints.web.exposure.exclude=shutdown
management.endpoint.metrics.enabled=true
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
