---
apiVersion: v1
kind: Service
metadata:
  name: mdp-builder-fg3
spec:
  ports:
  - name: actuator
    nodePort: 31111
    port: 80
    protocol: TCP
    targetPort: actuator
  selector:
    app: mdp-builder-fg3
  type: NodePort
