de.heuboe.sdbby.srp.publicationMode=OnUpdateCyclicSnapshot
de.heuboe.sdbby.srp.routeEncoding=openLR
de.heuboe.sdbby.srp.pubInterval=60
de.heuboe.sdbby.srp.checkInterval=10000
de.heuboe.sdbby.srp.fileDir=F:/sdbby/srp

#de.heuboe.sdbby.srp.wlsUrl=http://sdbby-2k19:8085/WebLocationServerSrv
de.heuboe.sdbby.srp.wlsUrl=http://localhost:8087/WebLocationServerSrv

#de.heuboe.sdbby.srp.sdbbyUrl=http://sdbby-2k19:8123/SdbbyService
de.heuboe.sdbby.srp.sdbbyUrl=http://localhost:8123/SdbbyService

de.heuboe.sdbby.srp.datex2Target=peter
de.heuboe.sdbby.srp.d2ReceiverURL=http://sdbby-2k19:5717/D2PushReceiver
de.heuboe.sdbby.srp.d2SchemaLocation=http://62.132.115.147:11447/d2Schema/StrategicRouting.xsd
de.heuboe.sdbby.srp.routeEncoding=openLR

##
## Kafka
##

## Connection
spring.kafka.bootstrap-servers=master1.d.c2vba.heuboe.hbintern:32002

# Consumer ID
spring.kafka.consumer.group-id=strategic-routing-publication-ps-test

# Default serialization types
spring.kafka.consumer.properties.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.producer.properties.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer



de.heuboe.sdbby.srp.strategyStatesTopic = C2VBA-StrategyStates

