de.heuboe.sdbby.srp.publicationMode=OnUpdateCyclicSnapshot
de.heuboe.sdbby.srp.pubInterval=60
de.heuboe.sdbby.srp.checkInterval=10000
de.heuboe.sdbby.srp.fileDir=F:/sdbby/srp
de.heuboe.sdbby.srp.wlsUrl=http://sdbby-2k19:8085/WebLocationServerSrv
de.heuboe.sdbby.srp.sdbbyUrl=http://sdbby-2k19:8123/SdbbyService
de.heuboe.sdbby.srp.datex2Target=peter
#de.heuboe.sdbby.srp.d2ReceiverURL=http://sdbby-2k19:5717/D2PushReceiver
de.heuboe.sdbby.srp.d2SchemaLocation=http://62.132.115.147:11447/d2Schema/StrategicRouting.xsd
de.heuboe.sdbby.srp.mdmAuthenticationFile=D:/by/etc/mdm/srp/mdmAuth.properties