## +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
##
## c2vba/tls-ifacewancom-by-sued
##
## +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-

# The Kafka servers to connect to, comma seperated list
## --------------------------------------------------------------------------
## Spring Actuator
## --------------------------------------------------------------------------
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoints.web.exposure.exclude=shutdown
management.endpoint.metrics.enabled=true
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

# The name of the consumer group for kafka.
# This is important because the progress/current index is saved using this name.
# Different applications that listen to kafka HAVE to use different group ids.
spring.kafka.consumer.group-id=tls_ifacewancom_sued
spring.kafka.listener.missing-topics-fatal=true

## --------------------------------------------------------------------------
## Spring Kafka
## --------------------------------------------------------------------------

# Spring-Converter
# has to be this way for our use of kafka
spring.kafka.consumer.properties.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.producer.properties.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP}

# GRPC ConfigService
grpc.client.CfgSvc.address=static://config-service.c2vba:9090
grpc.client.CfgSvc.negotiationType=PLAINTEXT

de.heuboe.tls.ifacewancom.config.uzId=${CENTRE_ID}
de.heuboe.tls.ifacewancom.config.rcvTopic=${SYSTEM_PREFIX}-tlsin-TeleReceived
de.heuboe.tls.ifacewancom.config.sndTopic=VRZ-tlsout-TeleToSend
de.heuboe.tls.ifacewancom.config.commStateTopic=${SYSTEM_PREFIX}-tlsin-TLSCommState

de.heuboe.tls.ifacewancom.config.ifaceKey=1203
de.heuboe.tls.ifacewancom.config.specialDevRoot=aggregatorParent, aggregatorParentId, aggregatorParentCable, 1203, 203, 1

de.heuboe.tls.ifacewancom.config.minJobNr=1
de.heuboe.tls.ifacewancom.config.maxJobNr=255

# timezone where tls timestamps operate in
# Europe/Berlin MEZ with daylight saving time
# GMT+01:00 MEZ but always wintertime !needs to be exact!
# UTC ...
de.heuboe.tls.ifacewancom.config.timezone4Sync=Europe/Berlin
de.heuboe.tls.ifacewancom.config.useDstBit=true

# config file for connection to other system
de.heuboe.tls.ifacewancom.config.configFileWANCom=/config-data/iface/by-sued-wancom.cfg

de.heuboe.tls.ifacewancom.config.chg.changetopic=VRZ-DataChange
de.heuboe.tls.ifacewancom.config.chg.changetopicgroupid=tlsIfaceWancomChangeDetector_sued
