<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>receiver-rmq</artifactId>
	<version>0.0.2</version>

	<parent>
		<groupId>de.heuboe.tls</groupId>
		<artifactId>tls-parent-pom</artifactId>
		<version>0.1.1-SNAPSHOT</version>
	</parent>

	<dependencies>
		<dependency>
			<groupId>de.heuboe.tls</groupId>
			<artifactId>receiver-core</artifactId>
			<version>0.0.2</version>
		</dependency>
		
		<dependency>
			<groupId>de.heuboe.tls</groupId>
			<artifactId>tls-tele</artifactId>
		</dependency>
		
		<dependency>
			<groupId>de.heuboe.tls</groupId>
			<artifactId>iface-syscon-rmq-iface</artifactId>
			<version>0.1.0</version>
		</dependency>
		
		<!--  logging -->
		<dependency>
			<groupId>de.heuboe.base</groupId>
			<artifactId>jhbBase</artifactId>
			<version>2.15.0</version>
		</dependency>

		<!--  RabbitMQ -->
		<dependency>
			<groupId>com.rabbitmq</groupId>
			<artifactId>amqp-client</artifactId>
			<version>3.4.3</version>
		</dependency>
		
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
		</dependency>
	</dependencies>
</project>
