---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: region-receiver-fg1-fg3-files
  annotations:
    storageClass: default_by_build.sh
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 30Gi

