---
apiVersion: v1
kind: Service
metadata:
  name: c2vba-datex2-region-receiver-fg1-fg3
spec:
  ports:
  - name: actuator
    nodePort: 32680
    port: 80
    protocol: TCP
    targetPort: actuator
  - name: mdm-http
    nodePort: 32681
    port: 82
    protocol: TCP
    targetPort: mdm-http
  - name: mdm-https
    nodePort: 32682
    port: 84
    protocol: TCP
    targetPort: mdm-https
  selector:
    app: c2vba-datex2-region-receiver-fg1-fg3
  type: NodePort
