{
  "id" : "DE-10051.M",
  "name" : "DE-10051.M",
  "elements" : [ {
    "id" : "DE1226388422_2",
    "length" : 249.86731387571052,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243333073_2",
    "length" : 31.185991323696857,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243333072_2",
    "length" : 32.163112348598794,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1304795873_2",
    "length" : 29.012762035839607,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1304795872_2",
    "length" : 146.5224402130146,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783184485_2",
    "length" : 120.74526961626336,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921114730_2",
    "length" : 132.98446121594972,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921114729_2",
    "length" : 552.1547200556096,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236104533_2",
    "length" : 66.7667422000188,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236104535_2",
    "length" : 49.5503905500329,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236104534_2",
    "length" : 713.0550396455075,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236103365_2",
    "length" : 33.37692879190342,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236103364_2",
    "length" : 608.0721560565594,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243330436_2",
    "length" : 66.44463293314388,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243330435_2",
    "length" : 356.1153600466389,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819415968_2",
    "length" : 328.88954969452504,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819415967_2",
    "length" : 181.9873323155743,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819416166_2",
    "length" : 137.16621640584054,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819416165_2",
    "length" : 129.40595385771303,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1223766176_2",
    "length" : 74.82679450833427,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1223766175_2",
    "length" : 59.74795156583961,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562822187_2",
    "length" : 57.570616786078176,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE854232458_2",
    "length" : 18.878182040509703,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE854232457_2",
    "length" : 191.98184701775193,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562822181_2",
    "length" : 81.7570601420966,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921121355_1",
    "length" : 71.51579566758146,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1286505843_1",
    "length" : 85.95762614459369,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1286505844_1",
    "length" : 57.2445760514899,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562822203_1",
    "length" : 39.22020789287788,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783181645_1",
    "length" : 73.31875226591086,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921121357_1",
    "length" : 108.1836355987752,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921121358_1",
    "length" : 150.70793388277755,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1202902227_1",
    "length" : 295.85213807372025,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1202902226_2",
    "length" : 158.32423815523163,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1232629871_2",
    "length" : 81.02000229457785,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1232629870_2",
    "length" : 36.41839939652372,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554340632_2",
    "length" : 78.34467316753774,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554340631_2",
    "length" : 170.79430302761324,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE769313392_2",
    "length" : 260.84418182486615,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225525829_2",
    "length" : 40.85304820227459,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225525828_2",
    "length" : 82.38583143984525,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225525831_2",
    "length" : 218.18572437904047,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225525830_2",
    "length" : 177.6397419800964,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243330225_2",
    "length" : 23.765342631109654,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1269028722_2",
    "length" : 217.71967855281017,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1269028721_2",
    "length" : 32.441947971766396,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819417613_2",
    "length" : 60.01260781259715,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1267860546_2",
    "length" : 131.96576130081385,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1267860545_2",
    "length" : 20.84220061613738,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783166475_2",
    "length" : 86.34461847948498,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268139217_2",
    "length" : 79.56467231600207,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268139216_2",
    "length" : 24.554241954545624,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819421089_2",
    "length" : 21.584495790728948,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819421088_2",
    "length" : 155.54657760917132,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554340549_2",
    "length" : 192.8420991144322,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1240787795_2",
    "length" : 73.7417007425652,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1240787797_2",
    "length" : 121.46213385336627,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1240787796_2",
    "length" : 32.803616308608724,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783166466_2",
    "length" : 107.20728164004707,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783166465_2",
    "length" : 492.9410831269623,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1240787799_2",
    "length" : 52.60562389098355,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1240787798_2",
    "length" : 532.1933246491245,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  } ],
  "direction" : "POSITIVE",
  "firstOffset" : 100.0,
  "lastOffset" : 275.99999999999994,
  "length" : 8740.985318400217
}