{
  "id" : "DE-10041.M",
  "name" : "DE-10041.M",
  "elements" : [ {
    "id" : "DE1289956220_2",
    "length" : 50.589345126067144,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289537255_2",
    "length" : 42.43612176440608,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1183005052_2",
    "length" : 86.67099973612363,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1183005051_2",
    "length" : 24.05100715284979,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921715205_2",
    "length" : 61.51479492641981,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289592076_2",
    "length" : 65.70200924373833,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307984192_2",
    "length" : 15.546969351784188,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307984191_2",
    "length" : 25.783274070875112,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289956224_2",
    "length" : 297.7566086099102,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289956223_2",
    "length" : 59.15439586431849,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225155555_2",
    "length" : 68.87816877997223,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289592078_2",
    "length" : 59.513708377122526,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289592077_2",
    "length" : 220.52820038862654,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  } ],
  "direction" : "POSITIVE",
  "firstOffset" : 6.0,
  "lastOffset" : 7.000000000000001,
  "length" : 858.5974030035876
}