{
  "id" : "DE-10034.M",
  "name" : "DE-10034.M",
  "elements" : [ {
    "id" : "DE1225161427_1",
    "length" : 104.40870615326051,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193221405_1",
    "length" : 70.18503732384211,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193221406_1",
    "length" : 116.79876055634102,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193221407_1",
    "length" : 165.25158644266548,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307342315_1",
    "length" : 48.808741633811195,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307342316_1",
    "length" : 265.7718918093668,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554334959_1",
    "length" : 122.63782851270742,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1295735118_1",
    "length" : 111.01433128211778,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1295735117_1",
    "length" : 179.91516021841989,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1302008882_1",
    "length" : 193.4733790014631,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  } ],
  "direction" : "POSITIVE",
  "firstOffset" : 21.0,
  "lastOffset" : 0.0,
  "length" : 1163.7920439325324
}