###########################################################################
#
# Makefile fuer die neue gemeinsame Produktionsumgebug mit Ronalds makefile
#
# Voraussetzungen : 
#
# Die Shellvariablen
#
###########################################################################
#
#
#----let global make know which targets are supported-----
all:
proto:
#link:
clean:

###########################################################################
#
#
############# Flags:

#make_recursive = yes

ddl = mstBuilder.ddl

Headers = gd_ddp_datex2MST.h

variants = debug(_d) release() 


include ${MMDIR}/stddepl

