server.port=4743

spring.data.mongodb.uri=mongodb://adminuser:password123@172.31.246.1:32000/c2vba-ps?appName=strategie-matching&authSource=admin

-Dspring.data.mongodb.uri=mongodb://adminuser:password123@172.31.246.1:32000/c2vba-ps?appName=strategie-matching&authSource=admin
-Dde.heuboe.datex2.mst.config.import.d2Version=D2
-Dde.heuboe.datex2.mst.config.import.xmlCfgFile=D:/by/importMDM_D2DataMapping/data-c2vba/mstConfig.xml

de.heuboe.datex2.mst.definition.import.mstId=UFD
de.heuboe.datex2.mst.definition.import.defVersion=1
de.heuboe.datex2.mst.definition.import.d2Version=2.3_MDM
de.heuboe.datex2.mst.definition.import.schemaCategory=mdm
de.heuboe.datex2.mst.definition.import.schemaFile=DATEXIISchema_2_2_3-FBZExt.xsd
de.heuboe.datex2.mst.definition.import.xmlDefFile=D:/by/importMDM_D2DataMapping/data-c2vba/mstDefinition_UFD.xml


