---
apiVersion: v1
kind: Service
metadata:
  name: c2vba-datex2-region-receiver
spec:
  ports:
  - name: actuator
    nodePort: 32730
    port: 80
    protocol: TCP
    targetPort: actuator
  - name: mdm-http
    nodePort: 32731
    port: 82
    protocol: TCP
    targetPort: mdm-http
  - name: mdm-https
    nodePort: 32732
    port: 84
    protocol: TCP
    targetPort: mdm-https
  selector:
    app: c2vba-datex2-region-receiver
  type: NodePort
