de.heuboe.by.config.import.vrzId=VRZ_BY
de.heuboe.by.config.import.vrzKnotenNr=256000
de.heuboe.by.config.import.uzId=C2VBA
de.heuboe.by.config.import.uzKnotenNr=256011

de.heuboe.by.config.import.aufbereitetDir=..//c2vba-config-data_C//aufbereitet//20251215_164621
de.heuboe.by.config.import.kriFile=..//c2vba-config-data_C//Export_20221013_hb.xlsx
de.heuboe.by.config.import.wwwDir=..//c2vba-config-data_C//www_v1.0.txt

grpc.client.configService.address=dns:///worker1.d.c2vba.heuboe.hbintern:31100
grpc.client.configService.negotiationType=PLAINTEXT
