server.port=0

#
# MDM connection parameter
#
de.heuboe.datex2.remote=SOAP

de.heuboe.datex2.vms.status.pub.receiverType=MDM

# Input Nord table is read from this MDM publication
de.heuboe.datex2.connection.url=https://broker.mdm-portal.de/BASt-MDM-Interface/srv/4486004/clientPullService
de.heuboe.datex2.connection.trustStoreFile=D:/komodnext/mdm/vms/cert/mdm-sectigo-2029.jks
de.heuboe.datex2.connection.trustStorePassword=pFef!KHE
de.heuboe.datex2.connection.keyStoreFile=D:/komodnext/mdm/vms/cert/vzh.heuboe.de.p12
de.heuboe.datex2.connection.keyStorePassword=GUChsx5n2S

de.heuboe.datex2.remote.schemaFile=schema/DATEXIISchema_2_2_3.xsd

# Content of pulled NORD table is not UTF-8 but ISO-8859-1
# If this is property is true (default), the content is converted to UTF-8 
#de.heuboe.c2vba.datex2.table.update.correctEncoding=false

# Type of table: LVE, UFD, SBA or WWW
de.heuboe.c2vba.datex2.table.update.type=LVE

# Input Sued table is read from file
de.heuboe.c2vba.datex2.table.update.tableSFile=F:/sdbby/mdm/mst/LVE/D2MSTPub_LVE_115.xml

# Input Nord table is read from file
de.heuboe.c2vba.datex2.table.update.tableNFile=src/test/resources/nordTables/data-publ-3490001.xml

# Join table is stored as file
de.heuboe.c2vba.datex2.table.update.resultFile=F:/sdbby/mdm/mst/LVE/D2MSTPub_LVE_<version>.xml

# Optional: MDM publication which holds the join files: the created join table is uploaded 
#de.heuboe.c2vba.datex2.table.update.pubUrl=https://broker.mdm-portal.de/BASt-MDM-Interface/srv/3535000/supplierPushService