<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.heuboe.asfinag</groupId>
        <artifactId>vmis2-jprotoc</artifactId>
        <version>4.6.2</version>
    </parent>

    <artifactId>vmis2-jprotoc-plugin</artifactId>

    <name>VMIS2 Kern ${project.artifactId}</name>
    <description>The plugin project for the protopojo extension of the protobuf compiler.</description>

    <properties>
        <!--suppress UnresolvedMavenProperty -->
        <timestamp>${buildtime}</timestamp>
        <maven.build.timestamp.format>yyyy-MM-dd HH:mm:ss Z (z)</maven.build.timestamp.format>
    </properties>

    <dependencies>
        <dependency>
            <groupId>de.heuboe.asfinag</groupId>
            <artifactId>vmis2-jprotoc-transferinterface</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
            <version>3.0.2</version>
        </dependency>

        <!-- using freemarker because we need conditions in markup -->
        <dependency>
            <groupId>org.freemarker</groupId>
            <artifactId>freemarker</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java-util</artifactId>
            <scope>compile</scope>
        </dependency>
        <!-- Tuple and other functional stuff -->
        <dependency>
            <groupId>io.vavr</groupId>
            <artifactId>vavr</artifactId>
            <version>0.10.4</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-text</artifactId>
            <version>1.9</version>
        </dependency>

        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>timestamp-property</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>timestamp-property</goal>
                            <!--
                                <goal>compile</goal>
                                <goal>test-compile</goal>
                            -->
                        </goals>
                        <configuration>
                            <name>buildtime</name>
                            <pattern>yyyy-MM-dd HH:mm:ss Z (z)</pattern>
                            <timeZone>CET</timeZone><!-- central european time -->
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>templating-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>filter-src</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>filter-sources</goal>
                        </goals>
                        <configuration>
                            <!-- Note the two following parameters are the default one. These
                                are specified here just as a reminder. But as the Maven philosophy is strongly
                                about conventions, it's better to just not specify them. -->
                            <sourceDirectory>${basedir}/src/main/java-templates</sourceDirectory>
                            <outputDirectory>${project.build.directory}/generated-sources/java-templates</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!--
                compile *.proto files
            -->
            <plugin>
                <groupId>org.xolstice.maven.plugins</groupId>
                <artifactId>protobuf-maven-plugin</artifactId>
                <configuration>
                    <clearOutputDirectory>false</clearOutputDirectory>
                    <protocArtifact>com.google.protobuf:protoc:${protobuf.version}:exe:${os.detected.classifier}</protocArtifact>
                </configuration>
                <executions>
                    <execution>
                        <id>protobuf-test-compile</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                        <configuration>
                            <attachProtoSources>false</attachProtoSources>
                            <writeDescriptorSet>false</writeDescriptorSet>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
