grpc.client.CfgServiceNrw.address=
#
grpc.client.GeoManagerNrw.address=
grpc.client.FeatureSvcNrw.address=
#
de.heuboe.nrw.sitecfg.svc.rep.root=
de.heuboe.nrw.sitecfg.svc.rep.sites=
de.heuboe.nrw.sitecfg.svc.rep.creation.mode=file
