server.port=8080

de.heuboe.datex2.mdp.country=DE
de.heuboe.datex2.mdp.nationalId=${MDM_BY_ORGA_KEY}
de.heuboe.datex2.mdp.language=de

de.heuboe.datex2.mdp.pubType=MDP_PUB_TYPE

de.heuboe.datex2.mdp.mdm=true

spring.data.mongodb.uri=mongodb://${MONGODB_AUTHORITY}/datex2MST?authSource=admin&readPreference=primary&appname=c2vba-mstBuilder-fg1&ssl=false
spring.kafka.consumer.group-id=C2VBA-MDPBuilder-FG1
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP}

de.heuboe.datex2.mdp.deFehlerTopic=C2VBA-tlsin-LVEDeFehler

# Der Zeitpunkt zu welchem der Prozess neue Daten schicken soll
# 0 * * * * * ist zu jeder vollen Minute
cron.expression=0 * * * * *

de.heuboe.datex2.mdp.mstId=LVE
de.heuboe.datex2.mdp.mstVersion=${SUED-MST-FG1-VERSION}

de.heuboe.datex2.mdp.maxDataAge=600000
de.heuboe.datex2.mdp.onlyActive=false
de.heuboe.datex2.mdp.checkValid=true
de.heuboe.datex2.mdp.writeVehClass=false
de.heuboe.datex2.mdp.ejectEmptySiteMeasurements=false
de.heuboe.datex2.mdp.invalidValsAsDataError=false

de.heuboe.datex2.mdp.checkValidity=""

de.heuboe.datex2.mdp.pubInstance=""

de.heuboe.datex2.mdp.schemaModelBaseVersion=2

de.heuboe.datex2.schema.datex2SchemaFile=schema/MeasuredData.xsd



# Publikationen werden dem c2vba-datex2-region-receiver-fg1-fg3 direkt zugestellt: kein MDM-Umweg

de.heuboe.datex2.connection.url=http://c2vba-datex2-region-receiver-fg1-fg3.c2vba.svc:82/datex2/services/supplierPushService-fg1-sued
de.heuboe.datex2.connection.trustStoreFile=
de.heuboe.datex2.connection.trustStorePassword=
de.heuboe.datex2.connection.keyStoreFile=
de.heuboe.datex2.connection.keyStorePassword=


#Publications may simply be provided in file system
de.heuboe.datex2.connection.pubPath=/files/pub


de.heuboe.datex2.remote.accessType=SOAP
de.heuboe.datex2.remote.d2Version=v2_2_3
de.heuboe.datex2.remote.validate=true


## --------------------------------------------------------------------------
## Actuator
## --------------------------------------------------------------------------
management.endpoints.web.exposure.include=health
management.endpoints.web.exposure.exclude=shutdown
management.endpoint.metrics.enabled=true
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

