<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

    <parent>
		<groupId>de.heuboe.tls</groupId>
		<artifactId>iface-parent-pom</artifactId>
		<version>1.0.1-SNAPSHOT</version>
	</parent>

	<artifactId>iface-prot-tls-over-ip</artifactId>

	<dependencies>
		<dependency>
			<groupId>de.heuboe.tls</groupId>
			<artifactId>iface-interfaces</artifactId>
		</dependency>
		<dependency>
			<groupId>de.heuboe.tls</groupId>
			<artifactId>iface-lib</artifactId>
		</dependency>

        <dependency>
            <groupId>de.heuboe.tls</groupId>
            <artifactId>tls-tele</artifactId>
    		<version>${tls-tele.version}</version>
            <scope>test</scope>
        </dependency>


        <!-- third party -->

		<!-- Google json implementation gson -->
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
		</dependency>
        <!-- lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>

        <!-- testing only -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>

	</dependencies>

</project>
