server.port=4723


##
## Kafka
##

## Connection
spring.kafka.bootstrap-servers=master1.d.c2vba.heuboe.hbintern:32002

# Consumer ID
spring.kafka.consumer.group-id=c2vba-datex2-join-vms-fg1-ps-test

# Default serialization types
spring.kafka.consumer.properties.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.producer.properties.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer

de.heuboe.kafka.listener.enable.auto.commit=false


de.heuboe.c2vba.datex2.join.pubMode= CyclicSnapshot
de.heuboe.c2vba.datex2.join.pubInterval= 60
de.heuboe.c2vba.datex2.join.pubFileDir = D:/by/c2vba/mdp/join/fg1

de.heuboe.c2vba.datex2.join.tableId = BY-C2VBA-FG1
de.heuboe.c2vba.datex2.join.tableVersion = 31

de.heuboe.c2vba.datex2.join.topicSued = C2VBA-datex2-publication-mdp-fg1-sued
de.heuboe.c2vba.datex2.join.topicNord = C2VBA-datex2-publication-mdp-fg1-nord-test


#
# MDM connection parameter
#
de.heuboe.datex2.remote=SOAP

de.heuboe.datex2.connection.useGzip=true

de.heuboe.datex2.vms.status.pub.receiverType=MDM

#de.heuboe.datex2.connection.url=https://broker.mdm-portal.de/BASt-MDM-Interface/srv/3464000/supplierPushService
#de.heuboe.datex2.connection.trustStoreFile=D:/komodnext/mdm/vms/cert/mdm-sectigo-2029.jks
#de.heuboe.datex2.connection.trustStorePassword=pFef!KHE
#de.heuboe.datex2.connection.keyStoreFile=D:/komodnext/mdm/vms/cert/vzh.heuboe.de.p12
#de.heuboe.datex2.connection.keyStorePassword=GUChsx5n2S

de.heuboe.datex2.connection.url=http://sdbby-2k19:5717/D2PushReceiver


#de.heuboe.datex2.connection.url=https://mobilithek.info:8443/mobilithek/api/v1.0/subscription/soap/554340481566113792/clientPullService
#de.heuboe.datex2.connection.trustStoreFile=D:/komodnext/mdm/vms/cert/cacerts
#de.heuboe.datex2.connection.trustStorePassword=changeit
#de.heuboe.datex2.connection.keyStoreFile=D:/komodnext/mdm/vms/cert/certificate.p12
#de.heuboe.datex2.connection.keyStorePassword=V@zahxTPP#pN



