server.port=4723


##
## Kafka
##

## Connection
spring.kafka.bootstrap-servers=master1.d.c2vba.heuboe.hbintern:32002

# Consumer ID
spring.kafka.consumer.group-id=c2vba-datex2-join-vms-sba-ps-test

# Default serialization types
spring.kafka.consumer.properties.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.producer.properties.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer


de.heuboe.c2vba.datex2.join.pubInterval= 300
de.heuboe.c2vba.datex2.join.pubFileDir = D:/by/c2vba/vms/join/sba

de.heuboe.c2vba.datex2.join.outdatedInterval= 864000

de.heuboe.c2vba.datex2.join.tableId = BY-C2VBA-SBA
de.heuboe.c2vba.datex2.join.tableVersion = 31

de.heuboe.c2vba.datex2.join.topicSued = C2VBA-datex2-publication-vms-srp-sued
de.heuboe.c2vba.datex2.join.topicNord = C2VBA-datex2-publication-vms-sba-nord


#
# MDM connection parameter
#
de.heuboe.datex2.remote=SOAP

de.heuboe.datex2.vms.status.pub.receiverType=MDM
de.heuboe.datex2.connection.url=https://mobilithek.info:8443/mobilithek/api/v1.0/publication/soap/674073327410540544/supplierPushService
de.heuboe.datex2.connection.trustStoreFile=
de.heuboe.datex2.connection.trustStorePassword=
de.heuboe.datex2.connection.keyStoreFile=D:/komodnext/mdm/vms/cert/mobi.hb.certificate.p12
de.heuboe.datex2.connection.keyStorePassword=V@zahxTPP#pN

#de.heuboe.datex2.connection.url=http://sdbby-2k19:5717/D2PushReceiver


