server.port=4723


##
## Kafka
##

## Connection
spring.kafka.bootstrap-servers=master1.d.c2vba.heuboe.hbintern:32002

# Consumer ID
spring.kafka.consumer.group-id=c2vba-datex2-join-vms-sba-ps-test

# Default serialization types
spring.kafka.consumer.properties.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.producer.properties.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer


de.heuboe.c2vba.datex2.join.pubInterval= 300
de.heuboe.c2vba.datex2.join.pubFileDir = D:/by/c2vba/vms/join/sba

de.heuboe.c2vba.datex2.join.outdatedInterval= 864000

de.heuboe.c2vba.datex2.join.tableId = D2-C2VBA-WWW-Table
de.heuboe.c2vba.datex2.join.tableVersion = 113_6

de.heuboe.c2vba.datex2.join.topicSued = C2VBA-datex2-publication-vms-www-sued
de.heuboe.c2vba.datex2.join.topicNord = C2VBA-datex2-publication-vms-www-nord


#
# MDM connection parameter
#
de.heuboe.datex2.remote=SOAP

de.heuboe.datex2.vms.status.pub.receiverType=MDM

#de.heuboe.datex2.connection.url=https://broker.mdm-portal.de/BASt-MDM-Interface/srv/3464000/supplierPushService
de.heuboe.datex2.connection.url=https://139.2.223.157/BASt-MDM-Interface/srv/3464000/supplierPushService


de.heuboe.datex2.connection.trustStoreFile=D:/komodnext/mdm/vms/cert/mdm-sectigo-2029.jks
de.heuboe.datex2.connection.trustStorePassword=pFef!KHE
de.heuboe.datex2.connection.keyStoreFile=D:/komodnext/mdm/vms/cert/vzh.heuboe.de.p12
de.heuboe.datex2.connection.keyStorePassword=GUChsx5n2S

de.heuboe.datex2.connection.disableCNCheck=true

#de.heuboe.datex2.connection.url=http://sdbby-2k19:5717/D2PushReceiver


