syntax = "proto3";

package eu.vmis_ehe.vmis2.configservice;

import "ConfigBase.proto";
import "heuboe/protobuf/Documentation.proto";
import "heuboe/protobuf/InterfaceVersion.proto";

option java_multiple_files = true;
option csharp_namespace = "eu.vmis_ehe.vmis2.configservice";
option (.heuboe.protobuf.interface_version) = "1.16.27";

// Structures used to describe AQs and WZGs

// AQ 'AnzeigeQuerschnitt'
message CfgAq {
    option (.heuboe.protobuf.stereotype) = ENTITY;

    enum AqType {
        UNKNOWN = 0;
        AQ = 1;                 // Standard-Anzeigequerschnitte der Verkehrsbeeinflussung
        VV = 7;                 // Vorankündigung von Verkehrslichtsignalanlagen
        EFQ = 8;                // Anzeigequerschnitt für Geschwindigkeitsbeschränkungen am oder kurz vor dem Ende zuführender Rampen
        WTA = 3;                // Wechseltextanzeige
        WWW = 2;                // Wechselwegweiser
        WWW_FG5 = 12;           // Oldish WWW-Types, deprecated, but still existing
        WTV = 4;                // Wechseltextanzeige Vollgrafik (MULTI)
        VLSA = 6;               // Verkehrslichtsignalanlagen
        INFO = 5;               // Vollmatrix-Informationstafel
        VHT = 9;                // Variable Hinweistafel im Sinne eines nicht anderweitig klassifizierten veränderbaren Verkehrszeichens.
        WZG = 10;               // Standard-WZGs (A,B,C) in Kombination mit anderen Hinweistafeln
        DWISTA = 11;            // komplexe Infotafel
    }
    string id = 1;
    string name = 2;
    string uz_id = 3;
    AqType type = 4;
    Heading heading = 5;
    oneof wzg {
        CfgIds wzg_ids = 6;
        CfgWzgs wzgs = 7;
    }
    repeated string cluster_ids = 10;
    repeated AqCluster clusters = 11;
    Location location = 20;
    Scope scope = 21 [(.heuboe.protobuf.required) = false];
}
message CfgAqs {
    option (.heuboe.protobuf.stereotype) = CONTAINER;

    repeated CfgAq aqs = 1;
}

message AqCluster {
    option (.heuboe.protobuf.stereotype) = DATATYPE;

    string id = 1;
    string name = 3;
    repeated string wzg_ids = 2;
}

// AQ's variable message sign (WZG)
message CfgWzg {
    option (.heuboe.protobuf.stereotype) = ENTITY;

    enum WzgType {
        UNKNOWN = 0;
        WZG_A = 1;             // WZG Typ A
        WZG_B = 2;             // WZG Typ B
        WZG_C = 3;             // Zusatzzeichen zum WZG B
        WZG_ZA = 4;            // Zusatzzeichen zum WZG A
        BLINKER = 5;           // Blinker
        FAILSAFE = 6;          // Fail-Safe-Prismenwender
        PW = 7;                // Sonstiger Prismenwender
        WTA_B = 8;             // WZG Typ B einer WTA
        VLSA3 = 10;            // Lichtsignalanlage (Rot, Gelb, Grün)
        WTV = 9;               // Wechseltextanzeige variabel
        INFO = 14;             // Info
        VHT = 15;              // Variable Hinweistafel im Sinne eines nicht anderweitig klassifizierten veränderbaren Verkehrszeichens.
        FASI = 16;             // Fahrstreifen-Signalisierung (Typ A mit besonderen Fähigkeiten)
    }

    enum DisplayType {
        UNKNOWN_DISPLAY_TYPE = 0;
        A = 1;
        B = 2;
        C = 3;
        D = 4;
        E = 5;
    }

    string id = 1;
    string name = 2;
    string uz_id = 3;
    WzgType type = 4;
    LanePos lane_pos = 5;
    Heading heading = 6;
    repeated WzgSymbol symbols = 7 [(.heuboe.protobuf.required) = false];   // optional, for WZGs that can display one of several predefined symbols
    repeated WzgFont fonts = 8 [(.heuboe.protobuf.required) = false];       // optional, for WZGs that can display arbitrary text
    //  repeated string www_wzg_ids = 9;                                    // deprecated
    repeated CmpProgram cmp_programs = 10;                                  // optional, E-type WZGs only
    repeated CfgComponent cmp_components = 24;                              // optional, E-type WZGs only
    DisplayType display_type = 11;
    string q_id = 12;
    Location location = 20;
    Scope scope = 23 [(.heuboe.protobuf.required) = false];

    // deprecated, but kept for compatibility (for now; will be removed for next version)
    oneof component {                                                       // optional, E-type WZGs only (deprecated, see cmp_components)
                                                                            CfgIds component_ids = 21 [(.heuboe.protobuf.required) = false];
                                                                            CfgWzgs components = 22 [(.heuboe.protobuf.required) = false];
    }

}
message CfgWzgs {
    option (.heuboe.protobuf.stereotype) = CONTAINER;
    repeated CfgWzg wzgs = 1;
}

// One component of an E-type WZG
message CfgComponent {
    option (.heuboe.protobuf.stereotype) = ENTITY;

    string id = 1;
    string name = 2;
    string uz_id = 3;
    repeated WzgSymbol symbols = 7;
    string wzg_id = 12;
    Scope scope = 23 [(.heuboe.protobuf.required) = false];
}

// WZG symbol definition (for WZGs that can display one of several predefined symbols)
message WzgSymbol {
    option (.heuboe.protobuf.stereotype) = DATATYPE;

    enum TrafficSignificance {      // enum constants correspond to TLS WVZ codes (for now).

        NONE = 0;
        DANGER = 1;
        UNEVEN_SURFACE = 2;
        SLIPPERINESS_RISK = 3;
        SKIDDING_RISK = 4;
        ROAD_NARROWS = 5;
        ROAD_NARROWS_RIGHT = 6;
        ROAD_NARROWS_LEFT = 7;
        ROADWORKS = 8;
        CONGESTION = 9;
        ONCOMING_TRAFFIC = 10;
        SNOWFALL = 11;
        TRAFFIC_SIGNALS = 12;

        reserved 13 to 19;

        SPEED_LIMIT_20_KMH = 20;
        SPEED_LIMIT_30_KMH = 21;
        SPEED_LIMIT_40_KMH = 22;
        SPEED_LIMIT_50_KMH = 23;
        SPEED_LIMIT_60_KMH = 24;
        SPEED_LIMIT_70_KMH = 25;
        SPEED_LIMIT_80_KMH = 26;
        SPEED_LIMIT_90_KMH = 27;
        SPEED_LIMIT_100_KMH = 28;
        SPEED_LIMIT_110_KMH = 29;
        SPEED_LIMIT_120_KMH = 30;
        NO_PASSING = 31;
        NO_PASSING_TRUCKS = 32;
        SPEED_LIMIT_130_KMH = 33;

        reserved 34 to 37;

        NO_VEHICLES_SMOG = 38;
        NO_VEHICLES = 39;
        END_SPEED_LIMIT_20_KMH = 40;
        END_SPEED_LIMIT_30_KMH = 41;
        END_SPEED_LIMIT_40_KMH = 42;
        END_SPEED_LIMIT_50_KMH = 43;
        END_SPEED_LIMIT_60_KMH = 44;
        END_SPEED_LIMIT_70_KMH = 45;
        END_SPEED_LIMIT_80_KMH = 46;
        END_SPEED_LIMIT_90_KMH = 47;
        END_SPEED_LIMIT_100_KMH = 48;
        END_SPEED_LIMIT_110_KMH = 49;
        END_SPEED_LIMIT_120_KMH = 50;
        END_NO_PASSING = 51;
        END_NO_PASSING_TRUCKS = 52;
        END_ALL_PROHIBITIONS = 53;
        END_SPEED_LIMIT_130_KMH = 54;

        reserved 55 to 60;

        YELLOW_BLINKER = 61;
        ADD_TEXT_CONGESTION = 62;
        ADD_TEXT_CONGESTION_RISK = 63;
        ADD_TEXT_FOG = 64;
        ADD_TEXT_WETNESS = 65;
        ADD_TEXT_ACCIDENT = 66;
        ADD_TEXT_VISIBILITY = 67;

        reserved 68;

        ADD_TEXT_ROAD_GRAVEL = 69;
        ADD_TEXT_MOWING = 70;
        ADD_TEXT_OZONE = 71;
        ADD_TEXT_NOISE_PROTECTION = 72;

        reserved 73;

        ADD_TEXT_600M = 74;

        reserved 75 to 77;

        ADD_TEXT_200M = 78;
        ADD_TEXT_300M = 79;
        ADD_TEXT_400M = 80;
        ADD_TEXT_500M = 81;
        ADD_TEXT_1000M = 82;
        ADD_TEXT_1500M = 83;
        ADD_TEXT_2000M = 84;
        ADD_TEXT_2500M = 85;
        ADD_TEXT_3000M = 86;
        ADD_TEXT_4000M = 87;
        ADD_TEXT_5000M = 88;

        reserved 89;

        ADD_TEXT_NEXT_200M  = 90;
        ADD_TEXT_NEXT_500M  = 91;
        ADD_TEXT_NEXT_1000M = 92;
        ADD_TEXT_NEXT_1500M = 93;
        ADD_TEXT_NEXT_2000M = 94;
        ADD_TEXT_NEXT_2500M = 95;
        ADD_TEXT_NEXT_3000M = 96;
        ADD_TEXT_NEXT_4000M = 97;
        ADD_TEXT_NEXT_5000M = 98;

        reserved 99;

        ADD_TEXT_2_8T = 100;
        ADD_TEXT_4T = 101;
        ADD_TEXT_7_5T = 102;
        ADD_TEXT_UNEXPECTED_BLACK_ICE = 103;
        ADD_SIGN_TRUCKS_ONLY = 104;
        ADD_SIGN_CARS_ONLY = 105;
        ADD_SIGN_CONGESTION_RISK = 106;
        RED = 107;
        YELLOW = 108;
        GREEN = 109;
        RED_YELLOW = 110;
        RED_X = 111;
        GREEN_ARROW_DOWN = 112;
        YELLOW_ARROW_LEFT = 113;
        YELLOW_ARROW_RIGHT = 114;

        reserved 115 to 120;

        RECOMMENDED_SPEED_30_KMH = 121;
        RECOMMENDED_SPEED_40_KMH = 122;
        RECOMMENDED_SPEED_50_KMH = 123;
        RECOMMENDED_SPEED_60_KMH = 124;
        RECOMMENDED_SPEED_70_KMH = 125;
        RECOMMENDED_SPEED_80_KMH = 126;
        RECOMMENDED_SPEED_90_KMH = 127;
        RECOMMENDED_SPEED_100_KMH = 128;
        RECOMMENDED_SPEED_110_KMH = 129;
        RECOMMENDED_SPEED_120_KMH = 130;
        RECOMMENDED_SPEED_130_KMH = 131;

        reserved 132 to 140;

        END_RECOMMENDED_SPEED_30_KMH = 141;
        END_RECOMMENDED_SPEED_40_KMH = 142;
        END_RECOMMENDED_SPEED_50_KMH = 143;
        END_RECOMMENDED_SPEED_60_KMH = 144;
        END_RECOMMENDED_SPEED_70_KMH = 145;
        END_RECOMMENDED_SPEED_80_KMH = 146;
        END_RECOMMENDED_SPEED_90_KMH = 147;
        END_RECOMMENDED_SPEED_100_KMH = 148;
        END_RECOMMENDED_SPEED_110_KMH = 149;
        END_RECOMMENDED_SPEED_140_KMH = 150;
        END_RECOMMENDED_SPEED_130_KMH = 151;

        reserved 152 to 214;

        ADD_TEXT_NEXT_1700M = 215;
        ADD_TEXT_NEXT_1800M = 216;
        ADD_TEXT_NEXT_1900M = 217;
        ADD_TEXT_NEXT_2100M = 218;

        reserved 219 to 224;

        ADD_TEXT_3_5T = 225;
        ADD_TEXT_DISTANCE = 226;
        ADD_TEXT_WRONG_WAY_DRIVER = 227;
        ADD_TEXT_SLIPPERINESS_RISK = 228;
        ADD_TEXT_SLIPPERINESS = 229;
        ADD_TEXT_IG_LUFT = 230;
        ADD_TEXT_SPOT_CHECK = 231;
        ADD_TEXT_OIL_SPILL = 232;
        ADD_TEXT_BREAKDOWN = 233;
        ADD_TEXT_CROSSWIND = 234;
        ADD_TEXT_TUNNEL_CLOSED = 235;
        ADD_TEXT_DETOUR = 236;

        reserved 237 to 240;

        PRISM_1 = 241;
        PRISM_2 = 242;
        PRISM_3 = 243;
        PRISM_4 = 244;

        reserved 245 to 255;
    }

    int32 code = 1;                                 // This particular symbol's code, must be unique for one WZG

    oneof name {                                    // Symbol's name, either
        TrafficSignificance significance = 2;       //  a traffic relevant constant, or
        string plaintext = 3;                       //  a simple text (for custom symbols)
    }

    int32 blink_frequency = 4 [(.heuboe.protobuf.required) = false];            // Optional, for WVZs that should blink by default

    repeated WzgSymbol components = 10[(.heuboe.protobuf.required) = false];    // Optional, E_type WZGs only: Component symbols for this 'program's code
}

// WZG font definition (for WZGs that can display arbitrary text)
message WzgFont {
    option (.heuboe.protobuf.stereotype) = DATATYPE;

    string id = 1;
    string name = 2;
}

// Component program definition: A named list of symbol codes for an E-type WZG group's list of components,
// with one symbol for each of WZG's component, ordered like those components
message CmpProgram {
    option (.heuboe.protobuf.stereotype) = DATATYPE;

    string id = 1;
    string name = 2;
    repeated CmpCode codes = 3;                     // Codes for WZG's components
}
message CmpCode {
    option (.heuboe.protobuf.stereotype) = DATATYPE;

    string component_id = 1;                        //
    int32 symbol_code = 2;                          //
}
