syntax = "proto3";

package eu.vmis_ehe.vmis2.configservice;

import "ConfigAqData.proto";
import "ConfigBase.proto";
import "ConfigMqUqVq.proto";
import "heuboe/protobuf/Documentation.proto";
import "heuboe/protobuf/InterfaceVersion.proto";

option java_multiple_files = true;
option csharp_namespace = "eu.vmis_ehe.vmis2.configservice";
option (.heuboe.protobuf.interface_version) = "1.16.27";

// Structures for various TLS devices

// standard UZ
message CfgUz {
    option (.heuboe.protobuf.stereotype) = ENTITY;

    string id = 1;
    string name = 2;
    oneof mq {
        CfgIds mq_ids = 3;
        CfgMqs mqs = 4;
    }    
    oneof aq {
        CfgIds aq_ids = 5;
        CfgAqs aqs = 6;
    }    
    oneof ude_sensor {
        CfgIds ude_sensor_ids = 7;
        CfgUdeSensors ude_sensors = 8;
    }    
    oneof vlt_sensor {
        CfgIds vlt_sensor_ids = 9;
        CfgVltSensors vlt_sensors = 10;
    }
    oneof kri {
        CfgIds kri_ids =11;
        CfgKris kris = 12;
    }
    oneof route_station {
        CfgIds route_station_ids = 13;
        CfgRouteStations route_stations = 14;
    }
    oneof fcd {
        CfgIds fcd_ids = 15;
        CfgFcds fcds = 16;
    }
    oneof grp {
        CfgIds grp_ids = 17;
        CfgGroups groups = 18;
    }
    Location location = 20;
    Scope scope = 21;
}
message CfgUzs {
    option (.heuboe.protobuf.stereotype) = CONTAINER;

    repeated CfgUz uzs = 1;
}

// Kri
message CfgKri {
    option (.heuboe.protobuf.stereotype) = ENTITY;

    enum KriType {
        UNKNOWN = 0;
        TWO_B = 1;
        TWO_C = 2;
        VIRTUAL = 3;
    }
    string id = 1;
    string name = 2;
    string uz_id = 3;
    KriType type = 7;
    oneof route_station {
        CfgIds route_station_ids = 4;
        CfgRouteStations route_stations = 5;
    }
    bool kri2C = 6;
    Location location = 20;
    Scope scope = 21;
}
message CfgKris {
    option (.heuboe.protobuf.stereotype) = CONTAINER;

    repeated CfgKri kris = 1;
}

// Route Station
message CfgRouteStation {
    option (.heuboe.protobuf.stereotype) = ENTITY;

    string id = 1;
    string name = 2;
    string uz_id = 3;
    oneof vde_sensor {
        CfgIds vde_sensor_ids = 5;
        CfgVdeSensors vde_sensors = 6;
    }
    oneof wzg {
        CfgIds wzg_ids = 7;
        CfgWzgs wzgs = 8;
    }
    oneof ude_sensor {
        CfgIds ude_sensor_ids = 9;
        CfgUdeSensors ude_sensors = 10;
    }    
    oneof vlt_sensor {
        CfgIds vlt_sensor_ids = 11;
        CfgVltSensors vlt_sensors = 12;
    }
    oneof fcd {
        CfgIds fcd_ids = 13;
        CfgFcds fcds = 14;
    }
    Location location = 20;
    Scope scope = 21;
}
message CfgRouteStations {
    option (.heuboe.protobuf.stereotype) = CONTAINER;

    repeated CfgRouteStation route_stations = 1;
}
