server.port=8088


#spring.data.mongodb.uri=mongodb://he3-w7v/nrwDatex2VmsTable01


de.heuboe.datex2.vms.status.pub.tableId=KOMOD-D2-VMS-Unit-Table-VRZ-Lev
de.heuboe.datex2.vms.status.pub.tableVersion=24
de.heuboe.datex2.vms.status.pub.pubInstance=ps
de.heuboe.datex2.vms.status.pub.fileDir=F:/komod/vms
de.heuboe.datex2.vms.status.pub.pubInterval=60
de.heuboe.datex2.vms.status.pub.pubMode=OnUpdateCyclicSnapshot
de.heuboe.datex2.vms.status.pub.sender=DE-NW-NRW
de.heuboe.datex2.vms.status.pub.datex2Target=MDM
de.heuboe.datex2.vms.status.pub.vmsServiceUrl=http://localhost:8083/Datex2/VMSPublication/Service

de.heuboe.datex2.vms.status.pub.vmsServiceListenerHost=0.0.0.0
de.heuboe.datex2.vms.status.pub.vmsServiceListenerPort=4748

#de.heuboe.datex2.vms.status.pub.checkData=true

#de.heuboe.datex2.vms.status.pub.mdmAuthenticationFile=D:/komodnext/mdm/vms/cert/mdmAuth-vms.properties

de.heuboe.datex2.vms.status.pub.receiverType=MDM

de.heuboe.datex2.connection.url=https://broker.mdm-portal.de/BASt-MDM-Interface/srv/2678000/supplierPushService
de.heuboe.datex2.connection.trustStoreFile=D:/komodnext/mdm/vms/cert/mdm-sectigo-2029.jks
de.heuboe.datex2.connection.trustStorePassword=pFef!KHE
de.heuboe.datex2.connection.keyStoreFile=D:/komodnext/mdm/vms/cert/vzh.heuboe.de.p12
de.heuboe.datex2.connection.keyStorePassword=GUChsx5n2S

de.heuboe.datex2.remote=SOAP

## --------------------------------------------------------------------------
## Kafka
## --------------------------------------------------------------------------

spring.kafka.bootstrap-servers=kafka1.d.uz.komodnext.heuboe.hbintern:9092

# Consumer ID
spring.kafka.consumer.group-id=vms-status-publication-ps-test

# Default serialization types
spring.kafka.consumer.properties.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.producer.properties.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer



## --------------------------------------------------------------------------
## Actuator
## --------------------------------------------------------------------------
management.endpoints.web.exposure.include=health
management.endpoints.web.exposure.exclude=shutdown
management.endpoint.metrics.enabled=true
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true