server.port=8080

# VMS table publication ID
de.heuboe.datex2.vms.status.pub.tableId=BY-SDB-D2-VMS-Unit-Table-SBA

# VMS table publication version
de.heuboe.datex2.vms.status.pub.tableVersion=${SUED-VMS-SBA-VERSION}


# Generated DATEX-II publications are logged as files
de.heuboe.datex2.vms.status.pub.fileDir=/files

# SOAP communication timeout
de.heuboe.datex2.vms.status.pub.connTimeout=20000

# Snapshot interval (seconds)
de.heuboe.datex2.vms.status.pub.pubInterval=300

# Publication mode: updates are sent immediately, each 'pubInterval' seconds an addtional snapshot is generated
de.heuboe.datex2.vms.status.pub.pubMode=OnUpdateCyclicSnapshot

# Sender identification in DATEX-II publications: MDM_BY_ORGA_KEY = DE-NAP-Heusch/Boesefeldt GmbH
de.heuboe.datex2.vms.status.pub.sender=${MDM_BY_ORGA_KEY}

# DATEX-II target
de.heuboe.datex2.vms.status.pub.datex2Target=Mobilithek


## --------------------------------------------------------------------------
## VmsPublicationService
## --------------------------------------------------------------------------

# SOAP server providing switching data
de.heuboe.datex2.vms.status.pub.vmsServiceUrl=http://vms-publication-service.c2vba.svc:81/Datex2/VMSPublication/Service?wsdl


# This process exposes a SOAP server to receive switching data sent by VmsPublicationService 

# SOAP server host
de.heuboe.datex2.vms.status.pub.vmsServiceListenerHost=0.0.0.0

# SOAP server port
de.heuboe.datex2.vms.status.pub.vmsServiceListenerPort=4748

# Context
de.heuboe.datex2.vms.status.pub.pubInstance=ps


# Host used by VmsPublicationService
de.heuboe.datex2.vms.status.pub.vmsServiceListenerHostExt=vms-status-publication.c2vba.svc

# Port used by VmsPublicationService
de.heuboe.datex2.vms.status.pub.vmsServiceListenerPortExt=81




# Receiver type
de.heuboe.datex2.vms.status.pub.receiverType=MDM

# Receiver of generated DATEX-II VMS publications
de.heuboe.datex2.connection.url=http://c2vba-datex2-region-receiver-sba.c2vba.svc:82/c2vba/sba/services/supplierPushService-sba-sued


# HTTP content is zipped
de.heuboe.datex2.connection.useGzip=true

# Communication protocol is SOAP
de.heuboe.datex2.remote=SOAP


# No pictogram URLs published (reason: for many signs the URL does not return an image)  
de.heuboe.datex2.vms.status.pub.writePictogramUrl=false

## --------------------------------------------------------------------------
## Kafka
## --------------------------------------------------------------------------

# Kafka server
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP}

# Consumer ID
spring.kafka.consumer.group-id=vms-status-publication

# Default serialization types
spring.kafka.consumer.properties.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.producer.properties.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer




## --------------------------------------------------------------------------
## Actuator
## --------------------------------------------------------------------------
management.endpoints.web.exposure.include=health
management.endpoints.web.exposure.exclude=shutdown
management.endpoint.metrics.enabled=true
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
