server.port=4783

# Port of SOAP service
de.heuboe.by.c2vba.datex2.mst.localisation.servicePort=5711

# URL of WLS
de.heuboe.by.c2vba.datex2.mst.localisation.wlsUrl=http://localhost:8087/WebLocationServerSrv?wsdl


de.heuboe.by.c2vba.datex2.mst.localisation.addOpenLRLocation=true

# gRPC config service connection
grpc.client.ConfigService.address=dns:///worker1.d.c2vba.heuboe.hbintern:31100
#grpc.client.ConfigService.address=dns:///hannahn-wx:9090
grpc.client.ConfigService.maxInboundMessageSize=30000000
grpc.client.ConfigService.negotiationType=PLAINTEXT


de.heuboe.by.c2vba.datex2.mst.localisation.system=ABDS

##
## Kafka
##

## Connection
spring.kafka.bootstrap-servers=master1.d.c2vba.heuboe.hbintern:32002
#spring.kafka.bootstrap-servers=kafka1.d.uz.komodnext.heuboe.hbintern:9092

# Consumer ID
spring.kafka.consumer.group-id=c2vba-datex2-mst-localisation-ps-test

# Topic LVE Betriebsparameter
de.heuboe.by.c2vba.datex2.mst.localisation.lveBetriebsparameterTopic=C2VBA-tlsin-LVEBetriebsparameter

# Topic UFD Betriebsparameter
de.heuboe.by.c2vba.datex2.mst.localisation.ufdBetriebsparameterTopic=C2VBA-tlsin-UFDBetriebsparameter

