###########################################################################
#
# Makefile fuer die neue gemeinsame Produktionsumgebug mit Ronalds makefile
#
# Voraussetzungen : 
#
# Die Shellvariablen
#
###########################################################################
#
#
#----let global make know which targets are supported-----
all:
proto:
#link:
#clean:

###########################################################################
#
#
############# Flags:

ddl = d2MSTSupply.ddl

include ${MMDIR}/stddepl
