# General settings
proxyHost=www-proxy
proxyPort=8000

# WLS web service settings
wls.protocol=http
wls.port:8085
wls.beans.xml=classpath:wls-beans.xml
#wls.jaxbContext=de.heuboe.wls.data.wls:de.heuboe.wls.data.roadmap:de.heuboe.wls.data.linref:de.heuboe.wls.data.tcc:de.heuboe.wls.data.sdbby:de.heuboe.wls.data.tmc

wls.persistence.host=he3-w7v
wls.persistence.database=wlsSdbbyTestps
wls.system.version=4.1

#map.pathname=map/VIB_P12_LuD_v22_NT2012Q4_link.SHP
#map.srid=31464
#map.pathname=map/Feinnetz_link.shp
map.pathname=map/Feinnetz_link.shp
map.srid=32632

vms.filename=map/KonfTab_Fischbach.txt;map/KonfTab_Freimann.txt
www.filename=map/www_v0.9.txt
sdb.filename=map/StrategieDefinition_v0.14.txt

# OpenLR settings
openLR.encoder.config=openLR-encoder.xml
openLR.decoder.config=openLR-decoder.xml

tmc.roadnet.files=map/Feinnetz_link.shp
tmc.filename=map/LCL15.1.D-160122.csv
tmc.version=D01:15.1

q.sued.filename=map/C2VBA-Q-Suedbayern.csv
q.nord.filename=map/C2VBA-Q-Nordbayern.csv

# WLS service settings
wls.srid=32632
wls.poolSize=10


