---
apiVersion: v1
kind: Service
metadata:
  name: site-config-service
spec:
  ports:
  - name: actuator
    nodePort: 31012
    port: 80
    protocol: TCP
    targetPort: actuator
  - name: grpclb
    nodePort: 31013
    port: 9090
    protocol: TCP
    targetPort: grpc
  selector:
    app: site-config-service
  type: NodePort
