server.port=8080

##
## Kafka
##

## Connection
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP}

# Consumer group ID
spring.kafka.consumer.group-id=c2vba-datex2-join-fg1

# Default serialization types
spring.kafka.consumer.properties.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.producer.properties.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer

# Topics with DATEX-II VMS-Publications
de.heuboe.c2vba.datex2.join.topicSued = C2VBA-datex2-publication-mdp-fg1-sued
de.heuboe.c2vba.datex2.join.topicNord = C2VBA-datex2-publication-mdp-fg1-nord


# VMS table ID and version
de.heuboe.c2vba.datex2.join.tableId = D2-C2VBA-LVE-Table
de.heuboe.c2vba.datex2.join.tableVersion = ${NORD-SUED-MST-FG1-VERSION}

# Interval of additional cyclic snapshot publications
de.heuboe.c2vba.datex2.join.pubInterval= 60

de.heuboe.c2vba.datex2.join.pubMode=CyclicSnapshot

# Each sent publication is saved as XML file in 'pubFileDir'
de.heuboe.c2vba.datex2.join.pubFileDir = /files/pub


#
# MDM connection parameter
#

de.heuboe.datex2.remote=SOAP
de.heuboe.datex2.vms.status.pub.receiverType=MDM

de.heuboe.datex2.connection.useGzip=true
de.heuboe.datex2.connection.disableCNCheck=true


#de.heuboe.datex2.connection.url=http://sdbby-2k19:5717/D2PushReceiver


de.heuboe.datex2.connection.url=${FG1-NORD-SUED-URL}
de.heuboe.datex2.connection.trustStoreFile=/mdm-certs/${MDM_PUBLIC_CERT_FILE}
de.heuboe.datex2.connection.trustStorePassword=${MDM_PUBLIC_CERT_PW}
de.heuboe.datex2.connection.keyStoreFile=/mdm-certs/${SYSTEM_PRIVATE_KEY_FILE}
de.heuboe.datex2.connection.keyStorePassword=${SYSTEM_PRIVATE_KEY_PW}





## --------------------------------------------------------------------------
## Actuator
## --------------------------------------------------------------------------
management.endpoints.web.exposure.include=health
management.endpoints.web.exposure.exclude=shutdown
management.endpoint.metrics.enabled=true
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true