## +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
##
##  VMIS2-gRPC-Template-Project
##
## This file provides a list of all custom application properties. The
## properties are listed with a possible default value, a hint which values
## might be allowed and a short description what the properties are used for.
##
## The file is intended as a template for custom property files
## of this application, which are then used in specific environments.
##
## All properties that have no default value or need to be overridden
## can be specified either
##   - within a custom property file ('-Dspring.config.location=file:<path>')
##   - by using system properties (-D<property>=<value>)
##   - application parameters (--<property>=<value>).
##
## See: Spring Boot Reference Guide - Externalized Configuration
## http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config
## +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-

# The url to the host this service connects to to share its data
grpc.client.ExternalServer.address=