---
apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  ports:
  - name: actuator
    nodePort: 31101
    port: 80
    protocol: TCP
    targetPort: actuator
  - name: grpclb
    nodePort: 31100
    port: 9090
    protocol: TCP
    targetPort: grpc
  selector:
    app: config-service
  type: NodePort
