{
  "id" : "DE-10058.M",
  "name" : "DE-10058.M",
  "elements" : [ {
    "id" : "DE921121357_1",
    "length" : 108.1836355987752,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921121358_1",
    "length" : 150.70793388277755,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1202902227_1",
    "length" : 295.85213807372025,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1202902226_2",
    "length" : 158.32423815523163,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1232629871_2",
    "length" : 81.02000229457785,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1232629870_2",
    "length" : 36.41839939652372,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554340632_2",
    "length" : 78.34467316753774,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554340631_2",
    "length" : 170.79430302761324,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE769313392_2",
    "length" : 260.84418182486615,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225525829_2",
    "length" : 40.85304820227459,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225525828_2",
    "length" : 82.38583143984525,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225525831_2",
    "length" : 218.18572437904047,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225525830_2",
    "length" : 177.6397419800964,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243330225_2",
    "length" : 23.765342631109654,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1269028722_2",
    "length" : 217.71967855281017,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1269028721_2",
    "length" : 32.441947971766396,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819417613_2",
    "length" : 60.01260781259715,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  } ],
  "direction" : "POSITIVE",
  "firstOffset" : 49.0,
  "lastOffset" : 19.0,
  "length" : 2103.480820578566
}