{
  "id" : "DE-10057.M",
  "name" : "DE-10057.M",
  "elements" : [ {
    "id" : "DE783176667_1",
    "length" : 74.57873035722724,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921185694_1",
    "length" : 51.79646908253718,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921185695_1",
    "length" : 81.11995732666085,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243395361_1",
    "length" : 170.19672157202194,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243395362_1",
    "length" : 3.4176870836230964,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1240787804_1",
    "length" : 28.04764463152857,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1240787805_1",
    "length" : 295.03678083716295,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1175260664_1",
    "length" : 51.345053267449885,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225311074_1",
    "length" : 321.7256357135833,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1240787806_1",
    "length" : 276.1396037722269,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1240787807_1",
    "length" : 39.104320764040835,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1240787808_1",
    "length" : 367.40143590643794,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783166463_1",
    "length" : 133.29876858264205,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783166464_1",
    "length" : 104.06060888810376,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1240787809_1",
    "length" : 62.57393679209153,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1240787810_1",
    "length" : 132.6684110568277,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1240787811_1",
    "length" : 86.86805485519352,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1224306592_1",
    "length" : 142.75869036344884,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554340515_1",
    "length" : 151.04819218173705,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1226728096_1",
    "length" : 37.195006322005824,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1226728097_1",
    "length" : 49.82132952578101,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819419447_1",
    "length" : 33.46726679798211,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1273202658_1",
    "length" : 70.65277807475172,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1273202659_1",
    "length" : 58.03066755717697,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819417882_1",
    "length" : 28.333047853514188,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1087967383_1",
    "length" : 35.834601879225794,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1087967384_1",
    "length" : 105.41995181703042,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1104721720_1",
    "length" : 35.56665624903555,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1104721721_1",
    "length" : 142.81595214126114,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243535034_1",
    "length" : 92.89477062420227,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE769313388_1",
    "length" : 157.82412623698124,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE769313389_1",
    "length" : 187.76223233782974,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE769313390_1",
    "length" : 52.78463038500516,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562763528_1",
    "length" : 362.5987822096865,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554340528_1",
    "length" : 105.5141901975035,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  } ],
  "direction" : "POSITIVE",
  "firstOffset" : 64.0,
  "lastOffset" : 22.0,
  "length" : 3982.188503046014
}