{
  "id" : "DE-10038.M",
  "name" : "DE-10038.M",
  "elements" : [ {
    "id" : "DE921718858_2",
    "length" : 166.24473791453119,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193221416_2",
    "length" : 41.95940694755492,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193221418_2",
    "length" : 34.72171072275556,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280584277_2",
    "length" : 93.08720116180432,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280584276_2",
    "length" : 188.20068512723162,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193221419_2",
    "length" : 53.28537997901841,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193221421_2",
    "length" : 344.38605283117585,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297031721_2",
    "length" : 185.77168465469725,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297031720_1",
    "length" : 93.23400780853217,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE923629332_1",
    "length" : 123.20475311449513,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE923629333_1",
    "length" : 155.15087421536396,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1310147784_1",
    "length" : 42.17890027720365,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1310147785_1",
    "length" : 26.914634634297492,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE67616031_1",
    "length" : 39.02395725495051,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268677402_1",
    "length" : 176.21737258721194,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268677403_1",
    "length" : 88.70980817165335,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE923629334_1",
    "length" : 95.75933460888052,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1282999528_1",
    "length" : 49.234026539998624,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1282999529_1",
    "length" : 29.39271664253261,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE722661825_1",
    "length" : 81.38553043353875,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1224579344_1",
    "length" : 118.4740886813283,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1277518083_1",
    "length" : 110.61747489131643,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1277518084_1",
    "length" : 37.31523618217555,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193221411_1",
    "length" : 26.097934795669723,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1277518085_1",
    "length" : 12.664630871335577,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1277518086_1",
    "length" : 40.98888842547283,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554336004_1",
    "length" : 56.6292661716698,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193221413_2",
    "length" : 312.19738373779353,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193221412_2",
    "length" : 92.38538740519758,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193221415_2",
    "length" : 52.163969495759545,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307550074_2",
    "length" : 67.80560184488883,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307550073_2",
    "length" : 87.91637785904919,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1308022488_1",
    "length" : 35.01410960494584,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1308022489_1",
    "length" : 42.463926767093646,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307550076_1",
    "length" : 109.51226563154978,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1296725947_1",
    "length" : 260.7632487425825,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1258894991_1",
    "length" : 252.31926130572361,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554336008_1",
    "length" : 184.19752297409877,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  } ],
  "direction" : "POSITIVE",
  "firstOffset" : 74.0,
  "lastOffset" : 5.0,
  "length" : 3754.39182804098
}