{
  "id" : "DE-10043.M",
  "name" : "DE-10043.M",
  "elements" : [ {
    "id" : "DE1216088347_2",
    "length" : 76.46580014573162,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1216088346_2",
    "length" : 20.9657011525792,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297042848_2",
    "length" : 85.88308424276266,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297042850_2",
    "length" : 192.270885446332,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297042849_2",
    "length" : 101.25906007981801,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297042851_1",
    "length" : 90.12146901358102,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297042852_1",
    "length" : 89.3530326515974,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE717769071_2",
    "length" : 245.86623614835935,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307876104_2",
    "length" : 83.57282834079452,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307876103_2",
    "length" : 132.2839933178557,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307876102_2",
    "length" : 91.11826946170265,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307876101_2",
    "length" : 32.886052495824266,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289537277_2",
    "length" : 67.99907412845643,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1308007830_2",
    "length" : 462.5755785948775,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1308007829_2",
    "length" : 86.81267668029503,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289537280_2",
    "length" : 453.0729878916098,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  } ],
  "direction" : "POSITIVE",
  "firstOffset" : 50.99999999999999,
  "lastOffset" : 323.0,
  "length" : 2131.433741900567
}