# Spring: HTTP access to actuator data
server.port=8080

# Publication mode: Possible values: CyclicComplete, CyclicOnChangeComplete, OnUpdate, or OnUpdateCyclicSnapshot
de.heuboe.sdbby.srp.publicationMode=CyclicOnChangeComplete

# Publication interval (seconds)
de.heuboe.sdbby.srp.pubInterval=300

# Only used with publicationMode = OnUpdateCyclicSnapshot: checks for changes in active strategies are executed each <checkInterval> ms
de.heuboe.sdbby.srp.checkInterval=5000

# Folder with XML files of generated DATEX-II publications
de.heuboe.sdbby.srp.fileDir=/files/pub

de.heuboe.sdbby.srp.datex2Sender=${MDM_BY_ORGA_KEY}

# WLS address
de.heuboe.sdbby.srp.wlsUrl=http://wls-project-sdbby.c2vba.svc:82/WebLocationServerSrv

# Address of sdbby service (provides currently active strategies)
de.heuboe.sdbby.srp.sdbbyUrl=http://sdbby-service.c2vba.svc:8123/SdbbyService

# DATEX-II publication target (attribute in 
de.heuboe.sdbby.srp.datex2Target=MDM

# Schema of DATEX-II publications
de.heuboe.sdbby.srp.d2SchemaLocation=http://62.132.115.147:11447/d2Schema/StrategicRouting.xsd

# MDM connection parameters
#de.heuboe.sdbby.srp.mdmAuthenticationFile=/files/cert/mdmAuth.properties

#true: converts OpenlrExtendedLinear elements so that they are valid with the original StrategicRouting.xsd 
#      ( 'firstDirection' sub elements are renamed: --> 'openlrLineLocationReference' )
de.heuboe.sdbby.srp.convert2BaseSchema=true


de.heuboe.datex2.remote=SOAP
de.heuboe.datex2.vms.status.pub.receiverType=MDM
de.heuboe.datex2.connection.url=http://c2vba-datex2-region-receiver.c2vba.svc:82/c2vba/srp/services/supplierPushService-srp-sued

#de.heuboe.datex2.connection.url=https://broker.mdm-portal.de/BASt-MDM-Interface/srv/3513001/supplierPushService
#de.heuboe.datex2.connection.trustStoreFile=/mdm-certs/mdm-sectigo-2029.jks
#de.heuboe.datex2.connection.trustStorePassword=${MDM_PUBLIC_CERT_PW}
#de.heuboe.datex2.connection.keyStoreFile=/mdm-certs/vzh.heuboe.de.p12
#de.heuboe.datex2.connection.keyStorePassword=${HB_PRIVATE_KEY_PW}

de.heuboe.datex2.connection.useGzip=true

de.heuboe.sdbby.srp.strategyRuleFile=/strategie-files/rules/StrategieRegeln_v0.20.txt

de.heuboe.sdbby.srp.routeEncoding=openLR

##
## Kafka
##

## Connection
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP}

# Consumer ID
de.heuboe.sdbby.srp.consumerGroupId=strategic-routing-publication

# Default serialization types
spring.kafka.consumer.properties.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.producer.properties.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer


de.heuboe.sdbby.srp.strategyStatesTopic = C2VBA-StrategyStates



## --------------------------------------------------------------------------
## Actuator
## --------------------------------------------------------------------------
management.endpoints.web.exposure.include=health
management.endpoints.web.exposure.exclude=shutdown
management.endpoint.metrics.enabled=true
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
