{
  "id" : "DE-10210.M",
  "name" : "DE-10210.M",
  "elements" : [ {
    "id" : "DE783184495_1",
    "length" : 140.43268101149098,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244147353_1",
    "length" : 106.18371945967806,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244147354_1",
    "length" : 45.4607997532685,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172804231_1",
    "length" : 26.2029041663383,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172804233_1",
    "length" : 23.88640959803149,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244147358_1",
    "length" : 114.18376528301246,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244147359_1",
    "length" : 61.71124532613067,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172805821_1",
    "length" : 35.5176904089818,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172805819_1",
    "length" : 89.24108914381182,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921114732_1",
    "length" : 237.51355927592482,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268360875_1",
    "length" : 210.5275860736588,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1296919227_1",
    "length" : 631.5179491721967,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1272298966_1",
    "length" : 27.18945349967763,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244151144_1",
    "length" : 41.80908440683743,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244151146_1",
    "length" : 351.569223565745,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244151147_1",
    "length" : 106.79586587933792,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819398642_1",
    "length" : 52.272394227473754,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819398643_1",
    "length" : 149.0769514290646,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562821813_1",
    "length" : 207.56716069403782,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921114733_1",
    "length" : 134.8488302445506,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921114734_1",
    "length" : 98.37440354922725,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562818735_1",
    "length" : 840.6016129896096,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562818736_1",
    "length" : 1259.960455929358,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1239664723_1",
    "length" : 2072.664105388086,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1239664724_1",
    "length" : 35.483989300783634,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1239664725_1",
    "length" : 75.79465604109912,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819397796_1",
    "length" : 220.8367687742795,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819397797_1",
    "length" : 491.96427152683765,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819397688_1",
    "length" : 530.6061872436206,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819395971_1",
    "length" : 121.03284273417218,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE52819391_1",
    "length" : 53.77844870032832,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE67617489_1",
    "length" : 58.03517406714927,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE67617490_1",
    "length" : 145.7290575029467,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE67617516_1",
    "length" : 57.44011691901994,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1126069210_1",
    "length" : 107.5820050054669,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1126069211_1",
    "length" : 203.80176177303542,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1239961188_1",
    "length" : 1039.462881154568,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1267485531_1",
    "length" : 182.79025317360794,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1267485532_1",
    "length" : 74.7102392065651,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562818743_1",
    "length" : 850.4924950036984,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1239961173_1",
    "length" : 119.81308675482029,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1239967668_1",
    "length" : 24.700861545754325,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1239967669_1",
    "length" : 84.57858130930643,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1181518691_1",
    "length" : 104.36430452792717,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE576294312_1",
    "length" : 101.94967275215791,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE722911567_1",
    "length" : 57.4731015104353,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE722911568_1",
    "length" : 102.44488206588326,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554332763_1",
    "length" : 156.23332775982328,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554332761_1",
    "length" : 34.63588236597244,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE52913394_1",
    "length" : 189.65256390598827,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE854734216_1",
    "length" : 72.86030657378251,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE854734217_1",
    "length" : 134.0332826995123,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244447400_1",
    "length" : 57.46882460999082,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244447399_2",
    "length" : 77.12199534809568,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1224047863_2",
    "length" : 143.23369113664384,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1126395643_1",
    "length" : 22.894375362496454,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1217360733_1",
    "length" : 170.85959146146706,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1217360734_1",
    "length" : 20.30759551053838,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE854734196_1",
    "length" : 33.32256054984101,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE52913376_1",
    "length" : 185.61862279991482,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE64465309_1",
    "length" : 36.967911188580246,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE854710925_1",
    "length" : 14.3188086388387,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979642931_1",
    "length" : 168.4292320148012,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1126565789_1",
    "length" : 33.32157216975293,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1126565790_1",
    "length" : 178.00081835071688,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE64465322_1",
    "length" : 67.19056246834249,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783093340_1",
    "length" : 24.991034165173968,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783093341_1",
    "length" : 13.016586166340923,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1074070974_1",
    "length" : 61.69699775205626,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1210729848_1",
    "length" : 68.47287744774654,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1210729849_1",
    "length" : 135.40632366341288,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1126385243_1",
    "length" : 51.577872445926694,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1126385244_1",
    "length" : 167.51526485665687,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244452152_1",
    "length" : 40.09708138953878,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244452153_1",
    "length" : 182.7819909568648,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225297302_1",
    "length" : 41.65323997225665,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225297303_1",
    "length" : 26.04301441816296,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562821934_1",
    "length" : 104.9161407147071,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1181633856_1",
    "length" : 132.24450046007993,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1181633857_1",
    "length" : 23.689162522645212,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244433599_1",
    "length" : 33.32060832030944,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244433600_1",
    "length" : 36.96660629018257,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1198227516_1",
    "length" : 111.44446991058041,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1181588761_1",
    "length" : 17.70383314237299,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE67618368_1",
    "length" : 101.00126690956779,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE67618369_1",
    "length" : 627.3622158191233,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554326496_1",
    "length" : 38.01742091245737,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1181597677_1",
    "length" : 48.67785919953192,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1181597678_1",
    "length" : 57.00745150215464,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1210771281_1",
    "length" : 21.345414465627503,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1210771282_1",
    "length" : 38.00491314692621,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225281125_1",
    "length" : 35.66226418670316,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225281126_1",
    "length" : 98.92086805394776,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1210771280_1",
    "length" : 28.63583560114798,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979633792_1",
    "length" : 1133.3244782195195,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  } ],
  "direction" : "POSITIVE",
  "firstOffset" : 121.0,
  "lastOffset" : 29.000000000000004,
  "length" : 15982.619218376298
}