{
  "id" : "DE-10061.M",
  "name" : "DE-10061.M",
  "elements" : [ {
    "id" : "DE979543736_1",
    "length" : 163.08842996695427,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921185693_1",
    "length" : 68.52492678306362,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586909525_1",
    "length" : 278.162031508335,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1283298482_1",
    "length" : 143.01913268882257,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1283298483_1",
    "length" : 100.21633227555758,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1263986936_1",
    "length" : 164.3383540705232,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1263986937_1",
    "length" : 150.98019594426802,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297211153_1",
    "length" : 410.75428255873305,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297211154_1",
    "length" : 562.7963642933187,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297211155_1",
    "length" : 195.85796372155994,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1187629179_1",
    "length" : 307.07671001612863,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1246714185_1",
    "length" : 105.2766905073147,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1194232583_1",
    "length" : 170.38434761354029,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1194232584_1",
    "length" : 66.95219591293058,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783176682_1",
    "length" : 20.215574411849783,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307527713_1",
    "length" : 94.29028947075199,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307527714_1",
    "length" : 13.91555694000963,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  } ],
  "direction" : "POSITIVE",
  "firstOffset" : 79.0,
  "lastOffset" : 13.0,
  "length" : 2935.9338217436516
}