{
  "id" : "DE-10203.M",
  "name" : "DE-10203.M",
  "elements" : [ {
    "id" : "DE770438838_2",
    "length" : 123.71346998733611,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920963266_2",
    "length" : 52.597690236704764,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172530961_2",
    "length" : 134.12632314374065,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172530960_2",
    "length" : 37.53166682701108,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172530959_2",
    "length" : 21.616767881582454,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172530958_2",
    "length" : 394.69576701142887,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586918817_2",
    "length" : 217.68962585057875,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783165143_2",
    "length" : 53.90242978567913,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE792404811_2",
    "length" : 112.99148636274228,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE792404810_2",
    "length" : 72.90375521836158,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE52819377_2",
    "length" : 185.39483222300152,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562821927_2",
    "length" : 50.2592833895453,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783165137_2",
    "length" : 88.53192934592406,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920963264_2",
    "length" : 80.20076465267744,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920963263_2",
    "length" : 85.65235507349797,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586918736_2",
    "length" : 190.0755560704288,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562821915_2",
    "length" : 904.3386667791133,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920963268_2",
    "length" : 748.34504291647,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920963267_2",
    "length" : 186.88829283355602,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586918740_2",
    "length" : 262.24424329677265,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586918739_2",
    "length" : 148.04693266572255,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289720615_2",
    "length" : 26.099388005699293,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289720614_2",
    "length" : 128.7881399295029,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920963269_2",
    "length" : 167.63264233079357,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586899977_2",
    "length" : 262.0843082008861,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085151077_2",
    "length" : 89.02620915964343,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085151076_2",
    "length" : 201.05871854565433,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE52819367_2",
    "length" : 226.81943793006874,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085140672_2",
    "length" : 24.096348665246047,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085140671_2",
    "length" : 79.69477182367707,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920987545_2",
    "length" : 46.60407084774454,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085140674_2",
    "length" : 26.099601649502958,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085140673_2",
    "length" : 119.46553471512374,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554329925_2",
    "length" : 287.6337778518552,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE774036239_2",
    "length" : 600.0204840700684,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE774036238_2",
    "length" : 337.88818374233523,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920987547_2",
    "length" : 99.77190816168144,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085146391_2",
    "length" : 23.447942324389523,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1181838295_2",
    "length" : 22.395942572493208,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1181838294_2",
    "length" : 56.51474450288122,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1181400492_2",
    "length" : 130.01927130370694,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783091736_2",
    "length" : 109.97275005590372,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE52913978_2",
    "length" : 163.08215269257036,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920987549_2",
    "length" : 191.22029934596648,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920987548_2",
    "length" : 96.61840921742125,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586899978_2",
    "length" : 76.57239852763965,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586899979_2",
    "length" : 134.71111651259395,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE67617551_2",
    "length" : 199.31054711529453,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783091731_2",
    "length" : 85.70485343662067,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1282616693_2",
    "length" : 65.6554390299713,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1282616692_2",
    "length" : 172.70456141676718,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1282616695_2",
    "length" : 308.2326307817618,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1282616694_2",
    "length" : 106.80920350048876,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783176709_2",
    "length" : 74.80341086440247,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225251810_2",
    "length" : 76.32649548855653,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225251809_2",
    "length" : 79.27467132967121,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562822077_2",
    "length" : 279.6393854545781,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562774091_2",
    "length" : 89.10527572555714,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE770438842_2",
    "length" : 65.65658996975965,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE770438841_2",
    "length" : 76.09321140566345,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE576294321_2",
    "length" : 22.396871634075467,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1217501866_2",
    "length" : 18.759062595663067,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243926822_2",
    "length" : 75.03629957242232,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243926821_2",
    "length" : 188.88159421669496,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE52798431_2",
    "length" : 370.02908365894973,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE67625843_2",
    "length" : 172.70959365248257,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920987551_2",
    "length" : 48.189702056691836,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281265724_2",
    "length" : 68.00245547299622,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281265723_2",
    "length" : 22.397208209589703,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554330034_2",
    "length" : 125.57135361838245,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586900047_2",
    "length" : 264.97741630390635,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586900048_2",
    "length" : 240.23789464165185,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297233637_2",
    "length" : 33.88561589689292,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297233636_2",
    "length" : 38.81083387070059,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244180680_2",
    "length" : 45.609868703488445,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  } ],
  "direction" : "POSITIVE",
  "firstOffset" : 55.0,
  "lastOffset" : 33.00000000000001,
  "length" : 11226.28669515712
}