{
  "id" : "DE-10205.M",
  "name" : "DE-10205.M",
  "elements" : [ {
    "id" : "DE1225431497_2",
    "length" : 28.407983109435484,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1257156919_2",
    "length" : 48.17174306825555,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1257156918_2",
    "length" : 24.10293793555621,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1257160336_2",
    "length" : 81.51712286165083,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1257160335_2",
    "length" : 101.26627756955958,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1295738360_2",
    "length" : 1071.4413573574957,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1267485527_2",
    "length" : 163.7065216877755,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1239961187_2",
    "length" : 23.460317999013743,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1257157745_2",
    "length" : 513.8575208302312,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1257157744_2",
    "length" : 662.1047528036736,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920963279_2",
    "length" : 221.099172813175,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE67617492_2",
    "length" : 28.413274090255562,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE67617491_2",
    "length" : 127.95426806221033,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE67617488_2",
    "length" : 57.42951798140193,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE67617487_2",
    "length" : 51.264845769854496,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921114736_2",
    "length" : 64.84657637200006,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921114735_2",
    "length" : 203.80969686341749,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244761425_2",
    "length" : 1176.035060344272,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244761427_2",
    "length" : 32.346400816999946,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244761426_2",
    "length" : 1041.096211709536,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562818712_2",
    "length" : 2212.6157334052946,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562818715_2",
    "length" : 89.84488359076727,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819398173_2",
    "length" : 102.5846199341329,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297467498_2",
    "length" : 205.7015610806287,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297467497_2",
    "length" : 334.1339702688685,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819398174_2",
    "length" : 431.95253442747514,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  } ],
  "direction" : "POSITIVE",
  "firstOffset" : 22.0,
  "lastOffset" : 3.9999999999999996,
  "length" : 8649.212328325464
}