{
  "id" : "DE-10048.M",
  "name" : "DE-10048.M",
  "elements" : [ {
    "id" : "DE1244151148_2",
    "length" : 151.80324111865644,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921114723_2",
    "length" : 122.30648015801876,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244151151_2",
    "length" : 154.57889148088555,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1296668509_2",
    "length" : 330.48654591153206,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268360873_2",
    "length" : 301.3689927318843,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289402406_2",
    "length" : 10.955436773885197,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289402405_2",
    "length" : 80.3422296569455,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819399924_2",
    "length" : 404.36773418660255,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172805818_2",
    "length" : 45.460305438862335,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172805823_2",
    "length" : 37.82512819574978,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244147346_2",
    "length" : 65.70426238934246,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244147345_2",
    "length" : 22.556611507081723,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172804236_2",
    "length" : 88.89747305890111,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172804235_2",
    "length" : 51.41738260720874,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172804232_2",
    "length" : 22.90876716468465,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819400099_2",
    "length" : 18.914638591517825,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819400098_2",
    "length" : 76.31797014178261,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819400249_2",
    "length" : 28.52414351426954,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1257157747_2",
    "length" : 60.81791250269521,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1257157746_2",
    "length" : 72.40199125642708,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1254489889_2",
    "length" : 75.54449989223562,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819401799_2",
    "length" : 66.60745614764409,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819401798_2",
    "length" : 33.43709882344959,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1232629782_2",
    "length" : 48.94411127216311,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1232629781_2",
    "length" : 52.36073023728214,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236206396_2",
    "length" : 140.53994513084203,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236206398_2",
    "length" : 79.68754130127914,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236206397_2",
    "length" : 93.04531051407855,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1232630737_2",
    "length" : 112.79753597534317,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562818721_2",
    "length" : 113.9897106764461,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1226388422_2",
    "length" : 249.86731387571052,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243333073_2",
    "length" : 31.185991323696857,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243333072_2",
    "length" : 32.163112348598794,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1304795873_2",
    "length" : 29.012762035839607,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1304795872_2",
    "length" : 146.5224402130146,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783184485_2",
    "length" : 120.74526961626336,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921114730_2",
    "length" : 132.98446121594972,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921114729_2",
    "length" : 552.1547200556096,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236104533_2",
    "length" : 66.7667422000188,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236104535_2",
    "length" : 49.5503905500329,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236104534_2",
    "length" : 713.0550396455075,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236103365_2",
    "length" : 33.37692879190342,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236103364_2",
    "length" : 608.0721560565594,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243330436_2",
    "length" : 66.44463293314388,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243330435_2",
    "length" : 356.1153600466389,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819415968_2",
    "length" : 328.88954969452504,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819415967_2",
    "length" : 181.9873323155743,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819416166_2",
    "length" : 137.16621640584054,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819416165_2",
    "length" : 129.40595385771303,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1223766176_2",
    "length" : 74.82679450833427,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1223766175_2",
    "length" : 59.74795156583961,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562822187_2",
    "length" : 57.570616786078176,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE854232458_2",
    "length" : 18.878182040509703,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE854232457_2",
    "length" : 191.98184701775193,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562822181_2",
    "length" : 81.7570601420966,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921121355_1",
    "length" : 71.51579566758146,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1286505843_1",
    "length" : 85.95762614459369,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1286505844_1",
    "length" : 57.2445760514899,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562822203_1",
    "length" : 39.22020789287788,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783181645_1",
    "length" : 73.31875226591086,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921121357_1",
    "length" : 108.1836355987752,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921121358_1",
    "length" : 150.70793388277755,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1202902227_1",
    "length" : 295.85213807372025,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1202902226_2",
    "length" : 158.32423815523163,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1232629871_2",
    "length" : 81.02000229457785,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1232629870_2",
    "length" : 36.41839939652372,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554340632_2",
    "length" : 78.34467316753774,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554340631_2",
    "length" : 170.79430302761324,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE769313392_2",
    "length" : 260.84418182486615,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225525829_2",
    "length" : 40.85304820227459,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225525828_2",
    "length" : 82.38583143984525,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225525831_2",
    "length" : 218.18572437904047,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225525830_2",
    "length" : 177.6397419800964,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243330225_2",
    "length" : 23.765342631109654,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1269028722_2",
    "length" : 217.71967855281017,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1269028721_2",
    "length" : 32.441947971766396,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819417613_2",
    "length" : 60.01260781259715,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1267860546_2",
    "length" : 131.96576130081385,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1267860545_2",
    "length" : 20.84220061613738,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783166475_2",
    "length" : 86.34461847948498,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268139217_2",
    "length" : 79.56467231600207,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268139216_2",
    "length" : 24.554241954545624,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819421089_2",
    "length" : 21.584495790728948,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819421088_2",
    "length" : 155.54657760917132,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554340547_2",
    "length" : 214.77009340652614,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819422383_2",
    "length" : 145.90528271856485,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819422382_2",
    "length" : 84.26134840491795,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783166469_2",
    "length" : 69.95541431195079,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1240787791_1",
    "length" : 525.301455658306,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1240787792_1",
    "length" : 26.851109582535827,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1240787793_1",
    "length" : 23.889375702882855,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1240787794_1",
    "length" : 243.23481211387522,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE64429398_1",
    "length" : 139.53356259103717,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554340624_1",
    "length" : 341.00989597093326,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554340625_1",
    "length" : 1288.1795608444781,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243884946_1",
    "length" : 37.31300355839357,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243884947_1",
    "length" : 35.8339252361502,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236222219_1",
    "length" : 31.296487055887024,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236222220_1",
    "length" : 132.86795010089133,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236207835_1",
    "length" : 64.26846327976216,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236207836_1",
    "length" : 32.13410412618808,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236207831_1",
    "length" : 23.888278224784226,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236207832_1",
    "length" : 302.18366320394483,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819423688_1",
    "length" : 361.50936501472165,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281267519_1",
    "length" : 27.37877869772811,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281267520_1",
    "length" : 111.66430017435087,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819424429_1",
    "length" : 60.47947979838682,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819424430_1",
    "length" : 221.39495071752742,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783168801_1",
    "length" : 77.87023633311446,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1302038005_1",
    "length" : 43.647639511285384,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1302038006_1",
    "length" : 47.353777022886575,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285711605_1",
    "length" : 69.36724348424165,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285711606_1",
    "length" : 720.5459150087327,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268205518_1",
    "length" : 45.495228555779725,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285711607_1",
    "length" : 59.919199140855916,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285711608_1",
    "length" : 16.836477748952163,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285711609_1",
    "length" : 679.4440383081346,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285711610_1",
    "length" : 838.4401605897363,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285711611_1",
    "length" : 23.670299942336257,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285711612_1",
    "length" : 52.33276187037689,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819426554_1",
    "length" : 390.17375738987596,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819426906_1",
    "length" : 90.42041738556811,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172439848_1",
    "length" : 160.13995929273506,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172439849_1",
    "length" : 47.343394460218846,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172439850_1",
    "length" : 21.268182051859608,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172439851_1",
    "length" : 109.65708961199738,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819427147_1",
    "length" : 88.56867394570892,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819427496_1",
    "length" : 142.57615667632302,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819427497_1",
    "length" : 23.114051698970375,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE67616262_1",
    "length" : 35.502637904422606,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285711613_1",
    "length" : 34.94638786065312,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285711614_1",
    "length" : 43.65576792554375,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285711615_1",
    "length" : 46.77944016904599,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE52819290_1",
    "length" : 213.01217853238208,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE749447837_1",
    "length" : 42.34424442601497,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920330915_1",
    "length" : 108.76099019436825,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920330916_1",
    "length" : 108.04738624917913,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1218475661_1",
    "length" : 174.80105846285576,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1218475662_1",
    "length" : 913.9798576390957,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  } ],
  "direction" : "POSITIVE",
  "firstOffset" : 28.0,
  "lastOffset" : 855.0000000000001,
  "length" : 20384.431270329816
}