{
  "id" : "DE-10001.M",
  "name" : "DE-10001.M",
  "elements" : [ {
    "id" : "DE724162454_1",
    "length" : 129.77362141230725,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE812111265_1",
    "length" : 90.08912149903139,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE812111266_1",
    "length" : 191.31651341004397,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE812111267_1",
    "length" : 207.38166603265955,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE812111268_1",
    "length" : 728.1428201350772,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE812111269_1",
    "length" : 93.734383575733,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE812106544_1",
    "length" : 518.1732387577983,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE812106545_1",
    "length" : 193.62784890104487,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE812106541_1",
    "length" : 141.5847733304022,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979402541_1",
    "length" : 175.18635258413616,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1278222367_1",
    "length" : 40.27079596172106,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1278222368_1",
    "length" : 50.16714854598692,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE812106538_1",
    "length" : 364.9290138101599,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280714131_1",
    "length" : 286.95241923201695,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280714132_1",
    "length" : 19.031192449870936,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280715382_1",
    "length" : 45.674418758970276,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280715383_1",
    "length" : 104.57416678972163,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE812106534_1",
    "length" : 55.706835029310795,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE740429453_1",
    "length" : 86.0807232380981,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280392363_1",
    "length" : 541.9169134307177,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280392364_1",
    "length" : 4101.376468934874,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE812094661_2",
    "length" : 491.9209127702044,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE812094660_1",
    "length" : 67.33772860161773,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1278020339_1",
    "length" : 75.22660727418153,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1278020340_1",
    "length" : 259.5953130234647,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE812094657_1",
    "length" : 442.7572751915518,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979407960_1",
    "length" : 391.2015576683705,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979407962_1",
    "length" : 580.5681126194245,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979407961_2",
    "length" : 213.25042793107698,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1296670948_2",
    "length" : 446.7321443868293,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297339203_2",
    "length" : 84.37847461744342,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297339204_1",
    "length" : 2993.254259029382,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280714163_1",
    "length" : 97.04645521587169,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297382150_1",
    "length" : 386.24700922697485,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297382151_1",
    "length" : 30.98287714978421,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280714166_1",
    "length" : 49.69332987141721,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1282854861_2",
    "length" : 957.3106018922691,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1084539304_2",
    "length" : 49.69342511603154,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1084539303_2",
    "length" : 170.21871922497536,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE53041224_2",
    "length" : 210.17167242610907,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920439755_2",
    "length" : 149.0811095578822,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297338286_2",
    "length" : 839.2841215085512,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1255182122_1",
    "length" : 64.64501527826584,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1277973136_1",
    "length" : 33.87890966055712,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1277973137_1",
    "length" : 422.61328289955117,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1296669153_1",
    "length" : 155.50094044263085,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1254771410_1",
    "length" : 186.87245607938462,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297338079_1",
    "length" : 2493.700665194142,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920439740_1",
    "length" : 112.4305488784153,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE83491257_1",
    "length" : 88.32856450831721,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE53041195_1",
    "length" : 190.43879129054616,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1290033912_1",
    "length" : 81.57872411495975,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920439741_1",
    "length" : 80.22127816101235,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920439742_1",
    "length" : 24.44124864203218,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE67615297_1",
    "length" : 213.38441530874928,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE923732577_1",
    "length" : 193.74607283163624,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE923732578_2",
    "length" : 800.7593994549746,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225165101_2",
    "length" : 32.313662785784146,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297377758_2",
    "length" : 33.796610892574364,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297377759_1",
    "length" : 615.498449893052,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  } ],
  "direction" : "POSITIVE",
  "firstOffset" : 100.00000000000001,
  "lastOffset" : 272.0,
  "length" : 22532.293156546635
}