{
  "id" : "DE-10039.M",
  "name" : "DE-10039.M",
  "elements" : [ {
    "id" : "DE554336012_2",
    "length" : 104.31723318096027,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268676228_2",
    "length" : 25.32842684617669,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268676229_2",
    "length" : 53.636660013541274,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1277518090_2",
    "length" : 355.174360876756,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1277518089_2",
    "length" : 15.68351177909415,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1277518088_2",
    "length" : 15.064129200166844,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1277518087_2",
    "length" : 240.69655227049353,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193222671_2",
    "length" : 152.46610538116965,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193222670_2",
    "length" : 37.57133326451078,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554336015_2",
    "length" : 142.07063764948956,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554336020_2",
    "length" : 199.71568633361161,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1296725939_2",
    "length" : 497.19757088984164,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  } ],
  "direction" : "POSITIVE",
  "firstOffset" : 56.00000000000001,
  "lastOffset" : 482.0,
  "length" : 1767.7246367959704
}