{
  "id" : "DE-10059.M",
  "name" : "DE-10059.M",
  "elements" : [ {
    "id" : "DE1126526116_2",
    "length" : 84.87376118729904,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1126526115_2",
    "length" : 530.3440259706827,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285712765_2",
    "length" : 74.89092856038981,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285712767_2",
    "length" : 21.099964530949507,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285712766_2",
    "length" : 922.7618447234178,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE774028741_2",
    "length" : 269.26647569152897,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819426333_2",
    "length" : 114.66064328961497,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819426332_2",
    "length" : 203.25145525887774,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285712769_2",
    "length" : 23.11923272973995,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285712768_2",
    "length" : 65.46738194805909,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268205516_2",
    "length" : 42.35321048717581,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268189719_2",
    "length" : 121.50766578770752,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819426230_2",
    "length" : 40.50277902194319,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819426229_2",
    "length" : 297.9435334844157,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819426063_2",
    "length" : 104.68142419695832,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819426062_2",
    "length" : 122.80451242388101,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285716066_2",
    "length" : 42.355333122049316,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285716068_2",
    "length" : 24.96772683241212,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285716067_2",
    "length" : 24.239105866868744,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783168803_2",
    "length" : 58.62791392275609,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562819033_2",
    "length" : 248.20099742173826,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562819032_2",
    "length" : 153.88976047243986,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586917021_2",
    "length" : 96.73105685132509,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979535139_2",
    "length" : 251.3543287108708,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979535138_2",
    "length" : 120.41850929470252,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783168791_2",
    "length" : 97.28821323275957,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979535142_2",
    "length" : 106.37385040043432,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979535147_2",
    "length" : 38.85833599612676,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979535146_2",
    "length" : 557.2209270149476,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921201423_2",
    "length" : 625.6945593546654,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921201422_2",
    "length" : 78.73793581002488,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE771538491_2",
    "length" : 21.27692464063694,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285979331_2",
    "length" : 9.448591766947954,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285979330_2",
    "length" : 86.88672212382019,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586916877_2",
    "length" : 277.16281020634483,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586916876_2",
    "length" : 48.03572560634712,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921201425_2",
    "length" : 158.29423203786,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1279641025_2",
    "length" : 852.3297332912053,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1279641024_2",
    "length" : 36.48820824422745,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1279641023_2",
    "length" : 198.18661612258956,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586917023_2",
    "length" : 306.07108759502046,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1171369102_2",
    "length" : 63.527502895017214,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1171369101_2",
    "length" : 93.7194597326997,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783176671_2",
    "length" : 34.64961010517488,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1224998331_2",
    "length" : 121.43818445707147,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1224998330_2",
    "length" : 59.09041682040376,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979648898_2",
    "length" : 137.07188347442127,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586909449_2",
    "length" : 67.69273734449544,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562821784_2",
    "length" : 39.21163881476154,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562821800_2",
    "length" : 347.49025859266743,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979653914_2",
    "length" : 45.86828927332898,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979653913_2",
    "length" : 152.7866569703956,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE770371949_2",
    "length" : 77.30904483836282,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1308633503_2",
    "length" : 16.062975515236733,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1308633502_2",
    "length" : 35.75726198948371,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243333155_2",
    "length" : 12.92589564721813,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979653903_2",
    "length" : 40.256681598892044,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979653902_2",
    "length" : 110.09245991031662,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586909486_2",
    "length" : 98.0074364647127,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921179777_2",
    "length" : 41.552876956975595,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921179776_2",
    "length" : 27.319119338903498,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1232579452_2",
    "length" : 75.36071047820688,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1232579451_2",
    "length" : 176.20998455083634,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783176681_2",
    "length" : 91.37746342455162,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1246714184_2",
    "length" : 355.7399930531447,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297504704_2",
    "length" : 109.78095274054812,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297504703_2",
    "length" : 202.20012722867,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297504709_2",
    "length" : 356.347543334544,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297504708_2",
    "length" : 16.556294641250766,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297504705_2",
    "length" : 533.7678975332686,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297504707_2",
    "length" : 188.87020492540455,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297504706_2",
    "length" : 78.38895282243925,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586909530_2",
    "length" : 308.6462525045534,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979543734_2",
    "length" : 770.2101659513675,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289335229_2",
    "length" : 28.61610521658122,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979543737_2",
    "length" : 61.374539260015766,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586909533_2",
    "length" : 69.73603188993815,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1232579593_2",
    "length" : 33.56445806513514,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1232579592_2",
    "length" : 69.14480341576987,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979543731_2",
    "length" : 97.92592182568409,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979543730_2",
    "length" : 42.25296375207968,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE770372760_2",
    "length" : 255.10328981571175,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE770372759_2",
    "length" : 57.01736046076844,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1286082734_2",
    "length" : 16.19458340050572,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1286082733_2",
    "length" : 46.450174365322006,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281444941_2",
    "length" : 36.009653921847594,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281444943_2",
    "length" : 38.57847222981049,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281444942_2",
    "length" : 72.69678525235214,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783189138_2",
    "length" : 112.09947207583998,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586900380_2",
    "length" : 188.3259574667914,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586900387_2",
    "length" : 34.374138922905885,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243332024_2",
    "length" : 14.324031574930618,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243332023_2",
    "length" : 21.353525692807793,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243417434_2",
    "length" : 217.77543591016044,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783189137_2",
    "length" : 112.24968397636749,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783189136_2",
    "length" : 115.10155865989374,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1277771994_2",
    "length" : 187.5687937610743,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1286475858_2",
    "length" : 39.883939139294974,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1286475857_2",
    "length" : 34.37464951600274,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783402371_2",
    "length" : 90.6304710778897,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586900497_2",
    "length" : 13.020993506811696,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE576321100_2",
    "length" : 267.0034606255844,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1286475863_2",
    "length" : 116.66043341261958,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1286475862_2",
    "length" : 353.45454022618,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE576320869_2",
    "length" : 28.649047215577784,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1308028199_2",
    "length" : 38.56638250525181,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1308028198_2",
    "length" : 212.1381160098438,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE576323041_2",
    "length" : 16.61349116420032,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783402366_2",
    "length" : 69.32594768050396,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783402365_2",
    "length" : 27.693621834712555,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920982153_2",
    "length" : 116.38900490917229,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1081686702_2",
    "length" : 71.76893571857048,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1081686701_2",
    "length" : 368.98918992491394,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920982155_2",
    "length" : 112.8958527503455,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920982154_2",
    "length" : 154.2779457820638,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562821435_2",
    "length" : 82.43156932353537,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562821434_2",
    "length" : 64.00818533794803,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE576295147_2",
    "length" : 56.68889629722353,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE576295146_2",
    "length" : 261.6906195927937,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1191965655_2",
    "length" : 20.965669744134832,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1216088347_2",
    "length" : 76.46580014573162,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1216088346_2",
    "length" : 20.9657011525792,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297042848_2",
    "length" : 85.88308424276266,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297042850_2",
    "length" : 192.270885446332,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297042849_2",
    "length" : 101.25906007981801,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297042851_1",
    "length" : 90.12146901358102,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297042852_1",
    "length" : 89.3530326515974,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE717769071_2",
    "length" : 245.86623614835935,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307876104_2",
    "length" : 83.57282834079452,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307876103_2",
    "length" : 132.2839933178557,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307876102_2",
    "length" : 91.11826946170265,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307876101_2",
    "length" : 32.886052495824266,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289537277_2",
    "length" : 67.99907412845643,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1308007830_2",
    "length" : 462.5755785948775,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1308007829_2",
    "length" : 86.81267668029503,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289537280_2",
    "length" : 453.0729878916098,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289537279_2",
    "length" : 44.65101545547799,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1296355422_2",
    "length" : 150.0407875586297,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1296355421_2",
    "length" : 62.78091968373521,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979411871_2",
    "length" : 80.236109486237,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1301890571_2",
    "length" : 32.43911093507565,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1301890570_2",
    "length" : 33.10745721696432,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920982160_2",
    "length" : 172.13161334520387,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1301890575_2",
    "length" : 243.40044842341226,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1301890574_2",
    "length" : 54.10675591736758,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285625094_2",
    "length" : 34.993037021366334,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554338630_2",
    "length" : 84.34843434915186,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE52921790_2",
    "length" : 35.46700697956462,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921715200_2",
    "length" : 55.48889102972839,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289956856_2",
    "length" : 92.8156371991036,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1296355420_2",
    "length" : 1253.6154115361471,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1296355419_2",
    "length" : 105.84925015898126,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297290685_2",
    "length" : 298.0527022974374,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1285625092_2",
    "length" : 234.55856064882587,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268288265_2",
    "length" : 63.55499058678613,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1296263302_2",
    "length" : 69.988648171266,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1296263301_2",
    "length" : 32.94204101429609,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1255250314_2",
    "length" : 173.30418177647144,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1255250313_2",
    "length" : 181.0227868706781,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1287350408_2",
    "length" : 26.814079154860288,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1287350409_2",
    "length" : 57.35232574992493,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268299935_2",
    "length" : 49.159125274601706,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268299934_2",
    "length" : 19.36571320907521,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1088338733_1",
    "length" : 38.00285213863368,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1287350411_2",
    "length" : 185.53570456594406,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289693930_2",
    "length" : 269.07355430477105,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289693929_2",
    "length" : 190.10279343873245,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289537263_2",
    "length" : 31.104229758181383,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289956220_2",
    "length" : 50.589345126067144,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289537255_2",
    "length" : 42.43612176440608,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1183005052_2",
    "length" : 86.67099973612363,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1183005051_2",
    "length" : 24.05100715284979,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921715205_2",
    "length" : 61.51479492641981,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289592076_2",
    "length" : 65.70200924373833,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307984192_2",
    "length" : 15.546969351784188,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307984191_2",
    "length" : 25.783274070875112,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289956224_2",
    "length" : 297.7566086099102,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289956223_2",
    "length" : 59.15439586431849,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225155555_2",
    "length" : 68.87816877997223,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289592078_2",
    "length" : 59.513708377122526,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289592077_2",
    "length" : 220.52820038862654,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783093333_2",
    "length" : 129.10404040876708,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783093332_2",
    "length" : 126.6603510706098,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1301890939_1",
    "length" : 37.31196679188348,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1301890940_2",
    "length" : 8.938534240941111,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE67615940_1",
    "length" : 151.33111974462912,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268465528_1",
    "length" : 33.97726838920857,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268465529_1",
    "length" : 63.97615436811671,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289537275_1",
    "length" : 37.32454550903937,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289956221_1",
    "length" : 25.20157673308891,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289956222_1",
    "length" : 25.2015508973041,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268299936_1",
    "length" : 39.75039796308815,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE772852737_1",
    "length" : 77.84817510057877,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562774139_1",
    "length" : 565.2806640408255,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE64484119_2",
    "length" : 808.393078829954,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281267415_1",
    "length" : 79.73721360594953,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281740652_2",
    "length" : 499.6558416401852,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281740653_1",
    "length" : 499.69873915790464,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281281792_1",
    "length" : 225.26753115064287,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281267444_2",
    "length" : 15.681679824896282,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281267443_2",
    "length" : 455.8802654925027,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281267446_2",
    "length" : 44.443383713459795,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281267494_2",
    "length" : 71.22779776179806,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281267493_2",
    "length" : 759.9043707425039,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921715208_2",
    "length" : 54.77303495193742,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921715207_2",
    "length" : 27.457395082926446,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE67615970_2",
    "length" : 93.0382177389029,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562821470_2",
    "length" : 62.18208256404842,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE64424982_2",
    "length" : 302.91568334570746,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554336012_2",
    "length" : 104.31723318096027,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268676228_2",
    "length" : 25.32842684617669,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268676229_2",
    "length" : 53.636660013541274,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1277518090_2",
    "length" : 355.174360876756,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1277518089_2",
    "length" : 15.68351177909415,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1277518088_2",
    "length" : 15.064129200166844,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1277518087_2",
    "length" : 240.69655227049353,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193222671_2",
    "length" : 152.46610538116965,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193222670_2",
    "length" : 37.57133326451078,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554336015_2",
    "length" : 142.07063764948956,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554336020_2",
    "length" : 199.71568633361161,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1296725939_2",
    "length" : 497.19757088984164,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307550078_1",
    "length" : 112.4974995229587,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307550079_1",
    "length" : 81.95531256264455,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921718863_1",
    "length" : 56.62934857244153,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307550080_1",
    "length" : 23.865245043147695,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307550081_1",
    "length" : 198.19026790919187,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193222673_1",
    "length" : 227.24402049544503,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193222674_2",
    "length" : 172.85487312522656,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE960707378_2",
    "length" : 37.27010539702564,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE960707377_2",
    "length" : 24.609365150732902,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1308029368_2",
    "length" : 182.29286505041395,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1308029367_2",
    "length" : 190.97020373141078,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE67616029_2",
    "length" : 150.55578501672886,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE67616032_2",
    "length" : 263.9600815116049,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE64483300_2",
    "length" : 42.181891290859696,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE64425005_2",
    "length" : 73.69859034505795,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921718849_2",
    "length" : 77.79816568996837,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1088340075_2",
    "length" : 27.38997374364662,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281281771_2",
    "length" : 41.929468132729234,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  } ],
  "direction" : "POSITIVE",
  "firstOffset" : 52.00000000000001,
  "lastOffset" : 38.0,
  "length" : 33927.00065451531
}