{
  "id" : "DE-10207.M",
  "name" : "DE-10207.M",
  "elements" : [ {
    "id" : "DE1268349880_1",
    "length" : 100.0161958850563,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268349881_1",
    "length" : 50.53383903294737,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1232537336_1",
    "length" : 146.9123039224503,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225197481_1",
    "length" : 38.80970562939659,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225197482_1",
    "length" : 69.05688254702805,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244180678_1",
    "length" : 68.24508653582531,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244180679_1",
    "length" : 37.52858613168497,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1256987649_1",
    "length" : 16.414061893319975,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1256987650_1",
    "length" : 15.12878187639939,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586900042_1",
    "length" : 132.36771957356194,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783176706_1",
    "length" : 16.41402417943154,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783176707_1",
    "length" : 452.32262698047475,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225251807_1",
    "length" : 57.567875443536984,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225251808_1",
    "length" : 111.49844752373028,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1182942176_1",
    "length" : 37.51742958639719,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1182942177_1",
    "length" : 64.60166530338613,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783091733_1",
    "length" : 90.39450532932011,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE52913974_1",
    "length" : 202.9457912122616,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085146397_1",
    "length" : 17.265606855426128,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085146398_1",
    "length" : 141.74874593728578,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920987539_1",
    "length" : 326.40728187639314,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE722728701_1",
    "length" : 149.01427534785734,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE722728702_1",
    "length" : 25.79286408668386,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783091734_1",
    "length" : 107.86096726825808,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244200778_1",
    "length" : 127.9096983789559,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244200779_1",
    "length" : 57.5662199728533,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244200776_1",
    "length" : 38.573108233186296,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1244200777_1",
    "length" : 799.9419987476324,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920987540_1",
    "length" : 334.62718403737415,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085146395_1",
    "length" : 60.09490243783546,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1282943672_1",
    "length" : 92.59967867657,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1282943673_1",
    "length" : 52.602354274855905,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE52819363_1",
    "length" : 193.4346889038892,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085151072_1",
    "length" : 22.839963389268135,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085151073_1",
    "length" : 85.29309695597121,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920987542_1",
    "length" : 47.848281604767486,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085151074_1",
    "length" : 26.257499474814143,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1085151075_1",
    "length" : 151.7984933719477,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586900015_1",
    "length" : 208.48129759208754,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586900014_1",
    "length" : 341.7795589897555,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920963271_1",
    "length" : 194.05398793397995,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920963272_1",
    "length" : 150.37910946834504,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE52836344_1",
    "length" : 387.6099085754649,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289720612_1",
    "length" : 25.011924824505922,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1289720613_1",
    "length" : 165.29882898720945,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920963274_1",
    "length" : 272.63719042362436,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562821923_1",
    "length" : 1498.862424020422,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586893466_1",
    "length" : 128.8807663279349,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225300766_1",
    "length" : 48.948076097553695,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225300767_1",
    "length" : 62.23306012801981,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783165139_1",
    "length" : 119.51260160426759,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562821924_1",
    "length" : 34.62822579333767,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562821925_1",
    "length" : 183.32468086085075,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE792367307_1",
    "length" : 60.92560084854045,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE792367308_1",
    "length" : 108.57052173561863,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920963275_1",
    "length" : 22.650189336703747,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1210719017_1",
    "length" : 212.18189848659898,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1210719018_1",
    "length" : 281.2133019697138,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE770438840_1",
    "length" : 37.243643095217436,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE576294292_1",
    "length" : 106.22399432363898,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1143172122_1",
    "length" : 22.649862849797607,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1143172123_1",
    "length" : 8.330695343822274,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172530962_1",
    "length" : 38.275230852343505,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1172530963_1",
    "length" : 61.96088574692748,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783093348_1",
    "length" : 115.37961875325504,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783093349_1",
    "length" : 136.834414104859,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE576262642_1",
    "length" : 218.74879564143203,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE576294294_1",
    "length" : 53.90084758160859,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586918827_1",
    "length" : 47.641269636330236,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586918828_1",
    "length" : 23.69026918175066,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562818753_1",
    "length" : 212.01270035066142,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562818751_1",
    "length" : 329.6644387139124,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1240286777_1",
    "length" : 213.49724574490244,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1240286778_1",
    "length" : 174.10672291942723,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225307638_1",
    "length" : 19.137730088204446,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1225307639_1",
    "length" : 80.86183886254395,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1223766901_1",
    "length" : 34.56850910894683,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1181554191_1",
    "length" : 24.698089102112284,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1181554192_1",
    "length" : 29.662295670340757,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562818746_1",
    "length" : 88.32399014340623,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562818745_1",
    "length" : 243.27037229714898,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE558301066_1",
    "length" : 80.22202998531594,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1241073673_1",
    "length" : 51.854259267789004,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1241073674_1",
    "length" : 37.02711124646766,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1076075695_1",
    "length" : 196.2861346498137,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783431628_1",
    "length" : 54.298207124875304,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783431629_1",
    "length" : 50.04362249052144,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281019496_1",
    "length" : 126.04148378219892,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281019497_1",
    "length" : 30.36040884761929,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783093345_1",
    "length" : 157.32484976691305,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920968684_1",
    "length" : 59.42003118641798,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1210784593_1",
    "length" : 38.4743027486072,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1210784594_1",
    "length" : 50.908787943759776,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586885062_1",
    "length" : 883.0115671067042,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586885063_1",
    "length" : 820.5796975741744,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  } ],
  "direction" : "POSITIVE",
  "firstOffset" : 85.0,
  "lastOffset" : 567.9999999999999,
  "length" : 13693.89184868216
}