{
  "id" : "DE-10062.M",
  "name" : "DE-10062.M",
  "elements" : [ {
    "id" : "DE1085151664_1",
    "length" : 96.28442059818106,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921105013_1",
    "length" : 56.76298451294389,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921105012_2",
    "length" : 249.85064666419143,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1283109293_2",
    "length" : 371.2047949339279,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1283109294_1",
    "length" : 236.8030544789051,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1101687934_1",
    "length" : 282.2605970603802,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554339171_1",
    "length" : 16.143681442332348,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE770379494_1",
    "length" : 214.64028329667244,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE770379495_1",
    "length" : 97.55030628495487,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921105014_1",
    "length" : 37.29679262291622,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921105015_1",
    "length" : 40.746673861009704,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE576320659_1",
    "length" : 95.80126835650795,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1076198099_1",
    "length" : 145.9039102721659,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1076198100_2",
    "length" : 43.941346212926234,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE877028275_2",
    "length" : 210.44498664427178,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE877028276_1",
    "length" : 201.06548126673854,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1308849230_1",
    "length" : 33.9368297876263,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1308849231_1",
    "length" : 31.870987200626594,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE710252056_1",
    "length" : 56.04840454643315,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE576320669_1",
    "length" : 33.21784418178772,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE576320670_1",
    "length" : 27.8428406060863,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE706535894_1",
    "length" : 316.95315426856,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193583715_1",
    "length" : 66.93697493711403,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193583716_1",
    "length" : 30.990861333832655,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193583712_1",
    "length" : 125.26897171955513,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193583729_1",
    "length" : 76.30554556710766,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193583730_1",
    "length" : 96.35568865161679,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1194761080_1",
    "length" : 90.90084630993303,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1194761081_1",
    "length" : 208.27417061221036,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1194760765",
    "length" : 68.23601786325405,
    "direction" : "BOTH",
    "inverseOrder" : false
  }, {
    "id" : "DE1194760764",
    "length" : 75.13086084597319,
    "direction" : "BOTH",
    "inverseOrder" : true
  }, {
    "id" : "DE1071094583",
    "length" : 80.39745291096717,
    "direction" : "BOTH",
    "inverseOrder" : true
  }, {
    "id" : "DE1073084281",
    "length" : 49.18584206727755,
    "direction" : "BOTH",
    "inverseOrder" : true
  }, {
    "id" : "DE1188413702",
    "length" : 98.10261857871222,
    "direction" : "BOTH",
    "inverseOrder" : false
  }, {
    "id" : "DE1188413701_2",
    "length" : 74.16530266142223,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1071095976_2",
    "length" : 47.12485874241162,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE917637361_2",
    "length" : 15.635281116650717,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE917637360_2",
    "length" : 19.483864795238382,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1071103964_2",
    "length" : 34.13646292184033,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1287172128",
    "length" : 47.58023571397791,
    "direction" : "BOTH",
    "inverseOrder" : true
  }, {
    "id" : "DE1287172127",
    "length" : 23.11709190830398,
    "direction" : "BOTH",
    "inverseOrder" : false
  }, {
    "id" : "DE1243332430_1",
    "length" : 30.93262579773763,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243332431_1",
    "length" : 190.50615777943602,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586900390_1",
    "length" : 78.73150750773607,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE784356355_1",
    "length" : 22.398969372096577,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE784356356_1",
    "length" : 89.11231411909706,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281444939_1",
    "length" : 55.22807670633956,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281444940_1",
    "length" : 59.7156481605855,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281444938_1",
    "length" : 31.117877111320578,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586900333_1",
    "length" : 45.885374312937856,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586900332_1",
    "length" : 115.91942027918182,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586900315_1",
    "length" : 72.35231699154947,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1073635517_1",
    "length" : 43.37127026836495,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1073635518_1",
    "length" : 21.139585422248743,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1232574410_1",
    "length" : 33.39079144060098,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1232574411_1",
    "length" : 56.75185984712817,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1073635519_1",
    "length" : 146.28968214215138,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1073635520_1",
    "length" : 213.2675015522051,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979543735_1",
    "length" : 21.768202594350882,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979543736_1",
    "length" : 163.08842996695427,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE921185693_1",
    "length" : 68.52492678306362,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE586909525_1",
    "length" : 278.162031508335,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1283298482_1",
    "length" : 143.01913268882257,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1283298483_1",
    "length" : 100.21633227555758,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1263986936_1",
    "length" : 164.3383540705232,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1263986937_1",
    "length" : 150.98019594426802,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297211153_1",
    "length" : 410.75428255873305,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297211154_1",
    "length" : 562.7963642933187,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297211155_1",
    "length" : 195.85796372155994,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1187629179_1",
    "length" : 307.07671001612863,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1246714185_1",
    "length" : 105.2766905073147,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1194232583_1",
    "length" : 170.38434761354029,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1194232584_1",
    "length" : 66.95219591293058,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783176682_1",
    "length" : 20.215574411849783,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307527713_1",
    "length" : 94.29028947075199,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307527714_1",
    "length" : 13.91555694000963,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  } ],
  "direction" : "POSITIVE",
  "firstOffset" : 74.0,
  "lastOffset" : 13.0,
  "length" : 8492.713241506264
}