{
  "id" : "DE-10003.M",
  "name" : "DE-10003.M",
  "elements" : [ {
    "id" : "DE920439759_1",
    "length" : 170.22503519788523,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE920439760_1",
    "length" : 135.59183630141962,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1282854860_1",
    "length" : 170.2202129744346,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554328284_1",
    "length" : 225.23726833145736,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE815706112_1",
    "length" : 319.70352008932696,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE815706113_2",
    "length" : 209.1080542443718,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297382153_2",
    "length" : 30.88303682122475,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297382152_2",
    "length" : 479.504316354484,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE83508220_2",
    "length" : 1164.723473662927,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE811912242_2",
    "length" : 219.01452164152045,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE811912241_2",
    "length" : 484.5759803632773,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297339202_2",
    "length" : 1137.7500420566082,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1297339201_1",
    "length" : 106.25684810291234,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE811913224_1",
    "length" : 68.95794028064635,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE811916739_1",
    "length" : 374.12221375403254,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979407957_1",
    "length" : 189.0106777054145,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979407959_2",
    "length" : 575.379744568241,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979407958_2",
    "length" : 390.92074904157977,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE811916735_2",
    "length" : 371.17887633872874,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE812094659_2",
    "length" : 73.01192275816251,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1278020348_2",
    "length" : 268.3995984072469,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1278020347_2",
    "length" : 57.0602957832529,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE812094664_2",
    "length" : 78.05731499373735,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE812094665_1",
    "length" : 482.2387741035384,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE812101127_2",
    "length" : 1048.4689937791145,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE812101130_2",
    "length" : 1903.8687358321745,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE812106530_2",
    "length" : 1443.276206228677,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE812106529_2",
    "length" : 146.15873524564702,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE812106528_2",
    "length" : 96.24005418708553,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE740429452_2",
    "length" : 82.84170748045653,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1276373269_2",
    "length" : 144.6877214577931,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1276373268_2",
    "length" : 63.488402035582986,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280714144_2",
    "length" : 16.7415503179904,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280714143_2",
    "length" : 377.60425079175883,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280714146_2",
    "length" : 274.4005150896555,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280714145_2",
    "length" : 27.885382527185904,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1278222372_2",
    "length" : 22.345976271270395,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1278222371_2",
    "length" : 41.46555375689934,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE812106543_2",
    "length" : 510.40451962479034,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE812106542_2",
    "length" : 517.1384939769966,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  } ],
  "direction" : "POSITIVE",
  "firstOffset" : 99.99999999999999,
  "lastOffset" : 467.0,
  "length" : 14348.010558502509
}