{
  "id" : "DE-10035.M",
  "name" : "DE-10035.M",
  "elements" : [ {
    "id" : "DE921718854_2",
    "length" : 142.5673727813056,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280584231_2",
    "length" : 41.27896812063289,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1296357491_2",
    "length" : 668.3423881904546,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1302009917_2",
    "length" : 405.34099511002336,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1302009916_2",
    "length" : 57.325405025446244,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1268678952_2",
    "length" : 38.99724113831744,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1213594779_2",
    "length" : 100.98352114676115,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280584153_2",
    "length" : 69.43208155801557,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281281816_2",
    "length" : 27.6563415032489,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1281281815_2",
    "length" : 81.4031756955271,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1213594777_2",
    "length" : 47.79968286598395,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1295735131_2",
    "length" : 45.50497523383093,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280884821_2",
    "length" : 16.428760822179246,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280884824_2",
    "length" : 24.68699868209485,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280884823_2",
    "length" : 122.59733488401784,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280584165_2",
    "length" : 56.05694133605357,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280584164_2",
    "length" : 50.96965294394508,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193222675_2",
    "length" : 164.75875455801832,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1193221408_2",
    "length" : 49.62561814657988,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE979408367_2",
    "length" : 103.09118978832215,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280584239_2",
    "length" : 36.788642095503874,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280584238_2",
    "length" : 166.99737110810972,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307350005_2",
    "length" : 52.59776876980673,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1307350004_2",
    "length" : 129.94298589684732,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1295735113_2",
    "length" : 108.1515793390106,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280584305_2",
    "length" : 125.45645541263953,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1280584304_2",
    "length" : 17.30861570507874,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  } ],
  "direction" : "POSITIVE",
  "firstOffset" : 100.0,
  "lastOffset" : 11.0,
  "length" : 2845.782202152676
}