{
  "id" : "DE-10056.M",
  "name" : "DE-10056.M",
  "elements" : [ {
    "id" : "DE1236222222_2",
    "length" : 133.34295293801247,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236222221_2",
    "length" : 29.072804955913174,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236222218_2",
    "length" : 35.83839823533879,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1236222217_2",
    "length" : 422.93914133888234,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819422608_2",
    "length" : 1243.6701703644985,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE64429426_2",
    "length" : 108.1446900950333,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1239800815_2",
    "length" : 194.7175432442152,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1239800816_2",
    "length" : 41.758351996447345,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1239800818_2",
    "length" : 25.369935168331565,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1239800817_2",
    "length" : 36.57427565169338,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1239800820_2",
    "length" : 29.074001641435746,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1239800819_2",
    "length" : 349.8094987370139,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783166468_2",
    "length" : 142.99755840106877,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE783166467_2",
    "length" : 80.34692882346945,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554348447_1",
    "length" : 459.9387652142506,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1296590142_1",
    "length" : 30.247753416298078,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1296590143_1",
    "length" : 34.107799144111645,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819421962_1",
    "length" : 104.26876817895334,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1226728096_1",
    "length" : 37.195006322005824,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1226728097_1",
    "length" : 49.82132952578101,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819419447_1",
    "length" : 33.46726679798211,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1273202658_1",
    "length" : 70.65277807475172,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1273202659_1",
    "length" : 58.03066755717697,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE819417882_1",
    "length" : 28.333047853514188,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1087967383_1",
    "length" : 35.834601879225794,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1087967384_1",
    "length" : 105.41995181703042,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1104721720_1",
    "length" : 35.56665624903555,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1104721721_1",
    "length" : 142.81595214126114,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE1243535034_1",
    "length" : 92.89477062420227,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE769313388_1",
    "length" : 157.82412623698124,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE769313389_1",
    "length" : 187.76223233782974,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE769313390_1",
    "length" : 52.78463038500516,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE562763528_1",
    "length" : 362.5987822096865,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  }, {
    "id" : "DE554340528_1",
    "length" : 105.5141901975035,
    "direction" : "POSITIVE",
    "inverseOrder" : false
  } ],
  "direction" : "POSITIVE",
  "firstOffset" : 4.999999999999999,
  "lastOffset" : 22.0,
  "length" : 4970.221137556438
}