package de.heuboe.vmis2.jprotoc.transferinterface;

import java.util.Collection;

import org.atteo.classindex.IndexSubclasses;

/**
 * A registration instance that contains all known transfer instances for a given module.
 * Implementations are expected to be singletons and have a single, public constructor without
 * arguments. The implementations will usually be generated by the jprotoc-plugin; one for each
 * interface project.
 *
 * <p>
 * Instances of this class will be found, if they are listed in the
 * {@code META-INF/services/de.heuboe.vmis2.jprotoc.transferinterface.ProtoTransferCatalog} text
 * file. One entry per line. You can automate this process if you add the following maven
 * dependency:
 * </p>
 *
 * <pre>
 * {@code
 * <dependency>
 *     <groupId>org.atteo.classindex</groupId>
 *     <artifactId>classindex</artifactId>
 *     <optional>true</optional>
 * </dependency>
 * }
 * </pre>
 *
 * @author Daniel Theuke (daniel.theuke@heuboe.de)
 */
@IndexSubclasses
@FunctionalInterface
public interface ProtoTransferCatalog {

    /**
     * Gets a list of all transfer instances known to this registration.
     *
     * @return An unmodifiable collection containing all known transfer instances.
     */
    Collection<BaseTransfer<?, ?>> getTransfers();

}
