//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.10 at 10:59:19 AM MESZ 
//


package de.heuboe.sdbby.service.config.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for configSet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="configSet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="configItem" type="{http://sdbby.heuboe.de/service/config/data}configItem" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "configSet", propOrder = {
    "configItem"
})
public class ConfigSet {

    protected List<ConfigItem> configItem;

    /**
     * Default no-arg constructor
     * 
     */
    public ConfigSet() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public ConfigSet(final List<ConfigItem> configItem) {
        this.configItem = configItem;
    }

    /**
     * Gets the value of the configItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the configItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConfigItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConfigItem }
     * 
     * 
     */
    public List<ConfigItem> getConfigItem() {
        if (configItem == null) {
            configItem = new ArrayList<ConfigItem>();
        }
        return this.configItem;
    }

}
