//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.10 at 10:59:19 AM MESZ 
//


package de.heuboe.sdbby.service.config.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.heuboe.sdbby.service.config.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConfigSet_QNAME = new QName("http://sdbby.heuboe.de/service/config/data", "ConfigSet");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.heuboe.sdbby.service.config.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConfigItem }
     * 
     */
    public ConfigItem createConfigItem() {
        return new ConfigItem();
    }

    /**
     * Create an instance of {@link ConfigSet }
     * 
     */
    public ConfigSet createConfigSet() {
        return new ConfigSet();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfigSet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sdbby.heuboe.de/service/config/data", name = "ConfigSet")
    public JAXBElement<ConfigSet> createConfigSet(ConfigSet value) {
        return new JAXBElement<ConfigSet>(_ConfigSet_QNAME, ConfigSet.class, null, value);
    }

}
