//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.10 at 10:59:19 AM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://sdbby.heuboe.de/service/config/data")
package de.heuboe.sdbby.service.config.data;
