## Actuator
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.endpoints.web.exposure.exclude=shutdown
management.endpoints.web.exposure.include=health,info,metrics,prometheus,loggers
management.metrics.export.prometheus.enabled=true
#
grpc.client.GLOBAL.negotiationType=PLAINTEXT
grpc.client.GLOBAL.maxInboundMessageSize=25000000
