server.port=6723

## Database
spring.data.mongodb.uri=mongodb://he3-w7v/c2vbaSddbySvcDev1

#spring.data.mongodb.uri=mongodb://adminuser:password123@172.31.246.1:32000/c2vba-ps?appName=strategie-matching&authSource=admin


##
## Kafka
##

## Connection
spring.kafka.bootstrap-servers=master1.p.c2vba.heuboe.hbintern:32002
#spring.kafka.bootstrap-servers=kafka1.d.uz.komodnext.heuboe.hbintern:9092

# Consumer ID
spring.kafka.consumer.group-id=strategie-matching-ps-test

# Default serialization types
spring.kafka.consumer.properties.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.producer.properties.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer

#spring.kafka.listener.ack-mode=MANUAL

de.heuboe.sdbby.service.wlsHost=localhost
de.heuboe.sdbby.service.wlsPort=8087

de.heuboe.sdbby.service.rulesFile=src/main/resources/rules/StrategieRegeln_v0.20.txt

# Cycle of rule evaluation (ms)
de.heuboe.sdbby.service.updateCycle=1001  

#de.heuboe.sdbby.service.prismenFile=cfg/prismen.txt

de.heuboe.sdbby.service.precedingFontChars=1


de.heuboe.sdbby.service.wzgBetriebsartTopic = C2VBA-tlsin-WZGBetriebsart
de.heuboe.sdbby.service.wzgStellzustandTopic = C2VBA-tlsin-WZGStellzustand
de.heuboe.sdbby.service.wzgKanalSteuerungTopic = C2VBA-tlsin-WZGKanalsteuerung
de.heuboe.sdbby.service.wzgDeFehlerTopic = C2VBA-tlsin-WZGDeFehler

de.heuboe.sdbby.service.strategyStateTopic = C2VBA-StrategyStates

# gRPC config service connection
grpc.client.ConfigService.address=dns:///master1.p.c2vba.heuboe.hbintern:31100
grpc.client.ConfigService.maxInboundMessageSize=30000000
grpc.client.ConfigService.negotiationType=PLAINTEXT


# gRPC GeoManager connection
grpc.client.GeoManager.address=dns:///master1.p.c2vba.heuboe.hbintern:31301
grpc.client.GeoManager.maxInboundMessageSize=30000000
grpc.client.GeoManager.negotiationType=PLAINTEXT



