server.port=8080

de.heuboe.datex2.vms.status.pub.tableId=BY-SDB-D2-VMS-Unit-Table-WWW
de.heuboe.datex2.vms.status.pub.tableVersion=${SUED-VMS-WWW-VERSION}
de.heuboe.datex2.vms.status.pub.pubInstance=ps
de.heuboe.datex2.vms.status.pub.fileDir=/files
de.heuboe.datex2.vms.status.pub.connTimeout=2000
de.heuboe.datex2.vms.status.pub.pubInterval=300
de.heuboe.datex2.vms.status.pub.pubMode=OnUpdateCyclicSnapshot
de.heuboe.datex2.vms.status.pub.sender=${MDM_BY_ORGA_KEY}
de.heuboe.datex2.vms.status.pub.datex2Target=MDM

de.heuboe.datex2.vms.status.pub.vmsServiceUrl=http://vms-publication-service.c2vba.svc:81/Datex2/VMSPublication/Service?wsdl

de.heuboe.datex2.vms.status.pub.vmsServiceListenerHost=0.0.0.0
de.heuboe.datex2.vms.status.pub.vmsServiceListenerPort=4749

de.heuboe.datex2.vms.status.pub.vmsServiceListenerHostExt=vms-status-publication-www.c2vba.svc
de.heuboe.datex2.vms.status.pub.vmsServiceListenerPortExt=81

#de.heuboe.datex2.connection.url=http://sdbby-w7v.heuboe.hbintern:5717/D2PushReceiver

de.heuboe.datex2.vms.status.pub.receiverType=MDM
de.heuboe.datex2.connection.url=http://c2vba-datex2-region-receiver-www.c2vba.svc:82/c2vba/www/services/supplierPushService-www-sued

de.heuboe.datex2.connection.useGzip=true
de.heuboe.datex2.remote=SOAP

## --------------------------------------------------------------------------
## Kafka
## --------------------------------------------------------------------------

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP}

# Consumer ID
spring.kafka.consumer.group-id=vms-status-publication-www

# Default serialization types
spring.kafka.consumer.properties.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.producer.properties.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer




## --------------------------------------------------------------------------
## Actuator
## --------------------------------------------------------------------------
management.endpoints.web.exposure.include=health
management.endpoints.web.exposure.exclude=shutdown
management.endpoint.metrics.enabled=true
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
