---
apiVersion: v1
kind: Service
metadata:
  name: c2vba-datex2-join-fg1
spec:
  ports:
  - name: actuator
    nodePort: 32740
    port: 80
    protocol: TCP
    targetPort: actuator
  selector:
    app: c2vba-datex2-join-fg1
  type: NodePort
