---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: srp-files
  annotations:
    storageClass: default_by_build.sh
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
