<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>de.heuboe.asfinag</groupId>
        <artifactId>vmis2-base-parent</artifactId>
        <version>7.1.1</version>
    </parent>

    <artifactId>vmis2-synchronize-vd-app</artifactId>
    <version>1.12.0</version>

    <name>VMIS2 Kern ${project.artifactId}</name>
    <description>VMIS2 application for synchronization of incoming data.</description>
    <url>https://gitlab.heuboe.hbintern/${gitlab.path}</url>
    <inceptionYear>2019</inceptionYear>

    <developers>
        <developer>
            <name>David Hermanns</name>
        </developer>
        <developer>
            <name>Marion Keune</name>
        </developer>
    </developers>

    <scm>
        <url>https://gitlab.heuboe.hbintern/${gitlab.path}</url>
        <connection>scm:git:git@gitlab.heuboe.hbintern:${gitlab.path}.git</connection>
        <developerConnection>scm:git:git@gitlab.heuboe.hbintern:${gitlab.path}.git</developerConnection>
      <tag>vmis2-synchronize-vd-app_1.9.6</tag>
  </scm>

    <properties>
	    <java.version>21</java.version>
        <mainClass>de.heuboe.asfinag.vmis2.synchronize.vd.Main</mainClass>
        <skip.fat>true</skip.fat>
        <sonar.exclusions>src/**/config/*Config.java;src/**/config/*Properties.java</sonar.exclusions>
        <sonar.test.exclusions>src/test/**</sonar.test.exclusions>
        <gitlab.path>VMIS2/data-receiving-and-processing/vmis2-synchronize-vd-app</gitlab.path>
    </properties>

    <dependencies>
        <!-- HeuBoe -->
        <dependency>
            <groupId>de.heuboe.asfinag</groupId>
            <artifactId>vmis2-app-base</artifactId>
            <version>2.0.0</version>
        </dependency>
        <dependency>
            <groupId>de.heuboe.asfinag</groupId>
            <artifactId>vmis2-configservice-interface</artifactId>
            <version>1.16.27</version>
        </dependency>
        <dependency>
            <groupId>de.heuboe.asfinag</groupId>
            <artifactId>vmis2-constants</artifactId>
            <version>0.0.6</version>
        </dependency>      
        <dependency>
            <groupId>de.heuboe.asfinag</groupId>
            <artifactId>vmis2-control-datamodel</artifactId>
            <version>3.5.1</version>
        </dependency>
        <dependency>
            <groupId>de.heuboe.asfinag</groupId>
            <artifactId>vmis2-infrastructure-base</artifactId>
            <version>2.0.1</version>
        </dependency>
        <dependency>
            <groupId>de.heuboe.asfinag</groupId>
            <artifactId>vmis2-jprotoc-transferinterface</artifactId>
            <version>4.6.2</version>
        </dependency>
        <dependency>
            <groupId>de.heuboe.asfinag</groupId>
            <artifactId>vmis2-kafka-protopojo-converter</artifactId>
            <version>2.0.0</version>
        </dependency>
        <dependency>
            <groupId>de.heuboe.asfinag</groupId>
            <artifactId>vmis2-log4j2-extension</artifactId>
            <version>1.3.1</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>de.heuboe.asfinag</groupId>
            <artifactId>vmis2-receiving-processing-datamodel</artifactId>
            <version>1.1.0</version>
        </dependency>
        <dependency>
            <groupId>de.heuboe.asfinag</groupId>
            <artifactId>vmis2-synchronize-vd</artifactId>
            <version>1.5.0</version>
        </dependency>
        <dependency>
            <groupId>de.heuboe.asfinag</groupId>
            <artifactId>vmis2-tls-proto-interface</artifactId>
            <version>3.3.0</version>
        </dependency>
        
        <!-- EHE -->
        <dependency>
            <groupId>eu.vmis-ehe.asfinag</groupId>
            <artifactId>vmis2-paramservice-interface</artifactId>
            <version>1.18.0</version>
        </dependency>
        <!-- MockClock -->
        <dependency>
            <groupId>com.statemachinesystems</groupId>
            <artifactId>mock-clock</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.quartz-scheduler/quartz -->
        <dependency>
            <groupId>org.quartz-scheduler</groupId>
            <artifactId>quartz</artifactId>
        </dependency>
        <!-- Spring -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-log4j2</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>net.devh</groupId>
            <artifactId>grpc-client-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java-util</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- Spring-Metrics -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- Kafka -->
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
        </dependency>

        <!-- jackson -->
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.projectlombok/lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/io.vavr/vavr -->
        <!-- Tuple and other functional stuff -->
        <dependency>
            <groupId>io.vavr</groupId>
            <artifactId>vavr</artifactId>
            <version>0.9.2</version>
        </dependency>

        <!-- testing only -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka-test</artifactId>
            <scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>ch.qos.logback</groupId>
					<artifactId>logback-classic</artifactId>
				</exclusion>
				<exclusion>
					<groupId>ch.qos.logback</groupId>
					<artifactId>logback-core</artifactId>
				</exclusion>
			</exclusions>
        </dependency>
        <dependency>
            <groupId>net.sf.supercsv</groupId>
            <artifactId>super-csv</artifactId>
            <version>2.4.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- Build an executable (fat) jar + add build infos -->
            <!-- add some stuff to spring's actuators; build a fat .jar (unless
                ${skip.fat) is true, see properties/the 'fat' profile) -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>build-info</id>
                        <goals>
                            <goal>build-info</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>repackage</id>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                        <configuration>
                            <skip>${skip.fat}</skip>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- Dockering -->
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>docker-build</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <from>
                        <image>${docker.registry}/eclipse-temurin:21-jre-alpine</image>
                    </from>
                    <to>
                        <image>${docker.registry}/heuboe/vmis2/${project.artifactId}:${project.version}</image>
                    </to>
                    <!-- We currently don't use HTTPS -> insecure -->
                    <allowInsecureRegistries>true</allowInsecureRegistries>
                    <container>
                        <jvmFlags>
                            <jvmFlag>-Dlogging.config=/config/log4j2.xml</jvmFlag>
                            <jvmFlag>-Dspring.config.additional-location=/config/</jvmFlag>
                        </jvmFlags>
                        <mainClass>${mainClass}</mainClass>
                        <!-- The ports that the application exposes, including
                            its purpose -->
                        <ports>
                            <port>8080</port><!-- actuator -->
                        </ports>
                        <labels>
                            <version>${project.version}</version>
                            <build.timestamp>${maven.build.timestamp}</build.timestamp>
                            <git.tags>${git.tags}</git.tags>
                            <git.commit.id.abbrev>${git.commit.id.abbrev}</git.commit.id.abbrev>
                            <git.commit.timestamp>${git.commit.time}</git.commit.timestamp>
                        </labels>
                        <creationTime>USE_CURRENT_TIMESTAMP</creationTime>
                        <filesModificationTime>${git.commit.time}</filesModificationTime>
                    </container>
                </configuration>
            </plugin>

        </plugins>
    </build>

    <profiles>

        <!-- Skip integration tests during cmd line build, use -P!skipIt
            to disable -->
        <profile>
            <id>skipIt</id>
            <activation>
                <property>
                    <name>!skipIt</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <forkCount>1</forkCount>
                            <reuseForks>false</reuseForks>
                            <forkedProcessExitTimeoutInSeconds>480</forkedProcessExitTimeoutInSeconds>
                            <excludes combine.children="append">
                                <exclude>**/it/**</exclude>
                            </excludes>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <!-- Skip approval tests during cmd line build, use -P!skipApproval
            to disable -->
        <profile>
            <id>skipApproval</id>
            <activation>
                <property>
                    <name>!skipApproval</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <excludes combine.children="append">
                                <exclude>**/approval/**</exclude>
                            </excludes>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <!-- Spring Boot FatJar: To activate this, use -Pfat on the commandline -->
        <profile>
            <id>fat</id>
            <properties>
                <skip.fat>false</skip.fat>
            </properties>
        </profile>

    </profiles>

</project>
