#
# 1) Remarks
#
# a) The url is only for information, but one should check if it is 'reachable'
#    (<url>?wsdl in a web browser should return the WSDL content of the soap service)
# b) In production environment the available ports are restricted by
#    i)  Firewall configurations 
#    ii) Kubernetes node port definitions (the node ports may differ from the pod ports) 
# 
# 2) Restrictions for consumerMode = PUSH
#
# a) For a single serverPort only one serverSchema shall be used
# b) For a single serverPort different contexts shall be used
#
#
regions:
  region-configs:
    -
      name: vms-sued-sba
      remote: SOAP      
      consumerMode: PUSH      
      url: http://mdm-datex2.heuboe.de:4721/datex2/services/supplierPushService-sba-sued
      context: /supplierPushService-sba-sued
      serverSchema: http
      serverPort: 4721
      serverDomain: "mdm-datex2.heuboe.de"
      topic: C2VBA-datex2-publication-vms-sba-sued
