server.port=4711

##
## Kafka
##

## Connection
spring.kafka.bootstrap-servers=master1.p.c2vba.heuboe.hbintern:32002

# Consumer ID
spring.kafka.consumer.group-id=c2vba-datex2-region-receiver-test-ps

# Default serialization types
spring.kafka.consumer.properties.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.producer.properties.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer


de.heuboe.datex2.connection.disableCNCheck=true

# Push consumers complete context is  /datex2/services/supplierPushService-<ext>
server.servlet.context-path=/datex2

# Pull clients query every <pullInterval> seconds
de.heuboe.c2vba.datex2.region.receiver.pullInterval = 60

# All received publications are logged in this directory
de.heuboe.c2vba.datex2.region.receiver.pubFileDir = D:/by/c2vba/join/sba

# Timeout reading topic state (initial content) 
de.heuboe.c2vba.datex2.region.receiver.keyStockReadTimeout = 15

de.heuboe.c2vba.datex2.region.receiver.aliveIntervalSued = 600
de.heuboe.c2vba.datex2.region.receiver.aliveIntervalNord = 3600

