---
apiVersion: v1
kind: Service
metadata:
  name: tls-legacy-data-converter
spec:
  ports:
  - name: actuator
    nodePort: 31445
    port: 80
    protocol: TCP
    targetPort: actuator
  selector:
    app: tls-legacy-data-converter
  type: NodePort
