## +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
##
## tls-receiver-app
##
## This file provides a list of all custom application properties. The
## properties are listed with a possible default value, a hint which values
## might be allowed and a short description what the properties are used for.
##
## The file is intended as a template for custom property files
## of this application, which are then used in specific environments.
##
## All properties that have no default value or need to be overridden
## can be specified either
##   - within a custom property file ('-Dspring.config.location=file:<path>')
##   - by using system properties (-D<property>=<value>)
##   - application parameters (--<property>=<value>).
##
## See: Spring Boot Reference Guide - Externalized Configuration
## http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config
## +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-

#SYSTEM_NAME_UCx=C2VBA
SYSTEM_NAME_UCx=${SYSTEM_PREFIX}

## --------------------------------------------------------------------------
## Spring Kafka
## --------------------------------------------------------------------------
# The name of the consumer group for kafka.
# This is important because the progress/current index is saved using this name.
# Different applications that listen to kafka HAVE to use different group ids.
spring.kafka.consumer.group-id=tls_receiver
spring.kafka.listener.missing-topics-fatal=false
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP}

# GRPC ConfigService
grpc.client.CfgSvc.address=static://config-service.c2vba:9090
grpc.client.CfgSvc.negotiationType=PLAINTEXT

# properties for the tls-receiver
de.heuboe.asfinag.tls.receiver.plugins=cvtPlugins
de.heuboe.asfinag.tls.receiver.plugJarNameTemplate=.*\\.jar
de.heuboe.asfinag.tls.receiver.plugpack=eu.vmis_ehe.vmis2.tls.received.conv
de.heuboe.asfinag.tls.receiver.uzId=${SYSTEM_NAME_UCx}
# ${SYSTEM_NAME_UCx}

de.heuboe.asfinag.tls.receiver.topicPostfix=
de.heuboe.asfinag.tls.receiver.topicPrefix=${SYSTEM_NAME_UCx}-tlsin-
de.heuboe.asfinag.tls.receiver.inputTopic=${SYSTEM_NAME_UCx}-tlsin-TeleReceived
#de.heuboe.asfinag.tls.receiver.topicPrefix=Kaarst-tlsin-
#de.heuboe.asfinag.tls.receiver.inputTopic=Kaarst-tlsin-TeleReceived

# timezone where tls timestamps operate in
# Europe/Berlin MEZ with daylight saving time
# GMT+01:00 MEZ but always wintertime !needs to be exact!
# UTC ...
de.heuboe.asfinag.tls.receiver.timezoneid=Europe/Berlin

de.heuboe.tls.receiver.config.chg.changetopic=VRZ-DataChange
de.heuboe.tls.receiver.config.chg.changetopicgroupid=tlsReceiverChangeDetectorGrpId

# The name of the application shown in the message management system.
#de.heuboe.tls.receiver.config.alarm.manager.eventSource=TLS-Receiver
# The group id that will be used for the alarm message if an object reference exists.
#de.heuboe.tls.receiver.config.alarm.manager.groupId=1002
# The group id that will be used for the alarm message if no object reference exists.
#de.heuboe.tls.receiver.config.alarm.manager.groupIdWithoutObjectReference=1002
# The topic the alarm message should be sent to.
#de.heuboe.tls.receiver.config.alarm.manager.topic=${SYSTEM_NAME_UCx}-AlarmMessage
