---
apiVersion: v1
kind: Service
metadata:
  name: c2vba-datex2-join-fg3
spec:
  ports:
  - name: actuator
    nodePort: 32750
    port: 80
    protocol: TCP
    targetPort: actuator
  selector:
    app: c2vba-datex2-join-fg3
  type: NodePort
