package de.heuboe.tls.iface.prot.tlsoip;

import de.heuboe.tls.iface.iface.IfaceApplication;
import de.heuboe.tls.iface.iface.IfaceProtocol;
import de.heuboe.tls.iface.iface.SystemMessageManagement;
import de.heuboe.tls.iface.lib.Util;
import lombok.extern.slf4j.Slf4j;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentLinkedQueue;

/**
 * Implementation of an {@link IfaceProtocol}
 * In this case it is the implementation of TLS oer IP
 */
@Slf4j
public class TlsOverIp implements IfaceProtocol {
	
	/**
	 * access to the iface application instance to pass received telegrams to
	 */
	private IfaceApplication ifaceApplication;

	/**
	 * a map for telegrams that have to be send by the communication threads
	 */
	private ConcurrentHashMap<String, ConcurrentLinkedQueue<Telegram>> teleToSend = new ConcurrentHashMap<>();
	
	/**
	 * the partner list received from the application (generated by routing data)
	 */
	private Map<Short, List<Short>> applicationKnownPartners;
	
	/**
	 * the own config containing the tls over ip parameters.
	 */
	private TlsOverIpConfig config;

	/**
	 * a map with the communication states
	 */
	private List<TlsOverIpClient> clientList = new ArrayList<>();
	
	/**
	 * a map with all runing server ports and their configuration
	 */
	private Map<Integer, TlsOverIpServer> serverMap = new HashMap<>();
	
	/**
	 * an object handling system messages if not null
	 */
	private SystemMessageManagement smm;
	
	/**
	 * Constructor with external provided configuration.
	 * 
	 * @param config the tls over ip configuration
	 */
	public TlsOverIp(TlsOverIpConfig config) {
		this.config = config;
	}
	
	/**
	 * Constructor with filename for the configuration.
	 * @param configFile a file containing the tls over ip configuration
	 * @throws IOException if file could not be read
	 */
	public TlsOverIp(String configFile) throws IOException {
		config = new ConfigReader(configFile).getTlsOverIpConfig();
	}
	
	/**
	 * send a tls telegram to osi2port/osi2partner.
	 * @param tele the tls telegram (Sammeltelegramm)
	 * @param osi2port osi2port where receiver is connected
	 * @param osi2partner osi2 address of receiver
	 */
	@Override
	public void sendTelegram(byte[] tele, short osi2port, short osi2partner) {
		log.debug("sendTelegram to " + osi2port + "/" + osi2partner);
		log.debug("Data = " + Util.toHex(tele));
		if (getConfiguration(osi2port, osi2partner) == null) {
			// silently ignore
			return;
		}
		ConcurrentLinkedQueue<Telegram> teleList = teleToSend.get(Util.getKey(osi2port, osi2partner));
		if (teleList != null) {			
			teleList.add(new Telegram(tele));
			if (teleList.size() > 100 && (teleList.size() % 1000) == 0) {
				log.warn("Size of teleList for " + osi2port + "/" + osi2partner + " = " + teleList.size());
				sysMsg( "Warn: Size of teleList for " + osi2port + "/" + osi2partner + " = " + teleList.size() );
			}
		} else {
			log.warn("cannot send telegram: communication to " + osi2port + "/" + osi2partner + " didn't identify yet.");
			sysMsg( "Warn: Cannot send telegram: communication to " + osi2port + "/" + osi2partner + " didn't identify yet." );
		}
	}
	
	private void sysMsg( String msg ) {
	    if (null != smm) {
	        smm.sendMessage( msg );
	    }
	}

	/**
	 * start communication for a single receiver, all receivers that are connected to a given osi2port or all configured receivers.
	 * @param osi2port osi2port where receiver is connected. If null, all configured receivers are started
	 * @param osi2partner osi2 address of receiver. If null, all receivers connected to the osi2port are started
	 */
	@Override
	public void startCommunication(Short osi2port, Short osi2partner) {
		if (osi2port != null && osi2partner != null) {
			startCommForPartner(osi2port, osi2partner);
		} else if (osi2port != null) {
			startCommForPort(osi2port);
		} else {
			startCommForAll();
		}
		
	}

	/**
	 * stop communication for a single receiver, all receivers that are connected to a given osi2port or all configured receivers.
	 * @param osi2port osi2port where receiver is connected. If null, all configured receivers are started
	 * @param osi2partner osi2 address of receiver. If null, all receivers connected to the osi2port are started
	 */
	@Override
	public void stopCommunication(Short osi2port, Short osi2partner) {
		List<TlsOverIpClient> clientsToStop = new ArrayList<>();
		for(TlsOverIpClient client : clientList) {
			// the method isPortPartner() handles null values for osi2port and/or osi2partner
			if (client.isPortPartner(osi2port, osi2partner)) {
				clientsToStop.add(client);
			}
		}
		for(TlsOverIpClient client : clientsToStop) {
			client.stopCommunication();
			clientList.remove(client);
		}
	}

	/**
	 * Setter for the iface application.
	 * @param ifaceApplication the iface application
	 */
	@Override
	public void setIfaceApplication(IfaceApplication ifaceApplication) {
		this.ifaceApplication = ifaceApplication;		
		this.smm = ifaceApplication.getSystemMessageManagement();
	}

    /**
     * Getter for the iface application.
     * @return ifaceApplication the iface application
     */
    @Override
    public IfaceApplication getIfaceApplication() {
        return this.ifaceApplication;       
    }

	/**
	 * Setter for the configured receivers. The map contains the osi2port as key and a list of osi2partner addresses as value.
	 * @param partnerMap the map containing all receivers
	 */
	@Override
	public void setPartners(Map<Short, List<Short>> partnerMap) {
		applicationKnownPartners = partnerMap;
	}

	void createSendQueue(short osi2Port, short osi2Partner) {
		String key = Util.getKey(osi2Port, osi2Partner);
		ConcurrentLinkedQueue<Telegram> queue = new ConcurrentLinkedQueue<>();
		teleToSend.put(key, queue);
	}
	
	void recvTelegram(byte[] tele, short osi2port, short osi2Address) {
		ifaceApplication.recvTelegramm(tele, osi2port, osi2Address);		
	}

	Telegram getNextTelegram(short osi2port, short osi2partner) {
		ConcurrentLinkedQueue<Telegram> teleList = teleToSend.get(Util.getKey(osi2port, osi2partner));
		if (teleList != null) {			
			if (!teleList.isEmpty()) {
				return teleList.remove();
			}
		} else {
			log.warn("cannot send telegram: connection " + Util.getKey(osi2port, osi2partner) + " is not known.");
			sysMsg( "Warn: Cannot send telegram: connection " + Util.getKey(osi2port, osi2partner) + " is not known." );
		}
		return null;
	}

	void sendCommState(short osi2Port, short osi2Address, boolean state) {
		ifaceApplication.recvCommunicationState(osi2Port, osi2Address, state, false);
	}

	private void startCommForAll() {
		for(Entry<Short, List<Short>> entry : applicationKnownPartners.entrySet()) {
			Short port = entry.getKey();
			for(Short partner : entry.getValue()) {
				startCommForPartner(port, partner);
			}
		}				
	}

	private void startCommForPort(short port) {
		List<Short> partners = applicationKnownPartners.get(port);
		for(Short partner : partners) {
			startCommForPartner(port, partner);
		}
	}

	private void startCommForPartner(short osi2Port, short osi2Partner) {
		ConnectionConfig conConfig = getConfiguration(osi2Port, osi2Partner);
		log.debug( "startCommForPartner osi2 " + osi2Port + "/" + osi2Partner + " cfg=" + conConfig );
		if (conConfig == null) {
			log.warn("cannot start communication for " + osi2Port + "/" + osi2Partner + " because it has no tls over ip configuration");
			sysMsg( "Warn: cannot start communication for " + osi2Port + "/" + osi2Partner + " because it has no tls over ip configuration" );
			return;
		}
		if (conConfig.getClient() == null) {
			log.warn("cannot start communication for " + osi2Port + "/" + osi2Partner + " because you didn't tell if it is client or server");
			sysMsg( "Warn: Cannot start communication for " + osi2Port + "/" + osi2Partner + " because you didn't tell if it is client or server" );
			return;
		}
		log.debug( "start a connection" );
		if ( Boolean.TRUE.equals(conConfig.getClient()) ) {
			startClientCommunication(conConfig);
		} else {
			startServerCommunication(conConfig);
		}
	}
	
	private void startClientCommunication(ConnectionConfig config) {
		String name = config.getServerHost() + ":" + config.getTcpPort();
		TlsOverIpClient client = new TlsOverIpClient(config, this, name);
		clientList.add(client);
	}
	
	private void startServerCommunication(ConnectionConfig config) {
		TlsOverIpServer server = serverMap.get(config.getTcpPort());
		if (server == null) {
			String name = "ServerPort: " + config.getTcpPort();
			boolean isSingleServer = checkSingleServer(config.getTcpPort());
			if (isSingleServer) {
				log.info(name + ": is single server");
				server = new TlsOverIpServer(config, this, name);
				server.setSingleServer();
			} else {
				log.info(name + ": is multi server");
				// try to get a configuration for 0/0 or osi2Port/0
				ConnectionConfig cfg = getConfiguration(config.getOsi2Port(), (short)0);
				if (cfg == null) {
					cfg = getConfiguration((short)0, (short)0);
				}
				if (cfg == null) {
					cfg = config;
				}
				server = new TlsOverIpServer(cfg, this, name);
				if (cfg != config) {
					server.addConfiguration(config);
				}
			}
			serverMap.put(config.getTcpPort(), server);
		} else {
			server.addConfiguration(config);
		}
	}
	
	private boolean checkSingleServer(int tcpport) {
		int cnt=0;
		for(ConnectionConfig cfg : config.getConnectionConfigList()) {
			if (cfg.getTcpPort() == tcpport) {
				++cnt;
			}
		}
		return (cnt == 1);
	}

	private ConnectionConfig getConfiguration(short osi2port, short osi2address) {
		for(ConnectionConfig cfg : config.getConnectionConfigList()) {
			if (cfg.getOsi2Port().equals(osi2port) && cfg.getOsi2Address().equals(osi2address)) {
				return cfg;
			}
		}
		return null;		
	}

	/**
	 * generate a global time synchronisation for all receivers.
	 */
	@Override
	public void timeSynchronzation() {
		for(TlsOverIpClient client : clientList) {
			client.timeSync();
		}
		for(TlsOverIpServer server : serverMap.values()) {
			server.timeSync();
		}
	}
	
}
