<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>de.heuboe.tls</groupId>
		<artifactId>receive-tls-parent-pom</artifactId>
		<version>2.0.1-SNAPSHOT</version>
	</parent>

	<artifactId>receiver-interfaces</artifactId>
	<description>Interfaces for tls tls receiver implementation</description>

	<name>${project.artifactId}</name>
	 
	<inceptionYear>2020</inceptionYear>
	<url>${urlCombined}</url>
	     
	<organization>
	    <name>Heusch/Boesefeldt GmbH</name>
	    <url>https://www.heuboe.de</url>
	</organization>
	 
	<licenses>
	    <license>
	        <name>All rights reserved - Heusch/Boesefeldt GmbH</name>
	    </license>
	</licenses>
	 
	<scm>
	    <url>${urlCombined}</url>
	    <connection>scm:git:git@${gitlab}:${urlmain}.git</connection>
	    <developerConnection>scm:git:git@${gitlab}:${urlmain}.git</developerConnection>
	    <tag>HEAD</tag>
	</scm>
	 
	<developers>
	    <developer>
	        <id>rn</id>
	        <name>Ronald Nikel</name>
	        <email>ronald.nikel@heuboe.de</email>
	    </developer>
	</developers>

	<properties>
	</properties>

	<dependencies>
		<dependency>
			<groupId>de.heuboe.tls</groupId>
			<artifactId>tls-tele</artifactId>
		</dependency>
        
	</dependencies>

</project>